### ISSUE TITLE
Windows Setup is hanging

### ISSUE THREAD

**Issue by marek22k** [yggdrasil-network/yggdrasil-go#1006]
OS: Windows XP SP3 with Legacy Updates
![Untitled](https://user-images.githubusercontent.com/46723399/209159759-84aee1a0-bb2d-443c-835c-9b9e44f452b4.png)
```
The Windows Installer Service could not be accessed. This can occur if you are running Windows in safe mode, or if the Windows Installer is not correctly installed. Contact your support personnel for assistance.
```
Tried with `yggdrasil-0.4.7-x64.msi` and `yggdrasil-0.4.7-x86.msi`.

**Comment by neilalexander** [comment]
The Wintun driver requires Windows 7 or later, so we won't be able to provide any support for Windows XP.

**Comment by JeanPaulLucien** [comment]
@marek22k Wintun for Windows XP is needed before.

**Comment by JeanPaulLucien** [comment]
@neilalexander
Is Wintun needed to setup Windows Installer environment? Write own installer is not hard to use WinAPI. I may take a look, just show code to me.
