### ISSUE TITLE
I can't seem to make Yggdrasil work anymore.

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/yggdrasil-go#1018]
It doesn't matter how I install it, from your repo or from the default Debian repo. I've generated the config file. I'm using tcp://kusoneko.moe:9002. I've enabled, started and restarted yggdrasil from systemctl, switched between Linux Mint and Linux Mint Debian Edition and still I can't load any of the Yggdrasil services.

**Comment by doosom** [comment]
Are you sure you are connected to any peer? What is the output of yggdrasilctl getpeers ?

You should see something like

`3   	60bec2d233589031b021790554dc1e2bb3e6987f0372f1a682b11a7a65f7d103	201:7d04:f4b7:329d:bf39:3f7a:1bea:ac8f	3s       	 1kb 	 1kb 	0 	tcp://kusoneko.moe:9002`

**Comment by styromaniac** [comment]
I had to use sudo yggdrasilctl getpeers. This is what it returned:

2023/02/18 15:48:41 Fatal error: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 80,1 >>> }

**Comment by doosom** [comment]
Check your config file. Seems you have some error there (line 80). Fix and restart.

**Comment by styromaniac** [comment]
> Check your config file. Seems you have some error there (line 80). Fix and restart. 
> 
> 

Yeah.  Right now I'm about to use a JSON file checker.

**Comment by styromaniac** [comment]
Is it possible that yggdrasil.conf is either being written incorrectly or read incorrectly?

**Comment by neilalexander** [comment]
Please post the log output from Yggdrasil, blanking out any parts you are concerned are sensitive.

**Comment by doosom** [comment]
> Is it possible that yggdrasil.conf is either being written incorrectly or read incorrectly?

I don't think so. Which parts did you modify in the initial file? Adding a peer should be enough for a start.

 "Peers": [
"tcp://kusoneko.moe:9002"
],

**Comment by ygguser** [comment]
The configuration file is not overwritten by itself.
It is more likely that you yourself violated its syntax when you made some changes.
In any case, if you can't restore it, find and fix the error, you can generate a new one:
```
sudo systemctl stop yggdrasil
sudo mv /etc/yggdrasil.conf /etc/yggdrasil.conf_old
sudo yggdrasil -genconf > /etc/yggdrasil.conf
```
Then you can carefully add the peers to it.
And start again: `sudo systemctl start yggdrasil`

If something goes wrong, you can always look at its logs like this:
```
sudo journalctl -u yggdrasil --since today -e
```

**Comment by ygguser** [comment]
Here is the correct variant:
```
Peers:
  [
    tcp://kusoneko.moe:9002
  ]
```

**Comment by ygguser** [comment]
Also, you can have a look here:
https://github.com/ygguser/peers_updater 😉

**Comment by styromaniac** [comment]
> > Is it possible that yggdrasil.conf is either being written incorrectly or read incorrectly?
> 
> I don't think so. Which parts did you modify in the initial file? Adding a peer should be enough for a start.
> 
> "Peers": [ "tcp://kusoneko.moe:9002" ],

When I generated the config, the syntax was a bit different than what you put in your comment, missing quotation marks and commas.

**Comment by styromaniac** [comment]
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Main process exited,>
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Failed with result '>
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Scheduled restart jo>
Feb 18 17:25:21 styromaniac systemd[1]: Stopped yggdrasil.
Feb 18 17:25:21 styromaniac systemd[1]: Starting yggdrasil...
Feb 18 17:25:21 styromaniac systemd[1]: Started yggdrasil.
Feb 18 17:25:21 styromaniac yggdrasil[16588]: panic: Found a punctuator charact>
Feb 18 17:25:21 styromaniac yggdrasil[16588]: goroutine 19 [running]:
Feb 18 17:25:21 styromaniac yggdrasil[16588]: main.readConfig(0x725468?, 0x4?, >
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-netw>
Feb 18 17:25:21 styromaniac yggdrasil[16588]: main.run({0x0, 0x0, 0x0, 0x0, 0x0>
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-netw>
Feb 18 17:25:21 styromaniac yggdrasil[16588]: main.main.func1()
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-netw>
Feb 18 17:25:21 styromaniac yggdrasil[16588]: created by main.main
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-netw>
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Main process exited,>
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Failed with result '>
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Scheduled restart jo>
Feb 18 17:25:21 styromaniac systemd[1]: Stopped yggdrasil.
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Start request repeat>
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Failed with result '>
Feb 18 17:25:21 styromaniac systemd[1]: Failed to start yggdrasil.
lines 810-832/832 (END)
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Failed with result 'exit-code'.
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Scheduled restart job, restart counter is at 4.
Feb 18 17:25:21 styromaniac systemd[1]: Stopped yggdrasil.
Feb 18 17:25:21 styromaniac systemd[1]: Starting yggdrasil...
Feb 18 17:25:21 styromaniac systemd[1]: Started yggdrasil.
Feb 18 17:25:21 styromaniac yggdrasil[16588]: panic: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 80,1 >>> }
Feb 18 17:25:21 styromaniac yggdrasil[16588]: goroutine 19 [running]:
Feb 18 17:25:21 styromaniac yggdrasil[16588]: main.readConfig(0x725468?, 0x4?, {0x7ffd11743e87?, 0x5?}, 0x0?)
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-network/yggdrasil-go/cmd/yggdrasil/main.go:83 +0x24e
Feb 18 17:25:21 styromaniac yggdrasil[16588]: main.run({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x7ffd11743e87, 0x1d}, ...}, ...)
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-network/yggdrasil-go/cmd/yggdrasil/main.go:226 +0xb4c
Feb 18 17:25:21 styromaniac yggdrasil[16588]: main.main.func1()
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-network/yggdrasil-go/cmd/yggdrasil/main.go:405 +0x85
Feb 18 17:25:21 styromaniac yggdrasil[16588]: created by main.main
Feb 18 17:25:21 styromaniac yggdrasil[16588]:         github.com/yggdrasil-network/yggdrasil-go/cmd/yggdrasil/main.go:403 +0x1ab
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Failed with result 'exit-code'.
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Scheduled restart job, restart counter is at 5.
Feb 18 17:25:21 styromaniac systemd[1]: Stopped yggdrasil.
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Start request repeated too quickly.
Feb 18 17:25:21 styromaniac systemd[1]: yggdrasil.service: Failed with result 'exit-code'.
Feb 18 17:25:21 styromaniac systemd[1]: Failed to start yggdrasil.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 810-832/832 (END)

**Comment by styromaniac** [comment]
> > Is it possible that yggdrasil.conf is either being written incorrectly or read incorrectly?
> 
> I don't think so. Which parts did you modify in the initial file? Adding a peer should be enough for a start.
> 
> "Peers": [ "tcp://kusoneko.moe:9002" ],

That's all I did.

**Comment by styromaniac** [comment]
I reinstalled LMDE in case there was anything I did wrong. The package from the default repo and I believe your repo both do not generate /etc/yggdrasil/yggdrasil.conf, so I generated it and set the owner/group to yggdrasil and I've also enabled it to execute.

Here's what I get from yggdrasilctl restart:

2023/02/18 22:36:08 Can't open config file from default location /etc/yggdrasil/yggdrasil.conf
2023/02/18 22:36:08 Falling back to platform default unix:///var/run/yggdrasil/yggdrasil.sock
2023/02/18 22:36:08 Connecting to UNIX socket /var/run/yggdrasil/yggdrasil.sock
2023/02/18 22:36:08 Fatal error: dial unix /var/run/yggdrasil/yggdrasil.sock: connect: no such file or directory

**Comment by styromaniac** [comment]
I noticed the Yggdrasil version from your repo creates /etc/yggdrasil.conf, but editing in the peer between the square brackets without quotation marks and saving it before `sudo systemctl restart` does nothing.

**Comment by ygguser** [comment]
Put it here: `cat /etc/systemd/system/yggdrasil.service`
And: `yggdrasil --version`

**Comment by ygguser** [comment]
And also, you can run yggdrasil not from systemd unit, but just like that: `sudo yggdrasil -useconffile <path to your conf>` to see what's going on.

**Comment by styromaniac** [comment]
```
[Unit]
Description=yggdrasil
Wants=network-online.target
Wants=yggdrasil-default-config.service
After=network-online.target
After=yggdrasil-default-config.service

[Service]
Group=yggdrasil
ProtectHome=true
ProtectSystem=true
SyslogIdentifier=yggdrasil
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
ExecStartPre=+-/sbin/modprobe tun
ExecStart=/usr/bin/yggdrasil -useconffile /etc/yggdrasil.conf
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
TimeoutStopSec=5

[Install]
WantedBy=multi-user.target
```
```
Build name: yggdrasil
Build version: 0.4.7
```
```
sudo yggdrasil -useconffile /etc/yggdrasil.conf
[sudo] password for styromaniac:                                       
panic: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 80,1 >>> }


goroutine 9 [running]:
main.readConfig(0x7236c3?, 0x4?, {0x7ffe38f4987a?, 0x5?}, 0x1?)
	/home/runner/work/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:83 +0x24e
main.run({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x7ffe38f4987a, 0x13}, ...}, ...)
	/home/runner/work/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:226 +0xa2c
main.main.func1()
	/home/runner/work/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:405 +0x85
created by main.main
	/home/runner/work/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:403 +0x1ab
```

**Comment by ygguser** [comment]
It can be seen from the systemd unit that it uses the `/etc/yggdrasil.conf` config, and there is an error in it. Why can't you fix this file or replace it with a new one?

**Comment by styromaniac** [comment]
```
{
  # List of connection strings for outbound peer connections in URI format,
  # e.g. tls://a.b.c.d:e or socks://a.b.c.d:e/f.g.h.i:j. These connections
  # will obey the operating system routing table, therefore you should
  # use this section when you may connect via different interfaces.
  Peers: [tcp://kusoneko.moe:9002]

  # List of connection strings for outbound peer connections in URI format,
  # arranged by source interface, e.g. { "eth0": [ "tls://a.b.c.d:e" ] }.
  # Note that SOCKS peerings will NOT be affected by this option and should
  # go in the "Peers" section instead.
  InterfacePeers: {}

  # Listen addresses for incoming connections. You will need to add
  # listeners in order to accept incoming peerings from non-local nodes.
  # Multicast peer discovery will work regardless of any listeners set
  # here. Each listener should be specified in URI format as above, e.g.
  # tls://0.0.0.0:0 or tls://[::]:0 to listen on all interfaces.
  Listen: []

  # Listen address for admin connections. Default is to listen for local
  # connections either on TCP/9001 or a UNIX socket depending on your
  # platform. Use this value for yggdrasilctl -endpoint=X. To disable
  # the admin socket, use the value "none" instead.
  AdminListen: unix:///var/run/yggdrasil.sock

  # Configuration for which interfaces multicast peer discovery should be
  # enabled on. Each entry in the list should be a json object which may
  # contain Regex, Beacon, Listen, and Port. Regex is a regular expression
  # which is matched against an interface name, and interfaces use the
  # first configuration that they match gainst. Beacon configures whether
  # or not the node should send link-local multicast beacons to advertise
  # their presence, while listening for incoming connections on Port.
  # Listen controls whether or not the node listens for multicast beacons
  # and opens outgoing connections.
  MulticastInterfaces:
  [
    {
      Regex: .*
      Beacon: true
      Listen: true
      Port: 0
      Priority: 0
    }
  ]

  # List of peer public keys to allow incoming peering connections
  # from. If left empty/undefined then all connections will be allowed
  # by default. This does not affect outgoing peerings, nor does it
  # affect link-local peers discovered via multicast.
  AllowedPublicKeys: []

  # Your public key. Your peers may ask you for this to put
  # into their AllowedPublicKeys configuration.
  PublicKey: e25a9b1ea832a370b12b81f25385f45d83eaf3a3956ec56f0f1760f0096599d8

  # Your private key. DO NOT share this with anyone!
  PrivateKey: 60b39a1a6076bd6d9987162daee85f1423491f753e64a18f1c937d11eb30dff3e25a9b1ea832a370b12b81f25385f45d83eaf3a3956ec56f0f1760f0096599d8

  # Local network interface name for TUN adapter, or "auto" to select
  # an interface automatically, or "none" to run without TUN.
  IfName: auto

  # Maximum Transmission Unit (MTU) size for your local TUN interface.
  # Default is the largest supported size for your platform. The lowest
  # possible value is 1280.
  IfMTU: 65535

  # By default, nodeinfo contains some defaults including the platform,
  # architecture and Yggdrasil version. These can help when surveying
  # the network and diagnosing network routing problems. Enabling
  # nodeinfo privacy prevents this, so that only items specified in
  # "NodeInfo" are sent back if specified.
  NodeInfoPrivacy: false

  # Optional node info. This must be a { "key": "value", ... } map
  # or set as null. This is entirely optional but, if set, is visible
  # to the whole network on request.
  NodeInfo: {}
}
```

**Comment by ygguser** [comment]
This is a correct file (just tested):

```
{
  # List of connection strings for outbound peer connections in URI format,
  # e.g. tls://a.b.c.d:e or socks://a.b.c.d:e/f.g.h.i:j. These connections
  # will obey the operating system routing table, therefore you should
  # use this section when you may connect via different interfaces.
  Peers: [
    tcp://kusoneko.moe:9002
  ]

  # List of connection strings for outbound peer connections in URI format,
  # arranged by source interface, e.g. { "eth0": [ "tls://a.b.c.d:e" ] }.
  # Note that SOCKS peerings will NOT be affected by this option and should
  # go in the "Peers" section instead.
  InterfacePeers: {}

  # Listen addresses for incoming connections. You will need to add
  # listeners in order to accept incoming peerings from non-local nodes.
  # Multicast peer discovery will work regardless of any listeners set
  # here. Each listener should be specified in URI format as above, e.g.
  # tls://0.0.0.0:0 or tls://[::]:0 to listen on all interfaces.
  Listen: []

  # Listen address for admin connections. Default is to listen for local
  # connections either on TCP/9001 or a UNIX socket depending on your
  # platform. Use this value for yggdrasilctl -endpoint=X. To disable
  # the admin socket, use the value "none" instead.
  AdminListen: none

  # Configuration for which interfaces multicast peer discovery should be
  # enabled on. Each entry in the list should be a json object which may
  # contain Regex, Beacon, Listen, and Port. Regex is a regular expression
  # which is matched against an interface name, and interfaces use the
  # first configuration that they match gainst. Beacon configures whether
  # or not the node should send link-local multicast beacons to advertise
  # their presence, while listening for incoming connections on Port.
  # Listen controls whether or not the node listens for multicast beacons
  # and opens outgoing connections.
  MulticastInterfaces: []

  # List of peer public keys to allow incoming peering connections
  # from. If left empty/undefined then all connections will be allowed
  # by default. This does not affect outgoing peerings, nor does it
  # affect link-local peers discovered via multicast.
  AllowedPublicKeys: []

  # Your public key. Your peers may ask you for this to put
  # into their AllowedPublicKeys configuration.
  PublicKey: e25a9b1ea832a370b12b81f25385f45d83eaf3a3956ec56f0f1760f0096599d8

  # Your private key. DO NOT share this with anyone!
  PrivateKey: 60b39a1a6076bd6d9987162daee85f1423491f753e64a18f1c937d11eb30dff3e25a9b1ea832a370b12b81f25385f45d83eaf3a3956ec56f0f1760f0096599d8

  # Local network interface name for TUN adapter, or "auto" to select
  # an interface automatically, or "none" to run without TUN.
  IfName: auto

  # Maximum Transmission Unit (MTU) size for your local TUN interface.
  # Default is the largest supported size for your platform. The lowest
  # possible value is 1280.
  IfMTU: 65535

  # By default, nodeinfo contains some defaults including the platform,
  # architecture and Yggdrasil version. These can help when surveying
  # the network and diagnosing network routing problems. Enabling
  # nodeinfo privacy prevents this, so that only items specified in
  # "NodeInfo" are sent back if specified.
  NodeInfoPrivacy: false

  # Optional node info. This must be a { "key": "value", ... } map
  # or set as null. This is entirely optional but, if set, is visible
  # to the whole network on request.
  NodeInfo: {}
}
```

**Comment by styromaniac** [comment]
> This is a correct file (just tested):
> 
> ```
> {
>   # List of connection strings for outbound peer connections in URI format,
>   # e.g. tls://a.b.c.d:e or socks://a.b.c.d:e/f.g.h.i:j. These connections
>   # will obey the operating system routing table, therefore you should
>   # use this section when you may connect via different interfaces.
>   Peers: [
>     tcp://kusoneko.moe:9002
>   ]
> 
>   # List of connection strings for outbound peer connections in URI format,
>   # arranged by source interface, e.g. { "eth0": [ "tls://a.b.c.d:e" ] }.
>   # Note that SOCKS peerings will NOT be affected by this option and should
>   # go in the "Peers" section instead.
>   InterfacePeers: {}
> 
>   # Listen addresses for incoming connections. You will need to add
>   # listeners in order to accept incoming peerings from non-local nodes.
>   # Multicast peer discovery will work regardless of any listeners set
>   # here. Each listener should be specified in URI format as above, e.g.
>   # tls://0.0.0.0:0 or tls://[::]:0 to listen on all interfaces.
>   Listen: []
> 
>   # Listen address for admin connections. Default is to listen for local
>   # connections either on TCP/9001 or a UNIX socket depending on your
>   # platform. Use this value for yggdrasilctl -endpoint=X. To disable
>   # the admin socket, use the value "none" instead.
>   AdminListen: none
> 
>   # Configuration for which interfaces multicast peer discovery should be
>   # enabled on. Each entry in the list should be a json object which may
>   # contain Regex, Beacon, Listen, and Port. Regex is a regular expression
>   # which is matched against an interface name, and interfaces use the
>   # first configuration that they match gainst. Beacon configures whether
>   # or not the node should send link-local multicast beacons to advertise
>   # their presence, while listening for incoming connections on Port.
>   # Listen controls whether or not the node listens for multicast beacons
>   # and opens outgoing connections.
>   MulticastInterfaces: []
> 
>   # List of peer public keys to allow incoming peering connections
>   # from. If left empty/undefined then all connections will be allowed
>   # by default. This does not affect outgoing peerings, nor does it
>   # affect link-local peers discovered via multicast.
>   AllowedPublicKeys: []
> 
>   # Your public key. Your peers may ask you for this to put
>   # into their AllowedPublicKeys configuration.
>   PublicKey: e25a9b1ea832a370b12b81f25385f45d83eaf3a3956ec56f0f1760f0096599d8
> 
>   # Your private key. DO NOT share this with anyone!
>   PrivateKey: 60b39a1a6076bd6d9987162daee85f1423491f753e64a18f1c937d11eb30dff3e25a9b1ea832a370b12b81f25385f45d83eaf3a3956ec56f0f1760f0096599d8
> 
>   # Local network interface name for TUN adapter, or "auto" to select
>   # an interface automatically, or "none" to run without TUN.
>   IfName: auto
> 
>   # Maximum Transmission Unit (MTU) size for your local TUN interface.
>   # Default is the largest supported size for your platform. The lowest
>   # possible value is 1280.
>   IfMTU: 65535
> 
>   # By default, nodeinfo contains some defaults including the platform,
>   # architecture and Yggdrasil version. These can help when surveying
>   # the network and diagnosing network routing problems. Enabling
>   # nodeinfo privacy prevents this, so that only items specified in
>   # "NodeInfo" are sent back if specified.
>   NodeInfoPrivacy: false
> 
>   # Optional node info. This must be a { "key": "value", ... } map
>   # or set as null. This is entirely optional but, if set, is visible
>   # to the whole network on request.
>   NodeInfo: {}
> }
> ```

You're right. I thought I had tried it like you had. I'm sorry for wasting you and others' time. It works now. Now I just need to generate a new conf
