### ISSUE TITLE
Arch: yggdrasil.sock error

### ISSUE THREAD

**Issue by chicorykvass** [yggdrasil-network/yggdrasil-go#1019]
I have yggdrasil on my OpenSUSE TW PC and it works great but now on freshly installed Arch Linux on my laptop it always gives me:

`Fatal error: dial unix /var/run/yggdrasil/yggdrasil.sock: connect: no such file or directory`

If I create yggdrasil.sock, it says 'connection refused' instead. I tried researching Google but found nothing to solve the problem.

**Comment by chicorykvass** [comment]
Solved pertially by editing yggdrasil service to point to /usr/local/bin instead of /usr/bin. yggdrasilctl still doesn't work, so I have to add peers to yggdrasil.conf manually.

**Comment by ygguser** [comment]
>… I have to add peers to yggdrasil.conf manually.

Maybe you will find it useful: https://github.com/ygguser/peers_updater
