### ISSUE TITLE
Multicast groups INSIDE the Yggdrasil network?

### ISSUE THREAD

**Issue by Evengard** [yggdrasil-network/yggdrasil-go#1020]
There's a thing in IP networks (IPv6 included) as multicast groups, where a peer subscribes to a multicast address, and receives everything sent to it "automagically". Well, apparently this mechanism is used by Yggdrasil itself for peers discovery.

Now, is there a possibility to actually have multicasting from INSIDE the Yggdrasil network? It would be nice to have a network where you could easily do global multicasting quite easily, and would probably help in making Yggdrasil more widespread - this way Yggdrasil could be the one stop utility for anything peer-to-peer, handling all the intricasies of NAT traversal, and with global multicasting making the peer discovery a real breese.

**Comment by neilalexander** [comment]
The reason we don't support multicasting inside Yggdrasil today is that we haven't yet figured out a way to do so sensibly at scale. There are two problems:

1. How to distribute group memberships in an efficient fashion, without flooding the entire network;
2. How to determine the allowed sources of a group.

**Comment by perguth** [comment]
>  the one stop utility for anything peer-to-peer, handling all the intricasies of NAT traversal, and with global multicasting making the peer discovery a real breese.

That's [Hyperswarm](https://github.com/holepunchto/hyperswarm).
