### ISSUE TITLE
yggdrasil uses deprecated link local address when attempting to respond to multicast peering

### ISSUE THREAD

**Issue by dlakelan** [yggdrasil-network/yggdrasil-go#1023]
On my router I run keepalived which wants a "virtual" link local address, so I use fe80::1:1:1 on my LAN.

yggdrasil running on this router sends out multicast notifications using the "usual" link local address, and then when it hears a peer on the LAN it sends a TCP connection from fe80::1:1:1 which is listed as "deprecated" rather than the "regular" link local address. These are seen as not allowed by my firewall and dropped, yggdrasil floods my desktop with these SYN requests

The router it's running on has these link local addresses:

```
    inet6 fe80::1:1:1/128 scope link nodad deprecated 
       valid_lft forever preferred_lft 0sec
    inet6 fe80::dea6:32ff:fe63:c27f/64 scope link 
       valid_lft forever preferred_lft forever
```

yggdrasil should use a consistent source address and should choose the non-deprecated address as its source address.

I've fixed this in my firewall so it works fine, but it seems like the wrong behavior to choose the deprecated address as the source.

**Comment by neilalexander** [comment]
I don't think we can fix this as the deprecated state is not available to us via the Go stdlib, so it'll try to use the first matching link-local address that is up.
