### ISSUE TITLE
Design rationale behind allowing peers to choose MTU?

### ISSUE THREAD

**Issue by turretkeeper** [yggdrasil-network/yggdrasil-go#1024]
From what I hear, IPv6 does not accept packets higher than the interface MTU, period. I won't pretend to know this for sure, but it sounds like allowing to choose different MTUs would be a recipe for overhead just for negotiation, if such negotiation even exists. Why does Yggdrasil not standardize it in a similar way address space is a defined standard?

**Comment by neilalexander** [comment]
When you send a packet to a remote node, Yggdrasil automatically exchanges the MTU as a part of the session setup and the lower of the local & remote MTU values is chosen as the effective session MTU.

If you send a packet larger than the effective session MTU, Yggdrasil generates and sends back an ICMPv6 Packet Too Big notification back to the sending application which causes the application/network stack to adjust future packet sizes down to the required size, which is the exact same mechanism by which Path MTU Discovery (PMTUD) normally works on other IPv6 networks (although normally it would be intermediate routers generating that notification instead).

Doing this means that pairs of nodes that support larger MTUs will be able to benefit from reduced overheads and increased throughput, but if you send a packet to a node that only supports smaller MTUs, Yggdrasil will do the right thing and tell userspace about the reduced MTU.

**Comment by turretkeeper** [comment]
Thank you. Is there a use case where limiting the MTU past the underlying limit would pose an advantage?

**Comment by neilalexander** [comment]
Because Yggdrasil’s peerings are TCP-based, we aren’t really limited by the underlying MTU at all. The TCP stream will operate at the usual underlying link MTU and we can continue to send larger packets over it, as TCP will segment them and enforce ordering automatically.

**Comment by neilalexander** [comment]
The origin of the session MTU exchange is because the maximum MTU varies between different platforms, i.e. max 65535 works on macOS/Linux/Windows, 32767 on FreeBSD, 16384 on OpenBSD. It also occasionally makes sense to be able to reduce the MTU if you are routing your `/64` routed subnet down a pipe with a lesser MTU, i.e. most links.

Most of the time, users will have no reason to change this option though and the default is sane.

**Comment by turretkeeper** [comment]
That makes sense, thank you.
