### ISSUE TITLE
Missing RPM package for Fedora38

### ISSUE THREAD

**Issue by Dirk1980ac** [yggdrasil-network/yggdrasil-go#1030]
I just upgraded to the fresh Fedora 38 and noticed that Yggdrasil-Go is not available anymore because there is no Build for Fedora 38 available in the copr repository.

Could you please enable Fedora 38 builds, if possible?

Kind regards,
Dirk

**Comment by neilalexander** [comment]
Done: https://copr.fedorainfracloud.org/coprs/neilalexander/yggdrasil-go/build/5803561/

**Comment by Dirk1980ac** [comment]
Thank you very much.
