### ISSUE TITLE
What application did you use to create the Windows msi installer?

### ISSUE THREAD

**Issue by lonnietc** [yggdrasil-network/yggdrasil-go#1059]
Hello,

I am researching using Yggdrasil since it has vastly improved over the years now and I really like what I have seen when testing it out lately.

With that in mind, I want to bundle it in a test application that will have a system tray (systray) controller and want to bundle that together.

What was used to create the msi installers for the Windows platform?
Thanks

**Comment by lonnietc** [comment]
Thanks and I will look into the contrib folder more as well.

I have never used the Matrix Chat stuff so all of that is still new to mew, but I have corresponded with some folks via email, Discord, and Slack.

Maybe I should look into some of the Matrix stuff more.

Thanks again.

**Comment by neilalexander** [comment]
Closing as answered.
