### ISSUE TITLE
Rewrite in non-GC'd language and/or publish spec

### ISSUE THREAD

**Issue by vegabook** [yggdrasil-network/yggdrasil-go#1066]
Go's GC makes it cumbersome to integrate into other language stacks, such as Erlang/Elixir BEAM, Rust, Python etc. This also makes it difficult to embed Yggdrasil into userspace applications as it requires Yggdrasil-go to be installed separately. 

A C or Rust library ideally (or Zig) would remove this limitation. 

Would you consider publishing a spec so that a non-Golang implementation can be written? I'd be prepared to offer funding of up to 250 USD per month (no strings attached apart from the above requirement) which might stimulate others to do same.

**Comment by xlmnxp** [comment]
what is the benefit?
Yggdrasil is already installable in userspac using docker or give network permission to executable

**Comment by arrza** [comment]
I have implemented yggdrasil in rust,
https://github.com/arrza/yggdrasil-rs,
It is working but lacks multicast yet.

**Comment by Arceliar** [comment]
The goal is to publish a spec eventually (or an RFC that leads to a better spec being developed by people who know what they're doing to e.g. design it so it's efficiently implementable in hardware).

This is a research project, so things change significantly from (major) release to release. I could just keep all that work private, but some people seem to find it a useful tool, and it's helpful to have things tested in the real world (up to a point, eventually all the bug reports are duplicates and more users would only slow things down), so I prefer to keep things public.

We tried writing a spec in the past, for v0.3, but it quickly became out dated and irrelevant. From my perspective, it just doesn't make sense to try to publish a spec and keep it in sync with the code base, or provide another implementation, until the project is close to "done" and no major changes are expected to the on-the-wire format or important behaviors. The community is of course free to do what they want, but I have very limited time to work on ygg, so I need to spend it working on R&D and implementing any changes to the routing scheme.

**Comment by vegabook** [comment]
> what is the benefit? Yggdrasil is already installable in userspac using docker or give network permission to executable

The benefit is to be able to distribute applications/apps that do not separately have to have another stack installed by potentially non-technical end users. Asking the average person to pull a docker container is not realistic in this use case. My personal (selfish) desire is for a mesh-based financial data platform that I'm writing in Elixir. The "private VPS" nature of yggdrasil is very attractive in this use case but again, I don't want to have to get people who are not computer people, to have to start docker-ing or editing config files. A C or Rust implementation can be compiled right into the BEAM.

**Comment by vegabook** [comment]
> I have implemented yggdrasil in rust, https://github.com/arrza/yggdrasil-rs, It is working but lacks multicast yet.

Feel free to [contact me](https://github.com/vegabook)

**Comment by vegabook** [comment]
> The goal is to publish a spec eventually (or an RFC that leads to a better spec being developed by people who know what they're doing to e.g. design it so it's efficiently implementable in hardware).
> 
> This is a research project, so things change significantly from (major) release to release. I could just keep all that work private, but some people seem to find it a useful tool, and it's helpful to have things tested in the real world (up to a point, eventually all the bug reports are duplicates and more users would only slow things down), so I prefer to keep things public.
> 
> We tried writing a spec in the past, for v0.3, but it quickly became out dated and irrelevant. From my perspective, it just doesn't make sense to try to publish a spec and keep it in sync with the code base, or provide another implementation, until the project is close to "done" and no major changes are expected to the on-the-wire format or important behaviors. The community is of course free to do what they want, but I have very limited time to work on ygg, so I need to spend it working on R&D and implementing any changes to the routing scheme.

Cool. Well, if there's anything I can do to speed things up towards a 1.0 feel free to contact me.

**Comment by Arceliar** [comment]
> > what is the benefit? Yggdrasil is already installable in userspac using docker or give network permission to executable
> 
> The benefit is to be able to distribute applications/apps that do not separately have to have another stack installed by potentially non-technical end users. Asking the average person to pull a docker container is not realistic in this use case. My personal (selfish) desire is for a mesh-based open financial data distribution platform that I'm writing in Elixir, meant to chip away at the big proprietary stacks (Bloomberg, Reuters, etc). The "private VPS" nature of yggdrasil is very attractive in this use case but again, I don't want to have to get people who are not computer people, to have to start docker-ing or editing config files. A C or Rust implementation can be compiled right into the BEAM or into a C/Rust/Kotlin/Swift/whatever application

FWIW, the Android and iOS apps are in Kotlin and Swift, respectively, using gomobile to export an interface those languages can call. It's possible to do something similar with cgo, you just need to wrap the important API functions in code that takes and returns C-friendly types. I *think* the code in [contrib/mobile](https://github.com/yggdrasil-network/yggdrasil-go/tree/develop/contrib/mobile) is already most of the way there. Exposing a C-friendly user-facing API is a small enough addition that we could probably do it, if there's enough of a demand / a good enough use case for it.
