### ISSUE TITLE
Mention of DHT in the examples displayed by yggdrasilctl 0.5

### ISSUE THREAD

**Issue by ufm** [yggdrasil-network/yggdrasil-go#1069]
https://github.com/yggdrasil-network/yggdrasil-go/blob/90c6288f7c2ab2b20d19856387a6c148041ee26d/cmd/yggdrasilctl/cmd_line_env.go#L42-L43

I thought there was no DHT in version 0.5? Did you forget to update the examples?

**Comment by neilalexander** [comment]
Yes, it looks like we forgot to update the examples. Will fix.
