### ISSUE TITLE
Too very fresh libc dependency

### ISSUE THREAD

**Issue by POPSuL** [yggdrasil-network/yggdrasil-go#1071]
On 0.5-rc3 I got next error:
```
окт 26 23:49:42 popsul-pc yggdrasil[988458]: /usr/bin/yggdrasil: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/yggdrasil)
```
But I've LTS ubuntu 20.04, and it have only `2.31-0ubuntu9`.
I think your should downgrade version of `libc`.

**Comment by neilalexander** [comment]
We already did, in 7934158, it's just that we haven't cut another RC since.

**Comment by POPSuL** [comment]
Ok, Thank you. I'll wait it!
