### ISSUE TITLE
Yggdrqasil 0.5.1 not connecting to 0.4.7 peers

### ISSUE THREAD

**Issue by derpindialer** [yggdrasil-network/yggdrasil-go#1079]
After upgrading to 0.5.1, I am no longer able to connect to peers running 0.4.7. Is there a compatibility issue? I have restarted 0.5.1 to see if there was an issue there. When I run `yggdrasilctl getpeers` it shows all my peers as down. I checked peers, and they are up and connectable by 0.4.7.

**Comment by neilalexander** [comment]
0.5.x is not compatible with 0.4.x. 

From the changelog:
> New routing scheme, which is backwards incompatible with previous versions of Yggdrasil

**Comment by derpindialer** [comment]
Thanks Neil, I should have read the changelog.
