### ISSUE TITLE
GoLang 1.21 build error

### ISSUE THREAD

**Issue by olej-tsil-51** [yggdrasil-network/yggdrasil-go#1092]
olej@esprimop420:~/2023/Yggdrasil/yggdrasil-go$ go version
go version devel go1.21-b37c0602cd Tue Mar 14 10:02:09 2023 +0000 linux/amd64

olej@esprimop420:~/2023/Yggdrasil/yggdrasil-go$ time ./build
Building: yggdrasil
github.com/quic-go/quic-go/internal/qtls
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:14:33: undefined: tls.QUICConn
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:15:33: undefined: tls.QUICConfig
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:16:33: undefined: tls.QUICEvent
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:17:33: undefined: tls.QUICEventKind
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:18:33: undefined: tls.QUICEncryptionLevel
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:19:33: undefined: tls.QUICSessionTicketOptions
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:20:33: undefined: tls.AlertError
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:24:39: undefined: tls.QUICEncryptionLevelInitial
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:25:39: undefined: tls.QUICEncryptionLevelEarly
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:26:39: undefined: tls.QUICEncryptionLevelHandshake
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.39.3/internal/qtls/go121.go:26:39: too many errors

real	0m0,122s
user	0m0,294s
sys	0m0,063s

**Comment by neilalexander** [comment]
It looks like you are on an unstable Go build?

**Comment by olej-tsil-51** [comment]
You are right, I inadvertently compiled GoLang from the development branch. Now I've fixed it:
$ git checkout go1.21.3
...
$ git fetch
...
$ cd src
$ export GOROOT_BOOTSTRAP=/usr/local/go; time ./all.bash
...
$ go version
go version go1.21.3 linux/amd64

And Yggdrasil build... 
$ pwd
/home/olej/2023/Yggdrasil/yggdrasil-go
$ ./build
...
$ yggdrasil --version
Build name: yggdrasil
Build version: 0.5.1

Thanks for the tip!
