### ISSUE TITLE
0.5.1 inconclusive error reporting during TUN device setup

### ISSUE THREAD

**Issue by ERnsTL** [yggdrasil-network/yggdrasil-go#1093]
I got yggdrasil set up using the one-off 0.5.1 deb package from Github; but I get a "permission denied" error on startup

```
Nov 04 09:46:51 as314 yggdrasil[270016]: 2023/11/04 09:46:51 Build name: yggdrasil
Nov 04 09:46:51 as314 yggdrasil[270016]: 2023/11/04 09:46:51 Build version: 0.5.1
Nov 04 09:46:51 as314 yggdrasil[270016]: 2023/11/04 09:46:51 Your public key is ...
Nov 04 09:46:51 as314 yggdrasil[270016]: 2023/11/04 09:46:51 Your IPv6 address is ...
Nov 04 09:46:51 as314 yggdrasil[270016]: 2023/11/04 09:46:51 Your IPv6 subnet is ...
Nov 04 09:46:51 as314 yggdrasil[270016]: 2023/11/04 09:46:51 UNIX admin socket listening on /var/run/yggdrasil/yggdrasil.sock
Nov 04 09:46:51 as314 yggdrasil[270016]: 2023/11/04 09:46:51 TLS listener started on ...
Nov 04 09:46:51 as314 yggdrasil[270016]: panic: permission denied
Nov 04 09:46:51 as314 yggdrasil[270016]: goroutine 1 [running]:
Nov 04 09:46:51 as314 yggdrasil[270016]: main.main()
Nov 04 09:46:51 as314 yggdrasil[270016]:         /home/runner/work/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:260 +0x2166
Nov 04 09:46:51 as314 systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

The error reporting in this case is not very helpful - 

The source code at line 260 just says "tun.Create", but I am not sure at what syscall / function the permission was denied - what did yggdrasil try to do which led to the permission error?

Please extend the error reporting at this point.

I have already set the necessary capability:

```
sudo setcap cap_net_admin=ep /usr/bin/yggdrasil
```

Not sure what else could go wrong.

**Comment by neilalexander** [comment]
Absolutely agree that the error reporting could be better here, I will look to improve it.

In the meantime, have you got something on your system (e.g. SELinux) that could be preventing Yggdrasil from creating a TUN?

**Comment by ERnsTL** [comment]
@neilalexander thanks for improving the error reporting! The setup is a standard Ubuntu 22.04 laptop; I dont recall changing SELinux-related settings.

**Comment by ERnsTL** [comment]
@neilalexander with v0.5.2 the error has changed to

```
Nov 06 21:47:23 as314 yggdrasil[348223]: panic: failed to add address to link: permission denied
Nov 06 21:47:23 as314 yggdrasil[348223]: goroutine 1 [running]:
Nov 06 21:47:23 as314 yggdrasil[348223]: main.main()
Nov 06 21:47:23 as314 yggdrasil[348223]:         /home/runner/work/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:265 +0x2286
Nov 06 21:47:23 as314 systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by ERnsTL** [comment]
@neilalexander Found the solution :-) Unrelated to yggdrasil, but maybe still of interest to future people.

---

When I run the commands manually, the error also appears:

```
sudo ip tuntap add name tun1 mode tun
sudo ip link set dev tun1 up
sudo ip addr add 200:xxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx dev tun1
```

also gives ```RTNETLINK answers: Permission denied```. How strange. I have multiple VPN programs in use on my machine (Ubuntu 22.04) with multiple tun devices and they dont have this issue. But they all have only IPv4 addresses...

```
sudo ip addr add 10.123.123.123 dev tun1
```

lol, this works. I found this issue there:  https://github.com/moby/moby/issues/32619

This solved the issue:

```
sudo sysctl net.ipv6.conf.all.disable_ipv6=0
```

I put this into the /etc/sysctl.conf file and yggdrasil started up nicely since then.
