### ISSUE TITLE
Error empty when connecting to old node

### ISSUE THREAD

**Issue by mkg20001** [yggdrasil-network/yggdrasil-go#1097]
I've got a bunch of peers and some of them are on older versions of yggdrasil

They show an empty error under last error

```
tcp://94.130.203.208:5999                           	Down 	Out	                                      	0s        	 0kb 	 0kb  	0 	0s ago:                                               	
````

It's a public peer and from one of the 0.4.7 nodes I can reach it, so it's just running an incompatible version

Instead of having an empty error I expect some message about the version being too old

**Comment by neilalexander** [comment]
#1091 addresses this.
