### ISSUE TITLE
panic: this should never happen

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#1100]
Version: 0.5.2
```
panic: this should never happen

goroutine 1872154 [running]:
github.com/Arceliar/ironwood/network.(*traffic).encode(0xc00009c3f0, {0xc000f460
00?, 0x3, 0xc4efe0?})
        C:/Users/runneradmin/go/pkg/mod/github.com/!arceliar/ironwood@v0.0.0-202
31104025256-ec84c695fc44/network/traffic.go:45 +0x567
github.com/Arceliar/ironwood/network.wireEncode({0xc000f46000?, 0xc0003ec5a0?, 0
x9bad38?}, 0x28?, {0x9b8890?, 0xc00009c3f0?})
        C:/Users/runneradmin/go/pkg/mod/github.com/!arceliar/ironwood@v0.0.0-202
31104025256-ec84c695fc44/network/wire.go:65 +0x75
github.com/Arceliar/ironwood/network.(*peerWriter).sendPacket.func1()
        C:/Users/runneradmin/go/pkg/mod/github.com/!arceliar/ironwood@v0.0.0-202
31104025256-ec84c695fc44/network/peers.go:207 +0x1bc
github.com/Arceliar/phony.(*Inbox).run(0xc0003ec678)
        C:/Users/runneradmin/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-202209
03101357-530938a4b13d/actor.go:98 +0x33
created by github.com/Arceliar/phony.(*Inbox).restart
        C:/Users/runneradmin/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-202209
03101357-530938a4b13d/actor.go:132 +0x56
```

**Comment by Arceliar** [comment]
Thanks for the report. Does this happen randomly, or do you have a way to reproduce it?

I genuinely have no idea what could be going wrong here. The panic comes from the encode method. Basically, it concatenates some `[]byte` slices together, and then checks that the length is equal to the sum of the lengths of the individual slices. There isn't a lot of room for mistakes. The object being encoded is a `traffic` struct, and those are normally stored/retrieved from a pool (to cut down on wasted allocations), so I suppose it's possible that there's a data race if things were incorrectly shared. It's possible there's a race that hasn't been caught by the race detector, but that's unlikely. I can't think of anything else that would cause let us reach the `panic`.

**Comment by Arceliar** [comment]
I think this should be fixed in `develop` (as of https://github.com/yggdrasil-network/yggdrasil-go/commit/6677d70648b076d25a8db0dfe5fe886e7ae3190e). There was a data race in one field of the `traffic` packet, which made it possible for one field of the packet to become corrupted if under heavy load (the `from` coords, used to send back errors if e.g. a packet drops). If the field was overwritten by coords of a different length while the packet was being encoded, then the expected size could differ from the size that was written to the slice, which triggers the panic.

**Comment by Vort** [comment]
> Does this happen randomly, or do you have a way to reproduce it?

It happens without my intervention.
However, there are several services hosted on my address.
Also I allow incoming peering connections from users.

So it may be users who trigger this problem.
Also my computer have high load because of non-Ygg related tasks.
Maybe that's why I see this problem more than other people.

One more note: this crash happens once in several days.
Rare enough to make bug chasing harder, but frequent enough to be inconvenient.

> I think this should be fixed in develop (as of https://github.com/yggdrasil-network/yggdrasil-go/commit/6677d70648b076d25a8db0dfe5fe886e7ae3190e).

Please trigger builds by GitHub Actions, so people who don't know how to build code also can test these changes.
I made binary myself and started to test it, but I'm not sure if my build 100% correct.

**Comment by Vort** [comment]
No crashes with `0.5.2-2-gb759683` for 6 days.
Looks like problem is solved.
Thank you.
