### ISSUE TITLE
Yggdrasil on OpenWrt

### ISSUE THREAD

**Issue by Monoloshka** [yggdrasil-network/yggdrasil-go#1103]
![image](https://github.com/yggdrasil-network/yggdrasil-go/assets/140126129/e0709d43-5623-48cd-bb9d-daf8c0641498)

**Comment by neilalexander** [comment]
This issue contains no useful information whatsoever and is totally un-actionable in this state. Which Yggdrasil version? How did you install it? What other configuration steps did you take?

**Comment by Monoloshka** [comment]
![image](https://github.com/yggdrasil-network/yggdrasil-go/assets/140126129/31fc2500-07e1-4ab3-ad40-8c73b02707c5)
https://yggdrasil-network.github.io/installation-linux-openwrt.html

**Comment by wfleurant** [comment]
you will need to open the firewall.
before you open the firewall (INPUT to Device) please set a password.
it should looks something like this

![image](https://github.com/yggdrasil-network/yggdrasil-go/assets/5460439/49112964-8e01-4070-9446-004c38357f91)

**Comment by Monoloshka** [comment]
![image](https://github.com/yggdrasil-network/yggdrasil-go/assets/140126129/bd68988e-ddc1-4d41-988c-4f217076d2e3)
Should I enable Allow-ICMPv6-yggdrasil, Allow-SSH-yggdrasil, Allow-HTTP-yggdrasil, Allow-HTTPS-yggdrasil that appeared after Yggdrasil installation? Maybe that's what you meant?

**Comment by Monoloshka** [comment]
![image](https://github.com/yggdrasil-network/yggdrasil-go/assets/140126129/be505551-5cb1-4f02-9456-7cde6d7eacc1)
Yggdrasil appeared here too, but the mesquerading item is unchecked by default. In the last 2 pictures I tried ticking all these items and then rebooted OpenWrt, but they didn't do anything

**Comment by vpzomtrrfrt** [comment]
make sure the node you're trying to connect to has the same version, 0.4 can't connect to 0.5 or vice versa

**Comment by wfleurant** [comment]
you wont need masq, you will need to configure and distribute the yggdrasil ip6 inner-network 300::xxx to the network. in a week or so 0.5 will be in yggdrasil-openwrt.

**Comment by Monoloshka** [comment]
Can't get into the sites anyway. Here's the logs: `Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Stopping multicast module
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Network device 'ygg0' link is down
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Interface 'yggdrasil' has link connectivity loss
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Interface 'yggdrasil' is now down
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Interface 'yggdrasil' is disabled
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Error reading TUN: read /dev/net/tun: file already closed
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Stopping...
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Exiting tun writer due to core read error: closed
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Disconnected TLS: 200:acbf:73b4:ce25:afd8:19bd:b011:491d@185.130.44.194, source 192.168.1.3; error: read tcp 192.168.1.3:58976->185.130.44.194:7040: use of closed network connection
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Failed to accept connection: accept tcp [fe80::52eb:f6ff:fe87:6578%wlan0]:41067: use of closed network connection
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Stopping TLS listener on: [fe80::52eb:f6ff:fe87:6578%wlan0]:41067
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Failed to accept connection: accept tcp [fe80::52eb:f6ff:fe87:6578%wan]:39757: use of closed network connection
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Stopping TLS listener on: [fe80::52eb:f6ff:fe87:6578%wan]:39757
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Failed to accept connection: accept tcp [fe80::52eb:f6ff:fe87:6578%br-lan]:41089: use of closed network connection
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Stopping TLS listener on: [fe80::52eb:f6ff:fe87:6578%br-lan]:41089
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Failed to accept connection: accept tcp [fe80::52eb:f6ff:fe87:6578%eth0]:42303: use of closed network connection
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Stopping TLS listener on: [fe80::52eb:f6ff:fe87:6578%eth0]:42303
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[2852]: 2023/11/16 12:05:04 Stopped
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Build name: yggdrasil-openwrt
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Build version: 0.4.3
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Starting up...
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Startup complete
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Starting multicast module
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 UNIX admin socket listening on /var/run/yggdrasil.sock
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Interface name: ygg0
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Interface 'yggdrasil' is enabled
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Network device 'ygg0' link is up
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Interface 'yggdrasil' has link connectivity
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Interface 'yggdrasil' is setting up now
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Interface IPv6: 201:e50e:3148:e919:60e9:b7b6:a4a6:1834/7
Thu Nov 16 17:05:04 2023 daemon.notice netifd: Interface 'yggdrasil' is now up
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Interface MTU: 53049
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Your public key is 46bc73adc5b9a7c5921256d679f2fbd9c91a9edd92123d9f204d290db89dc971
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Your IPv6 address is 201:e50e:3148:e919:60e9:b7b6:a4a6:1834
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Your IPv6 subnet is 301:e50e:3148:e919::/64
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Listening for TLS on: [fe80::52eb:f6ff:fe87:6578%br-lan]:34757
Thu Nov 16 17:05:04 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:04 Listening for TLS on: [fe80::52eb:f6ff:fe87:6578%wlan0]:36037
Thu Nov 16 17:05:05 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:05 Listening for TLS on: [fe80::52eb:f6ff:fe87:6578%eth0]:43173
Thu Nov 16 17:05:05 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:05 Listening for TLS on: [fe80::52eb:f6ff:fe87:6578%wan]:35071
Thu Nov 16 17:05:05 2023 daemon.info yggdrasil[4164]: 2023/11/16 12:05:05 Connected TLS: 200:acbf:73b4:ce25:afd8:19bd:b011:491d@185.130.44.194, source 192.168.1.3
Thu Nov 16 17:05:05 2023 user.notice firewall: Reloading firewall due to ifup of yggdrasil (ygg0)`
