### ISSUE TITLE
panic: this should never happen

### ISSUE THREAD

**Issue by temtemy** [yggdrasil-network/yggdrasil-go#1110]
Been getting this crash after I upgraded to 0.5.3. Seems related to #1100 but weirdly I never got that crash in 0.5.2.

```
panic: this should never happen

goroutine 83733 [running]:
github.com/Arceliar/ironwood/network.(*bloom).encode(0xc000014c48, {0xc000571000, 0x3, 0x40be})
        /home/mima/go/pkg/mod/github.com/!arceliar/ironwood@v0.0.0-20231126105342-ad38416a77c8/network/bloomfilter.go:78 +0x345
github.com/Arceliar/ironwood/network.wireEncode({0xc000571000?, 0xc000025098?, 0x61f0b1e857313?}, 0x0?, {0x9a5770?, 0xc000014c48?})
        /home/mima/go/pkg/mod/github.com/!arceliar/ironwood@v0.0.0-20231126105342-ad38416a77c8/network/wire.go:65 +0x75
github.com/Arceliar/ironwood/network.(*peerWriter).sendPacket.func1()
        /home/mima/go/pkg/mod/github.com/!arceliar/ironwood@v0.0.0-20231126105342-ad38416a77c8/network/peers.go:207 +0x1bc
github.com/Arceliar/phony.(*Inbox).run(0xc0000c0c18)
        /home/mima/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20220903101357-530938a4b13d/actor.go:98 +0x33
created by github.com/Arceliar/phony.(*Inbox).restart
        /home/mima/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20220903101357-530938a4b13d/actor.go:132 +0x56
```

**Comment by iczelion** [comment]
![2023-11-27_141118](https://github.com/yggdrasil-network/yggdrasil-go/assets/139316971/0a2847a3-a31f-4d5d-aa07-c455873f3ecb)

**Comment by neilalexander** [comment]
Downgrading probably won't help, as this is code that hasn't changed since v0.5.0.

I've uploaded `yggdrasil-develop` version `0.5.3-1-g741f825` to my S3 Debian repo, please test if you can & let me know if it helps.

**Comment by Vort** [comment]
No crash for 1.5 hours with `0.5.3-1-g741f825`.
Also frequent reconnects stopped, approximately 1 hour ago.

**Comment by temtemy** [comment]
No crashes as well for 10+ hours after upgrading to 0.5.4. Closing

**Comment by temtemy** [comment]
Resolving commits are [465b82d (Arceliar/ironwood)](/Arceliar/ironwood/commit/465b82dfb5bd6702837c1ff1eb20cb91fc56893c) and 741f825b8ed3e78664997f49c786dd51fa6a3805 for future reference
