### ISSUE TITLE
Yggdrasil sites are not opening. OpenWrt

### ISSUE THREAD

**Issue by Monoloshka** [yggdrasil-network/yggdrasil-go#1114]
Video: https://github.com/Monoloshka/Test2/
I would like to get rid of the need to specify the default gateway in Windows. Take into account that IPv6-PD value changes after OpenWrt reboot.
(I have no professional knowledge of IT.)

**Comment by wfleurant** [comment]
https://yggdrasil-openwrt.github.io/openwrt-config-basic.html

please see step 13: Enable Yggdrasil prefix to your local network

Try to enable this in LAN network

![image](https://github.com/yggdrasil-network/yggdrasil-go/assets/5460439/09789a53-a9b4-40c7-bfa0-b3ac2956d355)

**Comment by Monoloshka** [comment]
> https://yggdrasil-openwrt.github.io/openwrt-config-basic.html
> 
> см. шаг 13. Включите префикс Yggdrasil в вашей локальной сети.
> 
> Попробуйте включить это в сети LAN.
> 
> ![изображение](https://private-user-images.githubusercontent.com/5460439/290453514-09789a53-a9b4-40c7-bfa0-b3ac2956d355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTI3ODQsIm5iZiI6MTcwMjU1MjQ4NCwicGF0aCI6Ii81NDYwNDM5LzI5MDQ1MzUxNC0wOTc4OWE1My1hOWI0LTQwYzctYmZhMC1iM2FjMjk1NmQzNTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTExNDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEzNjU0YWE3MzI5ZGE5MTUzYjk1MGQzNjVlNDliM2I0YzU1M2UwOGNkNzZlMDkxOTVjNWUxMDBjZTllYTRmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XAwo3iP0ocFW5k5VaDzDGDHqPOPEnV-xrdCdlKfj1tA)

**Comment by Monoloshka** [comment]
Problem solved

**Comment by Monoloshka** [comment]
It doesn't work on Android.

**Comment by neilalexander** [comment]
"It doesn't work" is not the way to report problems — no one can help you with so little information.

At the least, please explain your current configuration, information about your devices, what you have tried and how you are verifying the results.

Have you verified that your devices are even picking up an IPv6 address from your router?

**Comment by Monoloshka** [comment]
https://github.com/Monoloshka/Test2/tree/main/mobile
Showing the settings: https://github.com/Monoloshka/Test2/tree/main/openwrt
-------------------------------------------------------------------------------------
Then I plan to use Tor bridges from the Yggdrasil network so that I can run a transparent Tor proxy on ipv6 and through the firewall I plan to forward to this transparent proxy. I am afraid that Yggdrasil connections will go to Tor instead of to Yggdrasil. I want to do this because my internet provider does not provide access to ipv6
