### ISSUE TITLE
-autoconf require access to admin socket and tun interface

### ISSUE THREAD

**Issue by ufm** [yggdrasil-network/yggdrasil-go#1122]
```
./yggdrasil -autoconf
2024/01/14 04:06:23 Build name: yggdrasil-develop
2024/01/14 04:06:23 Build version: 0.5.4-4-g768278a
2024/01/14 04:06:23 Your public key is f0558ff957e6785c0fc6b4eb8a19a72b021a0f05f65d4996029393afb859860d
2024/01/14 04:06:23 Your IPv6 address is 200:1f54:e00d:5033:f47:e072:9628:ebcc
2024/01/14 04:06:23 Your IPv6 subnet is 300:1f54:e00d:5033::/64
2024/01/14 04:06:23 Admin socket failed to listen: listen unix /var/run/yggdrasil.sock: bind: permission denied
```

1. Not always these nodes require access to the admin socket.
2. In this mode, it is impossible to start a node without a tun interface. But I would like to.

Therefore, I have two requests, if I may:
    Add the key '-noadminsock.'
    Add the key '-notun.'

**Comment by basilgello** [comment]
I encountered this with yggstack, so I ended up with https://github.com/yggdrasil-network/yggstack/commit/ad93f2c1c76cb443ee7dd80caa68fe81b5b3ef13

So if you dont need TUN or admin socket, you use `yggstack` instead.

**Comment by neilalexander** [comment]
A more concise way to do this is to create a partial configuration file and then use `-useconffile` at startup instead of `-autoconf`. Yggdrasil will automatically fill in the blanks so if you don't specify a `PrivateKey` then it will generate one at startup.

For example:
```
{
  AdminListen: none
  IfName: none
}
```

Similarly you can add `Peers`, `NodeInfo` etc.

**Comment by ufm** [comment]
Hmm. I didn't know about "partial configuration".
