### ISSUE TITLE
Doesn't work on openwrt router with mips (big endian) cpu

### ISSUE THREAD

**Issue by Sarevalak** [yggdrasil-network/yggdrasil-go#1133]
When running on big endian architecture yggdrasil-go can't route packets because of bug in https://github.com/bits-and-blooms/bloom/issues/99

**Comment by neilalexander** [comment]
Confirmed both the bug and the proposed fix in the bloom library and have PR'd your suggestion to them.

This is excellent investigatory work, thanks! We will get a release out to include this fix shortly.

**Comment by neilalexander** [comment]
This will be fixed in Yggdrasil v0.5.6 which will be hopefully released this week.
