### ISSUE TITLE
Yggdrasil 0.5.7 Crash on windows

### ISSUE THREAD

**Issue by AlexFreeman13** [yggdrasil-network/yggdrasil-go#1156]
Windows 10 22h2 19045.4717

C:\WINDOWS\system32>yggdrasil -autoconf
2024/08/05 22:13:10 Build name: yggdrasil
2024/08/05 22:13:11 Build version: 0.5.7
2024/08/05 22:13:11 Your public key is 8a91aaa9703c2f8cc4c60047ceac9974cd7c75475083b594bb3d01ccd63e5967
2024/08/05 22:13:11 Your IPv6 address is 200:eadc:aaad:1f87:a0e6:7673:ff70:62a6
2024/08/05 22:13:11 Your IPv6 subnet is 300:eadc:aaad:1f87::/64
2024/08/05 22:13:11 TCP admin socket listening on 127.0.0.1:9001
2024/08/05 22:13:11 TLS listener started on [fe80::bcd6:c8d5:8390:95ab%vEthernet (Ethernet 2)]:57324
2024/08/05 22:13:11 TLS listener started on [fe80::2a24:aff5:2bc3:b2c6%Lan]:57333
2024/08/05 22:13:11 TLS listener started on [fe80::b080:c439:c5c4:1d4c%vEthernet (Lan)]:57326
2024/08/05 22:13:11 TLS listener started on [fe80::1c20:7289:1d91:898c%vEthernet (Ethernet 3)]:57328
2024/08/05 22:13:11 TLS listener started on [fe80::ebbd:4096:826d:2618%vEthernet (outline-tap0)]:57329
2024/08/05 22:13:11 TLS listener started on [fe80::9496:a9a6:45a8:4d16%Ethernet 2]:57332
2024/08/05 22:13:11 Using existing driver 0.14
2024/08/05 22:13:11 Creating adapter
2024/08/05 22:13:26 Timed out waiting for device query: Время ожидания операции истекло. (Code 0x00000102)
2024/08/05 22:13:26 Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): Невозможно создать файл, так как он уже существует. (Code 0x000000B7)
panic: Error creating interface: Cannot create a file when that file already exists.

goroutine 1 [running]:
main.main()
        D:/a/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:268 +0x22e7

**Comment by peigongdsd** [comment]
Remove the existing dangling Yggdrasil tun interface, or reboot your computer. Then try if it's fixed.

**Comment by AlexFreeman13** [comment]
> Remove the existing dangling Yggdrasil tun interface, or reboot your computer. Then try if it's fixed.

It's don't work for me.

**Comment by EugeneMartein** [comment]
C:\Program Files\Yggdrasil>yggdrasil -autoconf
2024/08/06 08:34:37 Build name: yggdrasil
2024/08/06 08:34:37 Build version: 0.5.7
2024/08/06 08:34:37 Your public key is 04d15f8bf68d50b5d0d4f532b89b419d6b5c18f137357f58ef7dd6cc1347fe45
2024/08/06 08:34:37 Your IPv6 address is 205:cba8:1d02:5cab:d28b:cac2:b351:d92f
2024/08/06 08:34:37 Your IPv6 subnet is 305:cba8:1d02:5cab::/64
2024/08/06 08:34:37 TCP admin socket listening on 127.0.0.1:9001
2024/08/06 08:34:37 TLS listener started on [fe80::cfb7:d2ea:822c:4fe%Ethernet 2]:33306
2024/08/06 08:34:37 TLS listener started on [fe80::6eba:61cf:4f1b:ba22%Ethernet]:33307
2024/08/06 08:34:37 Connected inbound: 200:a9aa:95ca:54f3:41db:8848:f045:8f2b@[fe80::9c4f:d6f0:da8a:9388%Ether:61cf:4f1b:ba22%Ethernet]:33307
2024/08/06 08:34:37 Using existing driver 0.14
2024/08/06 08:34:37 Creating adapter
panic: TUN did not come up in time

goroutine 1 [running]:
main.main()
        D:/a/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:268 +0x22e7

**Comment by lespromtehkms** [comment]
I'm experiencing the same issues with Yggdrasil 0.5.7 as the other users have reported. It starts up, runs for a few seconds (anywhere from 1 to 15 seconds), I can even ping peers, but then the service crashes.
(Windows 10 22h2)

**Comment by Revertron** [comment]
Here, I've made a PR yesterday:
https://github.com/yggdrasil-network/yggdrasil-go/pull/1157

**Comment by neilalexander** [comment]
It looks like there are two separate issues here BTW, `TUN did not come up in time` vs `Cannot create a file when that file already exists`.

**Comment by Revertron** [comment]
Yep, and both are fixed in that PR.

**Comment by temtemy** [comment]
Also encountering this issue in FreeBSD:

```
2024/08/06 12:42:42 Build name: yggdrasil
2024/08/06 12:42:42 Build version: 0.5.7
[...]
panic: TUN did not come up in time

goroutine 1 [running]:
main.main()
        /home/<redacted>/yggdrasil-go/cmd/yggdrasil/main.go:268 +0x2334
```

**Comment by neilalexander** [comment]
Windows users, please try the following build to see if this issue is fixed:

* [x86-64/amd64](https://github.com/yggdrasil-network/yggdrasil-go/actions/runs/10341622525/artifacts/1799469460)
* [arm64](https://github.com/yggdrasil-network/yggdrasil-go/actions/runs/10341622525/artifacts/1799469506)

**Comment by neilalexander** [comment]
Windows users, please try the following build to see if this issue is fixed:

* [x86-64/amd64](https://github.com/yggdrasil-network/yggdrasil-go/actions/runs/10341622525/artifacts/1799469460)
* [arm64](https://github.com/yggdrasil-network/yggdrasil-go/actions/runs/10341622525/artifacts/1799469506)

**Comment by EugeneMartein** [comment]
> Windows users, please try the following build to see if this issue is fixed:
> 
>     * [x86-64/amd64](https://github.com/yggdrasil-network/yggdrasil-go/actions/runs/10341622525/artifacts/1799469460)
> 
>     * [arm64](https://github.com/yggdrasil-network/yggdrasil-go/actions/runs/10341622525/artifacts/1799469506)
> 
> 
> (I also posted these to the Yggdrasil Matrix room if these links don't work.)

Works fine for me. Windows 11 23H2 Build 22631.3880

**Comment by EugeneMartein** [comment]
Is this a solution to [this](https://github.com/yggdrasil-network/yggdrasil-android/issues/59) issue?
