### ISSUE TITLE
Real IP forwarding for WSS?

### ISSUE THREAD

**Issue by WGOS** [yggdrasil-network/yggdrasil-go#1159]
Greetings. Is it possible for `yggdrasilctl getPeeers` command to show real IPs of the nodes connected via `wss://` through a reverse proxy like nginx/caddy?

**Comment by neilalexander** [comment]
I don't believe the WebSocket library we use exposes this information, so that would need to be fixed upstream first.

**Comment by WGOS** [comment]
Thanks got it
