### ISSUE TITLE
support listening on FDs passed by the service manager (systemd socket activation)

### ISSUE THREAD

**Issue by flokli** [yggdrasil-network/yggdrasil-go#1169]
With systemd, It's possible to have the service manager take care of binding to certain listen addresses / socket types, and pass down the FD(s) to the process that's executed, either automatically, or lazily on the first connection, which simplifies some startup scenarios.

The more interesting part is that it allows further sandboxing / isolating the process, by not giving it privileges to do binding on its own. For example, you can have the service manager take care of binding on a port / creating a unix domain socket, and have the process just use the passed-down FD.

https://github.com/coreos/go-systemd/blob/main/activation/listeners.go provides a pure go implementation for it, and https://vincent.bernat.ch/en/blog/2018-systemd-golang-socket-activation#addendum-identifying-sockets-by-name provides some code examples.

It'd be great if yggdrasil-go could add a (linux-only) syntax allowing to specify a socket-activated listener, probably supporting listener names too.

**Comment by neilalexander** [comment]
Thanks for raising this but I don't think it makes sense to implement this within Yggdrasil. It's more complexity and more configuration behaviour to have to understand/explain/document for marginal gain.
