### ISSUE TITLE
Windows installer issue [fixed, forgot to click show all assets]

### ISSUE THREAD

**Issue by siryeetey** [yggdrasil-network/yggdrasil-go#1178]
when i tried to install the lates release, i got a message sayin "This installation package is not supported by this processor type. Contact your product vendor" I am on a dell latitude 3190 if that is the problem.

**Comment by neilalexander** [comment]
You probably downloaded the wrong package. There are 4 MSI packages, you need to pick the right one for your system:
1. `...x86.msi` for 32-bit Intel/AMD CPUs
2. `...x64.msi` for 64-bit Intel/AMD CPUs
3. `...arm.msi` for 32-bit ARM/Qualcomm CPUs
4. `...arm64.msi` for 64-bit ARM/Qualcomm CPUs
