### ISSUE TITLE
Packet loss when node coordinates change

### ISSUE THREAD

**Issue by IlyaMZP** [yggdrasil-network/yggdrasil-go#1179]
Is this expected behavior or did I misconfigure something?
The packet loss always stays above 1% even for directly connected nodes on the same local network. It seems to be correlated with node's coordinate changes.

https://github.com/user-attachments/assets/34a215eb-cd49-4455-b490-d777877c1018

**Comment by neilalexander** [comment]
When the remote node coordinates change, the old coordinates are invalidated and a new search for the remote key to discover the new coordinates has to be performed. In that time it's possible for traffic to be lost until we learn the new coordinates.

**Comment by IlyaMZP** [comment]
Looks like it has already been mentioned in this issue: https://github.com/yggdrasil-network/yggdrasil-go/issues/353
Which I missed, somehow.
