### ISSUE TITLE
Configuration file encoding issues on Windows

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#119]
This problem has been especially apparent on the latest version of Windows 10.

If you run `yggdrasil.exe -genconf > Yggdrasil.conf` from a Command Prompt, the file is written and can be read by `yggdrasil.exe -useconffile` and `yggdrasil.exe -useconf`. 

If you follow the same steps in PowerShell instead of Command Prompt, the encoding of the file is different (Unicode-perhaps?) and then Yggdrasil can no longer interpret it. (At a closer look, it seems that Yggdrasil reads every other byte of the file as `0x00`, which trips up `hjson`).

Also if you edit the `yggdrasil.conf` file in Notepad and then save, once again, the encoding is transformed and Yggdrasil can no longer make sense of it (same symptoms as with PowerShell).

**Comment by Arceliar** [comment]
Maybe Windows is using UTF-16 and Go expects UTF-8? In which case, we maybe need to pass the config through something to clean it up before trying to parse it.

It could hypothetically also be an issue with Unix vs Windows line-ends, but the half-the-bytes-are-zero thing sounds a lot more like a UTF-16 thing to me.

**Comment by neilalexander** [comment]
It does look a lot like it yes. Not yet sure if Go has an elegant solution to this.

**Comment by Arceliar** [comment]
Should have been fixed by #129 (we can reopen if the bug reappears).
