### ISSUE TITLE
IPv6 config changed in network interface, but not in Yggdrasil daemon

### ISSUE THREAD

**Issue by lcharles123** [yggdrasil-network/yggdrasil-go#1195]
I have one physical wired interface with IPv4 and IPv6, one from an ISP and the other of another ISP. It is the easy way of configuring a multi-homed connection. 

The IPv6 become unreachable because of ISP router issues. After placing a third ISP for testing and do a interface restart on the computer, the network changed the IPv6 on interface though auto-configuration,  but `yggdrasil getpeers` continued to show the error "network is unreachable" only in IPv6 peers. 

I think the daemon doesn't detected IPv6 address and gateway changes, i changed both. If change only suffix of IPv6, it works fine. All worked after restarting yggdrasil, but it will be better if not needed to restart. Changing ISP occurs when you have a portable computer and connect in other networks time to time.

Not sure if IPv4 have same behavior.

**Comment by neilalexander** [comment]
Yggdrasil doesn't care about the IP configuration or gateway of an interface and doesn't make any effort to track that (except for multicast interfaces and link-local addresses). It just initiates a socket dial and the OS returns an error if it fails.

Depending on how long the connection was down, it's likely that Yggdrasil had backed off retrying, so it would have come back up eventually, but restarting the node reset the backoff and forced it to happen faster. 

If you want to cap the backoff so it retries more often, you can add a `maxbackoff` to the peer URI, see https://yggdrasil-network.github.io/configurationref.html.

**Comment by lcharles123** [comment]
Thank you! It resolved the issue.
