### ISSUE TITLE
wss:// peering now requires TLS1.3 and has no default port

### ISSUE THREAD

**Issue by hatkidchan** [yggdrasil-network/yggdrasil-go#1208]
Can't add wss:// peers anymore, it needs a port, otherwise peering fails with `missing port in address`. With port added, fails with `failed to WebSocket dial: failed to send handshake request: Get "https://[redacted]:443/ygg/": remote error: tls: protocol version not supported`. Everything works on 0.5.9.
I didn't test ws:// peering, but my guess would be that it's also broken in a similar way.

Possible commit that caused the problem: https://github.com/yggdrasil-network/yggdrasil-go/commit/42873be09b5912cfbff0053fa94a1cb03112e0cf

**Comment by hatkidchan** [comment]
Peering via ws:// seems to work fine. I didn't have a second machine w/ 0.5.10 on it, so I just started another one on the same machine and tried peering with localhost, which seems to work. Either it's not enough to test it and peering via ws:// is also broken, OR only wss:// is broken.

**Comment by hatkidchan** [comment]
Peering with another instance of Yggdrasil running on the same machine via wss:// does seem to work(??) with port added, which is even weirder.

**Comment by hatkidchan** [comment]
Okay, with a bit of digging there's two separate issues:
- No default port for `wss://` peers (not a big issue)
- Something something possibly related to tlsconfig

**Comment by hatkidchan** [comment]
Found the culprit: minimum TLS version now is 1.3 but our domain was using TLS1.2. Previously it was fine, but I guess now requirements are stricter?

**Comment by hatkidchan** [comment]
This https://github.com/yggdrasil-network/yggdrasil-go/commit/7afa23be4c9850cc0d8a3fa5cf2cfd3b554a40e2 commit changed minimum version to be tls1.3 but back then it wasn't applied to wss, which was introduced in commit mentioned previously. Could we bump down minimum TLS version to 1.2 at least?

**Comment by basilgello** [comment]
1.2 is still widely used and standardized. Is there a specific reason to stick with 1.3 only @neilalexander ?

**Comment by basilgello** [comment]
Definition of default ports should be easy as it is 80 for HTTP/WS and 443 for HTTPS/WSS.
