### ISSUE TITLE
Latest release 0.5.12 is broken

### ISSUE THREAD

**Issue by schooldanlp6** [yggdrasil-network/yggdrasil-go#1221]
## How to reproduce
A minimally tweaked debian 12 install (minimal beeing the fact that I needed to install intel core ultra drivers) and the latest release. Installing will give some weird permission error and the thing just constantly crashes

## Current fix
Downgraded back to 0.5.9 it works

## OS
OS: Debian 12
Details: Framework 13 / Intel Core Ultra 5 / 32GB ram / 512GB SSD
More Details: no unnecessary packages installed

**Comment by mittwerk** [comment]
can you provide more details about what you did and describe the error in more detail? I also have debian 12 and everything works fine.

**Comment by schooldanlp6** [comment]
I really have to say I don't know what I changed 0.5.12 works after completly wiping it... sorry to bother you
