### ISSUE TITLE
sha256 checksum wrong

### ISSUE THREAD

**Issue by googl** [yggdrasil-network/yggdrasil-go#179]
After following the instructions for  [install from internet repository](https://yggdrasil-network.github.io/platform-linux.html#from-an-internet-repository-1), package download fails with checksum match error.
![package manager failure message](https://matrix.org/_matrix/media/r0/download/matrix.org/GIFxPMnLlxNYPmUuXiZOwSbp)

**Comment by neilalexander** [comment]
I've rebuilt the RPM repository - can you give it a try now?

**Comment by googl** [comment]
Great! It works. Thanks. One should `#dnf clean packages` first.
