### ISSUE TITLE
Able to read traffic using wireshark / Am I doing something wrong? 

### ISSUE THREAD

**Issue by bn4t** [yggdrasil-network/yggdrasil-go#196]
I recently wanted to see if traffic sent over yggdrasil is actually encrypted. 
To do this I pointed wireshark at the the `tun0` interface. 
To my surprise I the traffic which was sent over yggdrasil appeared to be unencrypted. 

Am I missing something/doing something wrong?

**Comment by neilalexander** [comment]
Yes - that is correct. Traffic is encrypted *after* it enters the `tun0` interface and is received by the Yggdrasil process. `tcpdump` intercepts the traffic *before* it reaches the Yggdrasil process, hence why you don't see it encrypted.

If you want to see the traffic encrypted, you should instead point your `tcpdump` to the peering connection itself, i.e. if you peer via `eth0` to `1.2.3.4` on TCP port `54321`, then you should tell `tcpdump` to show you that instead. You will see the connection encrypted.

**Comment by bn4t** [comment]
Thanks for elaborating. Makes sense now.
