### ISSUE TITLE
TUN goroutine termination on close

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#248]
When calling `tun.close()`, the tun goroutine can be left running as it's currently not signalled that the TUN/TAP adapter is going away. This hasn't usually been a problem because the only time we generally call `tun.close()` is when the process is already exiting.

However, this signals another problem in that it may cause panics if the TUN/TAP adapter disappears for some other reason instead of trying to recover gracefully.

**Comment by Arceliar** [comment]
Should be fixed now, re-open if anyone manages to crash it this way again after #255
