### ISSUE TITLE
Ability for admin socket to persist changes with -useconffile

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#296]
Perhaps something like a `persist=true/false` option for writable admin socket tasks, which will update the config on the filesystem if we are using `-useconffile` and we have `rw` access to that file.

I don't think this behaviour should be default, but it may make the work of many GUI/status apps considerably simpler having it as an option.

**Comment by Saiv46** [comment]
Something is blocking this issue?

**Comment by neilalexander** [comment]
The main thing blocking this issue is that if we rewrite the configuration file, it will nuke all comments and formatting that have been added and replace them with the default. It will also turn JSON-formatted files back into HJSON which might not be desirable.
