### ISSUE TITLE
Windows does not have a way to uniquely identify a specific tap0901 adapter

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#30]
Right now, Water simply selects probably the first `tap0901` adapter that it finds in the registry. This may conflict with OpenVPN or other software using the `tap0901` driver at the same time.

The capability exists to generate more than one TAP adapter - we should investigate how to select a specific one, or to not conflict.

**Comment by Arceliar** [comment]
It looks like the windows platform-specific paramters in water have a `ComponentID` field that defaults to `tap0901`. If the tap driver allows you to set up a new interface with a custom component ID, then exposing the `ComponentID` option in the config may be sufficient to fix this.
