### ISSUE TITLE
Node-to-node outer encryption layer

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#300]
We currently have end-to-end encryption, but we don't use a separate layer of encryption for node-to-node connections. This means an eavesdropper can read metadata from packets and gain (limited) information about where the packet is going -- coords, session handles, etc.

We already have the machinery in place for node-to-node encryption, but the only thing we use it for is link protocol traffic (I.e. spanning tree messages). Any time we open a link protocol message, if the contents aren't a switch / spanning tree message, then we could easily pass it to the code that currently handles other packet types. However, I'd prefer to use TCP+TLS for connections, so things are less obviously Yggdrasil traffic. Or QUIC if we decide to add UDP support again in the future.

This is just a reminder to do *something* for node-to-node encryption during the v0.4 cycle. At the very least, we should throw together some toy TCP+TLS benchmarks to see how they compare to plain TCP with messages comparable in size to what Yggdrasil uses, just to get a rough idea of what it would cost us.

**Comment by neilalexander** [comment]
This may tie in somewhat with #343.

**Comment by neilalexander** [comment]
For now I am going to close this as optional outer-layer encryption is now available using `tls://` with v0.3.11.
