### ISSUE TITLE
Peering cease wire packet required

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#32]
In order to correctly terminate a peering through the admin API (i.e. to add a `removePeer` command), a new wire packet needs to be defined to safely shut down and remove a peering from both sides.

In theory in TCP mode the connection can just be closed, but this is not possible with UDP.

**Comment by Arceliar** [comment]
To elaborate on this:

UDP peers send a small key packet every once in a while (for each active connection). When receiving a key packet, if no connection is already set up, then a new connection is set up. If you close a UDP connection, then currently it will just restart another connection the next time the peer sends a key packet.

We probably want to do 2 things.
1) Notify the peer, so they can close their connection too and stop sending key packets.
2) Close the current connection, but don't remove the connection info right away, to keep a new connection to the same node from being opened. Remove it after some acceptable timeout has passed, which should be at least a little longer than the usual node timeout (in case the remote end missed the disconnect message), or immediately if an addPeer is called.

**Comment by Arceliar** [comment]
Currently, UDP packets look like:
`[]byte{nChunks, nChunk, counter, msg...}`
where `nChunks` and `nChunk` are used to reassemble packets larger than the link MTU (or the maximum safe IPv4 UDP packet size), and `counter` is used to detect when a new packet begins.

Key packets look something like:
`[]byte{0, 0, 0, keys...}`

The main thing to note is that `nChunks >= 1` for all normal packets, so the `nChunks==0` case can be used to identify key packets.

I think it makes sense to extend this a bit. If byte 0 is == `0x00`, then we could identify that as a UDP control packet, with the second byte being the UDP control packet type. In which case, we could add something like a disconnect packet that looks something like `[]byte{0x00, 0x01, 0x00, keys...}` without breaking backwards compatibility with the current code, and then remove the extra (3rd) byte from key and disconnect packets at some later point (#42).
