### ISSUE TITLE
Auto-peer via DHT

### ISSUE THREAD

**Issue by iShift** [yggdrasil-network/yggdrasil-go#321]
Cjdns don't have DHT auto peer & auto discovery over public internet (not local LAN), how i understand yggdrasil also don't have that feature, why?

**Comment by iShift** [comment]
thanks for answer

**Comment by azazar** [comment]
I like Yggdrasil and find it quite useful. There is great idea behind it. And it's implementation is also seem much better that of CJDNS. It's too bad, that CJDNS developers decided to give up user experience and discarded autoconfiguration feature. For me public peers is the only way to join the network. Looking for peers manually, using forums and chats can and must be automated. There is a rule in software, saying that if it can be automated, it should be automated. Manual software configuration, even with graphical UI frightens away ordinary users, and wastes precious time of everyone, who wasn't frightened away. It's a bigger problem than it seems from a first glance.

DHT isn't the best choice for nearest node discovery. There is much simpler peer discovery algorithm. Each peer can store size constrained list of nearest known peers with lowest latency. All peers exchange peer lists and update their own after checking latency of peers in received lists.
