### ISSUE TITLE
WARNING: /var/run/yggdrasil.sock already exists and may be in use by another process

### ISSUE THREAD

**Issue by jmeeter** [yggdrasil-network/yggdrasil-go#326]
Using on OS X. Here's the output:

MBP:~ Jordan$ sudo yggdrasil -autoconf
Password:
2019/02/09 00:43:08 Build name: yggdrasil
2019/02/09 00:43:08 Build version: 0.3.2
2019/02/09 00:43:08 Starting up...
2019/02/09 00:43:08 Found 7 multicast interface(s)
2019/02/09 00:43:08 Starting switch
2019/02/09 00:43:08 Starting router
2019/02/09 00:43:08 Multicast discovery is enabled
2019/02/09 00:43:08 Listening for TCP on: [::]:65374
2019/02/09 00:43:08 WARNING: /var/run/yggdrasil.sock already exists and may be in use by another process
2019/02/09 00:43:08 Interface name: utun3
2019/02/09 00:43:08 Interface IPv6: xxxxxxx
2019/02/09 00:43:08 Interface MTU: 65535
2019/02/09 00:43:08 Admin socket failed to listen: listen unix /var/run/yggdrasil.sock: bind: address already in use
MBP:~ Jordan$ yggdrasilctl getPeers
2019/02/09 00:49:48 Found platform default config file /etc/yggdrasil.conf
2019/02/09 00:49:48 Using endpoint unix:///var/run/yggdrasil.sock from AdminListen
2019/02/09 00:49:48 Connecting to UNIX socket /var/run/yggdrasil.sock
2019/02/09 00:49:48 Fatal error: dial unix /var/run/yggdrasil.sock: connect: permission denied

**Comment by neilalexander** [comment]
Try to `sudo rm /var/run/yggdrasil.sock` and then rerun `yggdrasil` - the `yggdrasil.sock` doesn't get cleaned up if the process crashes for some reason.

**Comment by jmeeter** [comment]
Ok that seems to have worked, now I see

> Jordan$ sudo yggdrasil -autoconf
> 2019/02/09 12:42:19 Build name: yggdrasil
> 2019/02/09 12:42:19 Build version: 0.3.2
> 2019/02/09 12:42:19 Starting up...
> 2019/02/09 12:42:19 Found 7 multicast interface(s)
> 2019/02/09 12:42:19 Starting switch
> 2019/02/09 12:42:19 Starting router
> 2019/02/09 12:42:19 Multicast discovery is enabled
> 2019/02/09 12:42:19 Listening for TCP on: [::]:53003
> 2019/02/09 12:42:19 Interface name: utun3
> 2019/02/09 12:42:19 Interface IPv6: 201:d81b:de45:36f8:60c8:2738:f82f:8b7c/7
> 2019/02/09 12:42:19 Interface MTU: 65535
> 2019/02/09 12:42:19 UNIX admin socket listening on /var/run/yggdrasil.sock
> 2019/02/09 12:42:19 Startup complete
> 2019/02/09 12:42:19 Your IPv6 address is 201:d81b:de45:36f8:60c8:2738:f82f:8b7c
> 2019/02/09 12:42:19 Your IPv6 subnet is 301:d81b:de45:36f8::/64
> 2019/02/09 12:42:19 Connected: 201:5543:6eb4:d8b5:ebdc:11fa:2ad6:f7b9@fe80::1%lo0 source fe80::1%lo0
> 2019/02/09 12:42:21 Connected: 201:5543:6eb4:d8b5:ebdc:11fa:2ad6:f7b9@fe80::f1:eb58:cbfa:3b2e%en1 source fe80::f1:eb58:cbfa:3b2e%en1

Although I am not able to load any websites on the yggdrasil network. I am connected to peers:

> Jordan$ sudo yggdrasilctl getPeers
>                                         bytes_recvd  bytes_sent  endpoint                             port  uptime  
> 201:5543:6eb4:d8b5:ebdc:11fa:2ad6:f7b9  1041         1960        [fe80::f1:eb58:cbfa:3b2e%en1]:53007  2     00:01:40  
> 201:d81b:de45:36f8:60c8:2738:f82f:8b7c  2653         0           (self)                               0     00:01:42

**Comment by neilalexander** [comment]
I don't seem to be able to ping `201:5543:6eb4:d8b5:ebdc:11fa:2ad6:f7b9` or `201:d81b:de45:36f8:60c8:2738:f82f:8b7c` so I am wondering if either of these have got any peering configured that connect you to the rest of the network?

**Comment by neilalexander** [comment]
Closing this for now - let us know if you have any more similar problems.

**Comment by zabojeb** [comment]
just got the same issue and fixed it with `sudo rm /var/run/yggdrasil.sock`

it's still a problem but i don't know if it appears on any systems other than os x (tested version is os x 10.13)
