### ISSUE TITLE
Tell in logs when AllowedEncryptionPublicKeys blocks a connection attempt

### ISSUE THREAD

**Issue by Mikaela** [yggdrasil-network/yggdrasil-go#337]
Discussed at IRC/Matrix, where I and some others were surprised by AllowedEncryptionPublicKeys also affecting outgoing connections. However the error message is only shown when Yggdrasil is ran with specific flags instead of appearing in journalctl with default config.

**Comment by Arceliar** [comment]
It looks like we actually have this logged already, but at the debug level, so it doesn't display by default. Perhaps the info or maybe warn level would be more appropriate...

**Comment by Mikaela** [comment]
What are the log levels that get shown by default? I think warn would be appropiate as it's not "for your information" and it's not a direct error either.

**Comment by Arceliar** [comment]
Info, Warning, and Error are currently enabled by default (according to `yggdrasil -h`, too lazy to actually check the code...) so I think I'll switch it to warn as part of my #338 PR.

**Comment by neilalexander** [comment]
I don't think we ever fixed this, so I will add this to the v0.3.13 milestone so that it gets actioned.

**Comment by neilalexander** [comment]
This is already set as a `warn`-level error in v0.3.12.
