### ISSUE TITLE
Make AllowedEncryptionPublicKeys configurable for different scopes

### ISSUE THREAD

**Issue by jcgruenhage** [yggdrasil-network/yggdrasil-go#342]
Some people might want to allow incoming connections from their local network for everyone, but limit who can connect to them from the internet.

**Comment by neilalexander** [comment]
I am not entirely sure what configuration like this would look like, as we don't only have scopes to deal with (link-local, remote) but also protocols (TCP, potential future UDP/QUIC/...) – it might get rather complicated rather quickly. 

At the moment the `AllowedEncryptionPublicKeys` property only applies to peerings which *aren't* link-local, therefore a link-local multicast peering will always be allowed.

**Comment by jcgruenhage** [comment]
When I opened the issue, local peering wasn't always allowed, so the main reason for opening this issue has been resolved.

On the config side, you could put that into the definition of the listeners, so that for each listener, you can specify a list of encryption public keys that can connect to this specific listener, so there you can cover all the different protocols too. If you additionally put that next to each multicast interface, you get very fine grained control of who can connect where.

Putting a layer of indirection between all of this by defining key groups in another place and then putting the key group names into the listener/interface definition, you could additionally reduce duplication when multiple interfaces/listeners share the same config with regard to encryption keys.

**Comment by neilalexander** [comment]
We've added password support on a per-listener/per-peer/per-multicast interface scope for v0.5 so that will take place of this.
