### ISSUE TITLE
UNIX transport

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#346]
We already have `unix://` socket support for the admin socket. I'm not expecting it to be the most useful transport ever, but this one should be easy to add compared to almost anything else, so it seems like low hanging fruit. We could really just copy/paste the code from `tcp.go` or add a `unix://` case to that file (and maybe rename the file if we did that)... I'd kind of like to refactor `tcp.go` a bit anyway, to separate some of the `tcp://` and `socks://` logic a bit, since it's kind of ugly in some places right now.

**Comment by Mikaela** [comment]
Earlier discussion was at https://github.com/yggdrasil-network/yggdrasil-go/issues/153#issuecomment-403164527 where the only use case thought of was [Tor's Onion Services](https://torproject.org/docs/tor-onion-service.html.en) which can use UNIX sockets in addition to ports.

**Comment by cathugger** [comment]
It'd also be helpful with multiple nodes ran on the same machine (in separate network namespaces or containers).

**Comment by neilalexander** [comment]
v0.4 has UNIX socket support.
