### ISSUE TITLE
Log failures to connect when the remote blocks incoming requests with a firewall.

### ISSUE THREAD

**Issue by jcgruenhage** [yggdrasil-network/yggdrasil-go#352]

**Comment by neilalexander** [comment]
Are you meaning cases where the remote side resets the connection?

**Comment by jcgruenhage** [comment]
All packets were dropped, no connection reset. I guess it would be better to say that ygg should time out appropriately and log that timeout.

**Comment by neilalexander** [comment]
I expect that is already logged on the `debug` level - can you verify with `-logging error,warn,info,debug` options?

**Comment by jcgruenhage** [comment]
I did that when I had the issue, couldn't see anything in the logs about it.

**Comment by neilalexander** [comment]
Closing as outdated.
