### ISSUE TITLE
TCP/UDP Tunneling

### ISSUE THREAD

**Issue by evgivz** [yggdrasil-network/yggdrasil-go#354]
I haven't found a proper way to set up Docker web server container with yggdrasil connectivity. I'm new to Docker, but AFAIK they supposed to be in separate containers with optional ipv6 connectivity. That's just the one use case, where tunneling necessary. Another is when tun/tap device is not available to non-root users, who could benefit from something like ssh "dynamic tunneling" with socks proxies.

**Comment by neilalexander** [comment]
This is something we've talked about a few times and should be made simpler post-v0.3.6 with the new API functions for creating/accepting sessions. We'll track this for a future release.

**Comment by neilalexander** [comment]
We've experimented with netstack for non-TUN hosts but there are problems upstream that make it impractical, we don't plan to work around this in another way at this time.
