### ISSUE TITLE
Add Prometheus /metrics endpoint

### ISSUE THREAD

**Issue by yangm97** [yggdrasil-network/yggdrasil-go#367]
Since Yggdrasil already serves a restful API over http, this _shouldn't_ add much weight to binary size.

**Comment by keslerm** [comment]
I created a very simple external exporter here https://codeberg.org/rridley/prometheus-yggdrasil-exporter in the mean time

**Comment by neilalexander** [comment]
This is not planned at this time as it is already possible to extract relevant information out of the admin socket.
