### ISSUE TITLE
Yggdrasil as WASM module

### ISSUE THREAD

**Issue by iShift** [yggdrasil-network/yggdrasil-go#381]
I have one crazy idea, if you think that it crazy/useless - close it =)

As i see you plan to add support of WebSocket transport in https://github.com/yggdrasil-network/yggdrasil-go/issues/343 so, if you do that, i think, that next step - compile yggdrasil as web assembly module. _(thanks go language supports that)_

If we have WASM module we can launch it in browser page and make one-click overlay network.
_also - chrome support multicast https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/multicast_ 

So we can have zero-conf browser based network (like webtorrent bring torrent to web, wasm+yggdrasil can bring overlay network to web for the first time). 

As a next step, with WASM we can launch yggdrasil as chrome extension - it can help network to grow faster (even if extension can't proxy yggdrasil network and act only as switch without gate to network)

Short-run benefits:

1. One more way to distribute 
2. Super easy and fast network test with many users

Long-run benefits/goals:

1. Web pages that can request data through yggdrasil network (javascript api/lib)

**Comment by l-n-s** [comment]
Are you seriously talking about routing network packets in the web browser? :scream:

**Comment by iShift** [comment]
@l-n-s yep, i start my issue that it "crazy" =) but all great idea start as crazy))

**Comment by cathugger** [comment]
>Web pages that can request data through yggdrasil network (javascript api/lib)

b-but you'd need to have IPv6/TCP/UDP/whatever else networking stack for this to be useful too

**Comment by iShift** [comment]
@cathugger or proxy/tunnel API in yggdrasil

**Comment by azazar** [comment]
Chrome doesn't provide API for such extensions. You can't make extension to implement new network protocol, replace http/https or proxify http traffic.

**Comment by iShift** [comment]
@azazar but you can launch WASM module in background (on page or in extension) and ask it with API (if in background - background api). So you can get info from network, yes, it is not true way - because it is not mount as network adapter but it can work. 

Example:
Page A have WASM module and field with url to look inside network
When you type something in filed - it ask with js api wasm module, download page and insert it in DOM/iframe.

as a result - user can work with network just from browser. 
wasm module can have api to add peers - so user open link with public peer option and destination URL option, wasm start, connect to network, show page that user want. 

The main goal that we can reach - make easy bridge to network, as a next step - broadcast/multicast nearby peers

**Comment by iShift** [comment]
+ wasm module can build in browser such as Brave browser...

**Comment by KonoromiHimaries** [comment]
> next step, with WASM we can launch yggdrasil as chrome extension

https://github.com/embarklabs/embark#readme

**Comment by KonoromiHimaries** [comment]
https://github.com/cybercongress/cyberd/issues/471

**Comment by KonoromiHimaries** [comment]
https://github.com/cybercongress/cyb/issues/268

**Comment by Saiv46** [comment]
WebTorrent uses WebRTC for communicating with peers but needs a server to bootstrap, so WebYggdrasil will need "hubs" and/or "hybrid" peers to make that approach work (you don't even need a WebSocket transport, you can send raw datagrams between browsers).

**Comment by kotovalexarian** [comment]
That's a good idea to connect to public key addressable networks like Tor and Yggdrasil from browser. However, it might be easier to write a complete implementation of protocol in JavaScript than using WebAssembly because it's environment is too different and limited.

From https://github.com/Ayms/node-Tor#history:

> This project was started in 2012 when we contacted the Tor project team with some objectives to use the Tor network at that time from the browser, then Aaron Swartz to whom we dedicate this project just replied "I think the right solution is to implement all of Tor in JavaScript, so that the web browser can set up the necessary tunnels and it has all the security guarantees of the client. Obviously, of course, this is quite a programming challenge."

**Comment by neilalexander** [comment]
Closing as not planning to do anything here specifically at this time.
