### ISSUE TITLE
yggdrasilctl addPeer/removePeer persist

### ISSUE THREAD

**Issue by passenger245** [yggdrasil-network/yggdrasil-go#393]
feature request to persist added/removed peers to config

**Comment by neilalexander** [comment]
In cases where Yggdrasil is started with `-useconffile` this is possible, although the caveat is that the configuration would be normalised every time that a persistent change is written. That would destroy comments etc and overwrite them with the default ones.

If that's acceptable then I had thought that we might achieve this with a `persist=yes` option to `yggdrasilctl`. 

The alternative way that's just as easy is to update the configuration file by hand and then reload it at runtime with `killall -HUP yggdrasil`. New peers will be added within a minute of reloading the config and removed peers will remain connected until they drop but won't connect again.

**Comment by passenger245** [comment]
Reasons why i'd see it as valuable

- to handle I/o through yggdrasilctl to prevent race conditions between external tools
- keep track of user initiated peering. This would tackle #392 to know how many nodes are added and still connected

**Comment by cathugger** [comment]
Sounds like antifeature to me.
I definitely don't wanna allow yggdrasil overwriting its own config files and reformatting/removing comments there (unless I start it with option to allow that).
Maybe it could be acceptable if it was stored in some kind of separate database-like file, but I personally don't see why any tools touching peer list shouldn't hold their own lists, and ensure consistency upon control socket reconnection.
Maybe use cases I'm thinking of aren't complicated enough though.

**Comment by neilalexander** [comment]
I tend to prefer the approach where the user modifies the configuration file and then uses `SIGHUP` to reload it at runtime because then we aren’t doing anything destructive to the file, and we don’t need to do any writes.

**Comment by reddec** [comment]
Regardless of the implementation (separated DB or overwritten config - personally I will prefer one file per one peer), I would like to add some notes about the feature request:

## Case of a private network

A large private network system administrator probably will be very unhappy to set list of all public keys of peers as a list in configuration file for all nodes. Instead will be much more logical (from my point of view) add some "bootnode" that can provide network topology with required node identification data: IP, public key and so on. 

After node reboot, in case of persistent key/IP database, bootnodes are no more critical.

Actually, boot node it's a just normal node, defined in a peer list. Information distribution (peers discovery) is already implemented. All that needs to be done - to persist key/ip database between reboots.
## Faster boot-up

In case of the scenario of P2P connection, no doubts (in general situation), a closer peer to the destination peer, then the better connection will be (distances means number of piers between with the assumption that link's speed are similar). 

If a node can load already saved peer identification during boot time, IMHO establishing a new connection may take much less time.

**Comment by neilalexander** [comment]
I don't think at this stage we are comfortable with rewriting the contents of the configuration file, and in cases where `-useconf` is used instead of `-useconffile`, it is not possible anyway.

Going to close this for now but we may revisit this in the future if the anatomy of the node configuration changes.
