### ISSUE TITLE
how to remove this from mac

### ISSUE THREAD

**Issue by cinghialino** [yggdrasil-network/yggdrasil-go#404]
Hello, I do not have knowledge on how to remove this from my mac. I've installed it through the package.

**Comment by neilalexander** [comment]
Open up Terminal.app. You might be prompted for `Password:` when doing the below steps – just enter your user account password and hit Enter.

First unload the services:
```
sudo launchctl unload /Library/LaunchDaemons/yggdrasil.plist
```
... then delete the files installed by the package:
```
cd /
pkgutil --only-files --files io.github.yggdrasil-network.pkg | sudo xargs rm
```
... and finally forget the package:
```
sudo pkgutil --forget io.github.yggdrasil-network.pkg
```

**Comment by cinghialino** [comment]
Thank you for the quick and detailed response. I was able to succeed.
You might want to include this info in the Installation docs.

Thanks again.
