### ISSUE TITLE
Battle Mesh

### ISSUE THREAD

**Issue by zicmama** [yggdrasil-network/yggdrasil-go#415]
Is it correct to wonder why Yggdrasil is not part of Battle Mesh events?
https://www.battlemesh.org/BattleMeshV12

**Comment by zicmama** [comment]
If not, battlemesh@ml.ninux.org and v12@battlemesh.org are communication channels...

**Comment by Arceliar** [comment]
We've discussed this a bit in the matrix channel. While we'd like to be involved in battlemesh, the developers (@neilalexander and myself) don't expect that we'll be able to attend this year -- other things in our schedules. Perhaps next time.
