### ISSUE TITLE
Separate router and switch

### ISSUE THREAD

**Issue by jcgruenhage** [yggdrasil-network/yggdrasil-go#421]
Currently a node consists of a router and a switch, with the router connected to switch port 0. Ideally a switch wouldn't treat port 0 specially and the router would instead get it's own coordinates. There is some discussion about this [in the matrix room](https://matrix.to/#/!DwmKuvGvRKciqyFcxv:matrix.org/$1558274901176kUzpn:gruenhage.xyz?via=matrix.org&via=privacytools.io&via=tomesh.net). It looks like we need a breaking change in the protocol for this, so it's kinda related to #292.

**Comment by neilalexander** [comment]
In v0.4 the router and switch roles are merged somewhat, so closing.
