### ISSUE TITLE
Decide on appropriate format for admin socket

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#43]
Right now there is no strict formatting requirement on either inputs or outputs to/from the admin socket. This is not ideal for interfacing with the admin socket programmatically.

Investigate whether there is a more appropriate format to use - ideally one that remains as easy for a human to interact with/to understand as it is to be parsed by an external program:

1. JSON
1. MessagePack
1. XML
1. YAML

**Comment by Arceliar** [comment]
All else being equal, something line delimited would be nice, just so people can use line-based command line tools without much trouble. I would say [line-delimited json](https://en.wikipedia.org/wiki/JSON_streaming#Line-delimited_JSON) is my early favorite for a response format, as long as the fields of each object are sorted in some consistent order, to make piping it through standard command line tools (parsing with split/cut) a tedious but possible option. I'm not sure what I think about request formats. Being able to echo-pipe-nc is really convenient from a user and shell-scripting standpoint, and generating a request programmatically seems like it should be easier than parsing one, so I'm not opposed to keeping a space-delimited convention for now (where the first term is the name of some function, and the rest are arguments and/or flags of various sorts, in which case we should write better parsing code for this).

**Comment by Arceliar** [comment]
Whatever we decide for this, it should be guidelines and not strict rules. It wouldn't make much sense to change the format of the `dot` output, for example.

**Comment by neilalexander** [comment]
I've been trying to come up with a sensible solution for this, and honestly I'm drawing a blank. As I see it there are three problems here: the response format for `get`, the response format for `set` and the input format.

For `get` commands we could use JSON with the following caveats:
- We don't get much control over the order of keys returned or the formatting
- We will probably have to rewrite substantial chunks of the admin code to use maps
- We could use line-delimited JSON or we could wrap the entire JSON response into a single stanza

For `set` commands some more difficult questions open up:
- How should we return success or failure?
- Should we be returning the request along with the success/failure, or should we be returning the newly changed state? Do we need to do either?
- Should the success/failure and the state change be a part of the same JSON stanza/nested, or should they be separate line-delimited lines?
- Should the response of the `set` be consistent with the response of the `get`?

Then there's the input format, which right now is nice and easy to use with `echo`-pipe-`nc` but is particularly sensitive to parameter order and not aware of quotemarks etc. Aside from some small modifications to make it more robust, I think it is okay to keep this input format. It does mean that the input and the output format won't necessarily be the same, however.

So I arrive at the question: for the substantial complexity that a JSON interface would bring, would we actually be better using a line-by-line friendly delimited output format, like we do now, but with some stricter output and formatting rules to ensure that it can be easily parsed as well as understood by a human being?
