### ISSUE TITLE
Strip unnecessary logic from debug.go

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#435]
A lot of the contents of `debug.go` is no longer needed now that we expose a lot of info through `api.go`.

It seems that `debug.go` should really only be responsible for setting up channels between sim nodes and accessing non-exported info, e.g. forwarding data from the switch.

Even the profiler stuff could be moved out of `debug.go` and into a future `cmd/yggdrasilsim` (#434) for cleanliness.

**Comment by Arceliar** [comment]
Most of `debug.go` was cleaned up in #519 and anything it turns out we still need for the sim will be re-added later.
