### ISSUE TITLE
Possible bug in develop with long-lived sessions

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#439]
I have noticed that sessions are quite often dropped after a couple of hours (but seem to re-establish fine) in the latest `develop` builds. This doesn’t happen in the release v0.3.5 builds. 

I haven’t yet investigated further yet so I’m not sure if the problem is in the sessions or whether something is causing peerings to drop temporarily.

**Comment by Arceliar** [comment]
While working on #441 I noticed that some fields in the sessions weren't being updated properly to trigger keep-alive session pings. I'm didn't think about it much, but it wouldn't surprise me if it also prevented keep-alive searches from happening. If a node's coords changed and that caused traffic to drop, but the pings/searches never happened, then I think that would cause the `Conn` to just drop packets until it finally times out and gets `Close`d / re-`DIal`ed, so hopefully I accidentally fixed this (or it's at least something we can deliberately try to test for).

**Comment by neilalexander** [comment]
This does appear to be fixed with `0.3.5-140` so closing for now.
