### ISSUE TITLE
DHT allocates/sorts heavily

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#44]
Created in response to a `FIXME` in `dht.go`.

> DHT allocates a bunch, sorts, and keeps the part it likes. It would be better to only track the part it likes to begin with.

**Comment by Arceliar** [comment]
Implementation-wise: right now it fills a slice with everything in the DHT, sorts by keyspace distance, then truncates the slice to some size (2), and returns that slice. It should probably either use a linked list, or loop over the slice and do an insertion sort (appending to the end if needed, truncating or skipping the append if this makes the slice too long).

**Comment by neilalexander** [comment]
Is this still relevant with Chord?

**Comment by Arceliar** [comment]
The code that was formerly at fault for this no longer exists, but I think the current chord implementation *also* happens to allocate and sort more than it needs to. Probably not as much as kad did, but more than needed...

**Comment by neilalexander** [comment]
Closing as not relevant anymore in v0.4.
