### ISSUE TITLE
TAP mode doesn't work in develop branch on linux

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#442]
What the title says. If I'm running in tap mode and try to send packets somewhere, it doesn't seem to work. A comment in #441 notes one place where I think I see a bug, but I would have expected that bug to crash the code if it ever reached that point, so I genuinely have no idea where the issue is (I haven't looked at the code / tried to debug it yet).

**Comment by neilalexander** [comment]
This is now fixed by #455.
