### ISSUE TITLE
Slowdowns beginning in 0.3.6

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#448]
As part of the refactoring to make the code work as a library, we introduced structs that provide the `net.Conn` interface and updated the tun/tap code to use them. `Read`/`Write` with these is currently slower than on master. We need to investigate why that is and fix it.

Likely causes:
1. New session worker logic, perhaps there is some contention here or something. This could potentially be replaced with a mutex-based approach, we just need to be careful about how these are handled.
2. There are lots of places in `Read` and `Write` which allocate something, mostly timers for deadlines, while the old code avoided allocations in the hot paths. I'm pretty sure we can get rid of most or all of these, we just need to be careful to do it in a thread-safe way. There may also be more copies between `[]byte` than before (we should endeavor to keep that to a minimum, really only when it's necessary for thread safety or to conform to the `net.Conn` interface).
3. It's possible that the code on the tun/tap side, which needs to call functions of the new `Conn`s, is slower (for some reason) than the old code that passed everything to the router goroutine.

We need to profile things to figure out what's what.

**Comment by neilalexander** [comment]
Just a reminder to look into the reader goroutine > reader helper goroutine > `Conn` goroutine pattern as a part of v0.3.7.

**Comment by Arceliar** [comment]
So I think there's a few different things going on here that contribute to the problem.
1. `Conn.Read` and `Conn.Write` both need to access parts of the `sessionInfo` that are protected by a mutex, which puts them in contention with eachother. If I simply comment out the mutex, then things become unsafe, but almost half of the speed loss between 0.3.5 and now is recovered.
2. There are a few more places where packet can get dropped in the event of a bottleneck, instead of blocking until the next step of the chain is available. In general, I expect this means packets drop more often. For example, *after* decrypting a packet, we can drop it if the tun is too busy to write it out, when ideally we'd not drop it after we've wasted significant resources decrypting it already.
3. There's a little more allocation happening in the hot path, mostly related to `Cancellation` objects used to implement a timeout mechanism to conform to the `net.Conn` interface. This isn't as bad as the original `Timer`-based code, but there may be room for improvement.

It's worth mentioning that, with `GOMAXPROCS=1`, I actually see noticeably better performance with the new code than with the old. So, at least on my machine, we're getting more packets sent with the same amount of work, there's just more contention for resources for any one `Conn`. It wouldn't surprise me if total throughput to *multiple* nodes is higher than before, even if throughput to any one node is lower, but I haven't tested this yet.

**Comment by Arceliar** [comment]
Almost forgot, I've been thinking about what a better implementation of the current `session`/`Conn` code may look like.

1. Split up the `sessionInfo` into a few parts. We want a dedicated `send` and `recv` goroutine per session, and they should own the part of the session info that they need for their respective jobs. If the outside world needs to send them any info, then they should do it via message passing. That eliminates the mutexes and contention when accessing data, in exchange for marginally more complicated updates to data when e.g. a `ping` comes in.
2. `Conn.Write` should just check that a packet is writeable (e.g. fits under MTU) and then pass it to the `send` worker. If the worker is too busy, the channel should block until the worker is free.
3. `Conn.Read` should just pull packets out of a buffer of already-decrypted packets managed by the `recv` worker, and the `recv` worker should decrypt packets immediately when they come in (unless too many are buffered waiting for `Conn.Read`, then it should drop any more that come in until there's room--no point in wasting CPU if we're receiving them faster than we can handle them a the `Conn` level).
4. When `send` or `recv` workers handle packets, they should do so via a fixed sized worker pool with 1 worker per `runtime.GOMAXPROCS()` (to make sure we don't spawn crypto goroutines ad infinitum, which could lead to memory problems, but 1 per core seems reasonably constrained). The `send` and `recv` workers should do any required sanity checks (nonces etc) and then prepare a struct with any info the workers need, including a (buffered) channel through which they can send a `struct{[]byte, error}` or similar as output. Then the `send` or `recv` worker passes it to the queue for the crypto workers and waits for a response, but waiting happens in a select statement with waiting for any new work to submit, and we wait or output *in order* (e.g. a slice of outputs, always just listen for the first one while the slice is non-empty, as part of a select waiting for more packets to submit to the worker pool). This would allow all cores to be used for packets associated with a single session, but would prevent packets from being reordered unnecessarily by the scheduler. Note that all the temporary structs here can be reused to avoid allocations.

I think that should do a better job of getting packets to the next step of the chain as fast as possible, and spreading at least the crypto part of the CPU load across cores more evenly when only one session is a significant source of traffic. We should also be a bit more careful about exactly when we allow packets to drop if there's a bottleneck. For example, if we've gone to the trouble of decrypting a packet, then we should make sure we can safely just let things block until that makes it to the tun, rather than drop it after having spent CPU time on it.

**Comment by neilalexander** [comment]
This has been pretty much resolved by #480.
