### ISSUE TITLE
Appropriate build versioning

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#45]
Right now the CircleCI build pipeline numbers the build artifacts in the following format: `X.Y.ZZZZ`, where `X` is the major version number (right now 0), `Y` is the minor version number (right now 1) and `ZZZZ` is the build number, arbitrarily determined from the number of Git commits on that branch.

This was just enough to make the builds look distinct, but doesn't actually match [Semantic Versioning](https://semver.org) guidelines.

Breaking protocol changes should probably be identified in the minor version number, but in that case, to strictly meet the guidelines, the build number should count the number of builds since the last minor version and not overall like it does today. (Also would need to drop the leading zeroes!)

If including a version number in the wire format, like described in #42, should this be derived from the major and minor version number? 

More open-ended question: is Semantic Versioning the right approach for us, and how worried about this are we right now?

**Comment by Arceliar** [comment]
Thinking about this more, I like the idea of semver, but I don't think it needs to be a high priority that we exactly match the guidelines right now, as long as we don't reuse numbers or do things that would make it difficult to adopt that numbering scheme later.

Another option would be `X.Y.Z-C`, where `X.Y.Z` are as in semver and set by hand, and `C` is the commit number used in the CI for development builds. Then we can update the hard coded semver and tag, as needed, with the -C being omitted from "stable" builds. I'm not sure if it would make more sense to update the semver part immediately before a build (so `X.Y.Z-C` means `X.Y.Z` + commits up through `C`), or immediately after (so `X.Y.Z-C` means that it's work-in-progress towards what will eventually be `X.Y.Z`).

I don't think we need to come to a decision on this until the next time we want to do a breaking change (`0.2.something`).

I think we should keep the wire version numbers, if/when we add something, as a protocol version number, and the build numbers as an implementation version number, so I don't think they need to be related to eachother (except that any incompatible wire format changes will require the most significant nonzero semver number to increase).
