### ISSUE TITLE
Log file becomes overwritten every restart

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#450]
It should be good to have ability of looking into log information for previous runs of this software.
Right now log file is replaced every time program is started.
Also log contains no information about stopping of the Windows service.
And please tell why log path is specified via command line instead of config file.
Tested version: yggdrasil-develop-0.3.5-0140-windows-amd64.exe.

**Comment by neilalexander** [comment]
We don’t have the ability to track the Windows service—you would need to look into the Windows Event Viewer for that. We should be able to make the logs append though rather than recreate on each start. 

Right now the parameter is on the command line because otherwise there is no way to get output when using `-autoconf`, which doesn’t take config input.

**Comment by Vort** [comment]
> We don’t have the ability to track the Windows service—you would need to look into the Windows Event Viewer for that.

Process is just killed or what?
It should know that it is exiting.

**Comment by neilalexander** [comment]
We know when the service is gracefully stopped but we don't know if it's been killed for some reason (e.g. low resources) or if the service stopped because Yggdrasil crashed. 

There is a deferred function which is supposed to happen during a graceful exit but if that isn't being triggered then I can try and fix that.

**Comment by Vort** [comment]
Logging of graceful exit is a good start.

**Comment by neilalexander** [comment]
This is what I mean—we should be doing. If there's no `Stopping...` message then that's a bug.

**Comment by Vort** [comment]
This problem and #451 are specific to Windows service mode of operation.
When I run program in console, Ctrl+C yields Stopping... message.

**Comment by neilalexander** [comment]
Can you please try the build from https://circleci.com/gh/yggdrasil-network/yggdrasil-go/1131#artifacts/containers/0 and see if that solves the problem with stopping the Windows service?

64-bit: https://1131-115685026-gh.circle-artifacts.com/0/yggdrasil-stopfix-0.3.5-0141-windows-amd64.exe
32-bit: https://1131-115685026-gh.circle-artifacts.com/0/yggdrasil-stopfix-0.3.5-0141-windows-i386.exe

**Comment by Vort** [comment]
Still no "Stopping..." message.

**Comment by neilalexander** [comment]
How about https://circleci.com/gh/yggdrasil-network/yggdrasil-go/1135#artifacts/containers/0 - is that any better?

64-bit: https://1135-115685026-gh.circle-artifacts.com/0/yggdrasil-stopfix-0.3.5-0142-windows-amd64.exe
32-bit: https://1135-115685026-gh.circle-artifacts.com/0/yggdrasil-stopfix-0.3.5-0142-windows-i386.exe

**Comment by Vort** [comment]
No overwrite now, but still no "Stopping...".
Maybe #451 is blocking that message?

**Comment by neilalexander** [comment]
https://circleci.com/gh/yggdrasil-network/yggdrasil-go/1139#artifacts/containers/0 might fix the peers blocking on a failed connection and also rearranges the terminate logic a bit, wondering if that helps at all?

64-bit: https://1139-115685026-gh.circle-artifacts.com/0/yggdrasil-stopfix-0.3.5-0144-windows-amd64.exe
32-bit: https://1139-115685026-gh.circle-artifacts.com/0/yggdrasil-stopfix-0.3.5-0144-windows-i386.exe

If it doesn't fix the issue with capturing the service stopping then that'll need to be investigated further with what's going on with the [minwinsvc](https://github.com/kardianos/minwinsvc) wrapper that we use for Windows services—we didn't write that. Neither me nor Arceliar use Windows as our day-to-day platforms and we don't have many Windows testers :-)

**Comment by Vort** [comment]
No luck with "Stopping..." again.

**Comment by neilalexander** [comment]
OK, the premise of this issue is fixed so I'll close this issue and will open a new one for the fact that the Windows stop handler may not be being called.
