### ISSUE TITLE
Dev version makes no peer connections

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#451]
After dev version (0.3.5-0140) is started, `yggdrasilctl.exe getPeers` command returns only my node.
Configuration file contains list of 14 peers.
OS: Windows 7 SP1 x64

**Comment by neilalexander** [comment]
Was the release v0.3.5 build working normally before you tried `develop`?

Can you confirm that your peers are formatted in full `tcp://a.b.c.d:e` style?

Are they `Peers` or `InterfacePeers`?

**Comment by Vort** [comment]
> Was the release v0.3.5 build working normally before you tried develop?

I was most likely using lower version, but 0.3.5 works fine too.

> Can you confirm that your peers are formatted in full tcp://a.b.c.d:e style?

I use something like this: `Peers: [ "tcp://185.164.138.18:1001" ]`

**Comment by Mikaela** [comment]
I am having similar at times on Debian 10, I have gotten it to work with various methods like `systemctl restart NetworkManager yggdrasil tor-client dnscrypt-proxy` and restarting my router as the problem often seems to hit when my router has forgotten it should share IPv6 connectivity to my LAN.

**Comment by Vort** [comment]
But peers are IPv4. And no information about problem contained in logs.

**Comment by neilalexander** [comment]
Can you increase logging output to `-logging error,warn,info,debug,trace` and see if anything is shown there?

**Comment by Vort** [comment]
This problem and #450 are specific to Windows service mode of operation.

**Comment by Vort** [comment]
My first peer most likely is offline now. Yggdrasil tries to connect to it, fails, and make no connection to other peers.
You can simulate this by this config: `Peers: [ "tcp://8.8.8.8:12345", "tcp://185.164.138.18:1001" ]`
Log contains `2019/07/06 13:37:55 Failed to dial TCP: dial tcp 8.8.8.8:12345: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.` and no more connection related lines.

**Comment by neilalexander** [comment]
Hm, okay, that's a far more unique and interesting scenario. Let me take a look at what's going on.

**Comment by Vort** [comment]
Problem _may be_ fixed.
Now peer connections are going, but no packet transmissoin can be done.
(`ping 21f:dd73:7cdb:773b:a924:7ec0:800b:221e` do nothing)
Should I make another report?

**Comment by neilalexander** [comment]
Yes I think that might be best! I think @Arceliar mentioned recently that there was a problem with the TAP mode in `develop` on Linux so that probably affects Windows too.
