### ISSUE TITLE
Windows service shutdown handler may not be being called

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#452]
We use `minwinsvc` to try and capture the state of the process when running under a Windows service. The shutdown handler doesn't seem to be being called for some reason.

**Comment by Vort** [comment]
Now I see it with `0.3.5-0184`:
`2019/07/22 10:31:21 Stopping...`
Not sure if it shows always, but looks like fixed.

**Comment by neilalexander** [comment]
I'll close this for now then, we can reopen if it becomes an issue again.
