### ISSUE TITLE
No packet transmission with latest dev build

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#454]
With `yggdrasil-stopfix-0.3.5-0144-windows-amd64.exe` binary `ping 21f:dd73:7cdb:773b:a924:7ec0:800b:221e` command shows timeouts.
While it works fine with 0.3.5.

**Comment by neilalexander** [comment]
Can you please try the build from

**Comment by neilalexander** [comment]
Oops, didn't mean to close.

Can you please try the build on Windows at https://circleci.com/gh/yggdrasil-network/yggdrasil-go/1147#artifacts/containers/0 for this issue?

64-bit: https://1147-115685026-gh.circle-artifacts.com/0/yggdrasil-tapfix-0.3.5-0147-windows-amd64.exe
32-bit: https://1147-115685026-gh.circle-artifacts.com/0/yggdrasil-tapfix-0.3.5-0147-windows-i386.exe

**Comment by Vort** [comment]
I don't see any difference.
But maybe this can help?
```
2019/07/06 19:16:34 netsh command: netsh interface set interface TapAdapter admin=ENABLED
2019/07/06 19:16:34 netsh command: %v netsh interface ipv6 set subinterface interface=TapAdapter mtu=65535 store=active
2019/07/06 19:16:35 Interface name: TapAdapter
2019/07/06 19:16:35 Interface IPv6: 200:f001:9c61:be26:2e6e:cd55:a454:2ada/7
2019/07/06 19:16:35 Interface MTU: 65535
2019/07/06 19:16:35 netsh command: %v netsh interface ipv6 add address interface=TapAdapter addr=200:f001:9c61:be26:2e6e:cd55:a454:2ada/7 store=active
2019/07/06 19:16:35 Configuring CKR...
```
What that `%v` is for?

**Comment by neilalexander** [comment]
That's a red herring I think as it looks to just be a mistake in the `tun.log.Printf` line. Does your adapter show having an IPv6 address correctly when Yggdrasil is running?

**Comment by Vort** [comment]
> That's a red herring I think

I agree.

> Does your adapter show having an IPv6 address correctly when Yggdrasil is running?

Yes, address is correct.

**Comment by neilalexander** [comment]
How does https://circleci.com/gh/yggdrasil-network/yggdrasil-go/1151#artifacts/containers/0 look?

64-bit: https://1151-115685026-gh.circle-artifacts.com/0/yggdrasil-tapfix-0.3.5-0148-windows-amd64.exe
32-bit: https://1151-115685026-gh.circle-artifacts.com/0/yggdrasil-tapfix-0.3.5-0148-windows-i386.exe

**Comment by Vort** [comment]
It works now.
When not crashes :)
