### ISSUE TITLE
Problem starting while IPsec/L2TP is connected

### ISSUE THREAD

**Issue by xaozai** [yggdrasil-network/yggdrasil-go#464]
Tried tap-windows-9.9.2_3 and tap-windows-9.21.2.
Run as admin output (yggdrasil-0.3.5-windows-amd64.exe -useconffile yggdrasil.conf):
2019/07/18 13:19:46 Build name: yggdrasil
2019/07/18 13:19:46 Build version: 0.3.5
2019/07/18 13:19:46 Starting up...
2019/07/18 13:19:46 Starting switch
2019/07/18 13:19:46 Starting router
2019/07/18 13:19:46 Listening for TCP on: 127.0.0.1:5715
2019/07/18 13:19:46 Multicast discovery is disabled
2019/07/18 13:19:46 TCP admin socket listening on 127.0.0.1:9001
2019/07/18 13:19:46 netsh command: netsh interface set interface  admin=DISABLED
2019/07/18 13:19:46 Windows netsh failed: exit status 1.
2019/07/18 13:19:46 Failed to start TUN/TAP
2019/07/18 13:19:46 An error occurred during startup
panic: exit status 1
goroutine 1 [running]:
main.main()
        /home/circleci/project/cmd/yggdrasil/main.go:252 +0x1146

Windows 7 Professional x64

**Comment by Vort** [comment]
Maybe name of your adapter contains non-English characters?
If that is the case, try to rename it to, for example, `TapAdapter` and add it to config:
`  IfName: TapAdapter`

**Comment by xaozai** [comment]
I rename them immediately after installation, so as not to get confused in the future.
In the config I specified the name Ygg.
Although, this adapter is normally determined by Ygg when set to "auto".
When Ygg does not find the adapter, it displays another error message.
![01](https://user-images.githubusercontent.com/8542452/61455041-29d60f00-a96b-11e9-9e61-9001c9ff825a.png)
![02](https://user-images.githubusercontent.com/8542452/61455042-29d60f00-a96b-11e9-84a8-26f7f0492349.png)

**Comment by Vort** [comment]
`2019/07/18 13:19:46 netsh command: netsh interface set interface admin=DISABLED` line means that problem is somehow related to adapter name.
Here is how it looks for me:
`2019/07/18 15:00:58 netsh command: netsh interface set interface TapAdapter admin=DISABLED`
I also encountered similar problems, where adapter name was blank, but they was disappearing after several restarts of Yggdrasil.

**Comment by neilalexander** [comment]
When we look up available TAP adapters, we use the Windows registry.

Can you please open `regedit.exe`, navigate to the following area:
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002BE10318}
```
Under here there are various folders with numbers, e.g. `0001`. If you look through these, you should find one (or more) of these that refer to the TAP adapter, e.g. `ProductName` = `TAP-Windows Adapter V9`. 

Can you screenshot those relevant areas and attach them please?

They *should* have `ComponentId` = `tap0901`.

**Comment by xaozai** [comment]
Ок. Here is a screenshot.
![15](https://user-images.githubusercontent.com/8542452/61463564-56932200-a97d-11e9-8f3d-cae4edab9c28.png)

**Comment by Vort** [comment]
@neilalexander maybe program should stop as soon as it finds empty interface name?

**Comment by neilalexander** [comment]
Can you please check the behaviour in the following `develop` build?

64-bit: https://1257-115685026-gh.circle-artifacts.com/0/yggdrasil-develop-0.3.5-0179-windows-amd64.exe
32-bit: https://1257-115685026-gh.circle-artifacts.com/0/yggdrasil-develop-0.3.5-0179-windows-i386.exe

**Comment by neilalexander** [comment]
Can you please test the following `develop` build to see if interface selection is fixed:

64-bit: https://1261-115685026-gh.circle-artifacts.com/0/yggdrasil-develop-0.3.5-0181-windows-amd64.exe
32-bit: https://1261-115685026-gh.circle-artifacts.com/0/yggdrasil-develop-0.3.5-0181-windows-i386.exe

**Comment by neilalexander** [comment]
Please test the following build to see if you still have problems:

64-bit: https://1273-115685026-gh.circle-artifacts.com/0/yggdrasil-develop-0.3.5-0184-windows-amd64.exe
32-bit: https://1273-115685026-gh.circle-artifacts.com/0/yggdrasil-develop-0.3.5-0184-windows-i386.exe

**Comment by xaozai** [comment]
@neilalexander, I noticed something strange: if before starting the application, I connect to the VPN server (L2TP/IPSEC), the application displays the following message:
```
2019/07/22 09:27:48 Build name: yggdrasil-develop
2019/07/22 09:27:48 Build version: 0.3.5-0184
2019/07/22 09:27:48 Starting up...
2019/07/22 09:27:48 Starting switch
2019/07/22 09:27:48 Starting router
2019/07/22 09:27:48 Listening for TCP on: 127.0.0.1:2156
2019/07/22 09:27:48 Startup complete
2019/07/22 09:27:48 TCP admin socket listening on 127.0.0.1:9001
**2019/07/22 09:27:48 An error occurred starting TUN/TAP: unable to find TAP adapt
er with component ID tap0901**
2019/07/22 09:27:48 Your IPv6 address is 200:b886:73cd:75d8:abd:cb8e:baff:fe4c
2019/07/22 09:27:48 Your IPv6 subnet is 300:b886:73cd:75d8::/64
2019/07/22 09:27:48 Connected TCP: 200:e6bd:2cff:628e:bfb8:a636:d600:306b@194.17
7.21.156, source 10.0.2.2
```
194.177.21.156 is a public
10.0.2.2 is the IP address assigned to me when I connect to the VPN server.

And when I'm not connected to a VPN server, the app starts up and works fine:
```
2019/07/22 09:37:59 Build name: yggdrasil-develop
2019/07/22 09:37:59 Build version: 0.3.5-0184
2019/07/22 09:37:59 Starting up...
2019/07/22 09:37:59 Starting switch
2019/07/22 09:37:59 Starting router
2019/07/22 09:37:59 Listening for TCP on: 127.0.0.1:2353
2019/07/22 09:37:59 Startup complete
2019/07/22 09:37:59 TCP admin socket listening on 127.0.0.1:9001
2019/07/22 09:37:59 Connected TCP: 200:e6bd:2cff:628e:bfb8:a636:d600:306b@194.17
7.21.156, source 10.11.28.111
2019/07/22 09:38:00 Interface name: Ygg
2019/07/22 09:38:00 Interface IPv6: 200:b886:73cd:75d8:abd:cb8e:baff:fe4c/7
2019/07/22 09:38:00 Interface MTU: 65535
2019/07/22 09:38:00 Your IPv6 address is 200:b886:73cd:75d8:abd:cb8e:baff:fe4c
2019/07/22 09:38:00 Your IPv6 subnet is 300:b886:73cd:75d8::/64
```
10.11.28.111 is my IP address on the local network.

**Comment by xaozai** [comment]
And by the way, the last time I tried to run the application (4 days ago), I was also connected to the same VPN server. Now I tried to disconnect from VPN, started yggdrasil-0.3.5-windows-amd64 (last release) and it works! Apparently, the problem is in some conflict when connecting to VPN (L2TP/IPsec).

**Comment by neilalexander** [comment]
Curious, I am not really sure why IPsec/L2TP would have anything to do with TAP but I can try and experiment with this sometime. In the meantime I'll rename the issue.

**Comment by Vort** [comment]
Just a guess - maybe VPN software locks registry access for adapter while it is used?

**Comment by Vort** [comment]
I have tried 3 thing while reproducing:
1. Using of `openvpn-install-2.4.7-I607-Win7.exe` + new TAP V9 adapter.
Result -> `netsh` error.
2. Using of `openvpn-connect-2.7.1.101_signed.msi` + auto-installed TAP Adapter OAS NDIS 6.0.
Result -> no error.
3. Using of Windows standard VPN connection (L2TP/IPsec):
Result -> `2019/07/23 18:09:06 An error occurred starting TUN/TAP: unable to find TAP adapter with component ID tap0901`.
So the problem can be easily reproduced inside VM with no additional software.

**Comment by Vort** [comment]
I have found where is the problem:
[		if bytes.Equal(v.HardwareAddr[:6], mac[:6]) {](https://github.com/yggdrasil-network/water/blob/28ccb9101d557cfd4df49adccbc4e9dd432ec0de/syscalls_windows.go#L316)
`v.HardwareAddr` can be empty, which means problems.

**Comment by neilalexander** [comment]
I guess the `v.HardwareAddr` goes out of bounds in that instance and the `panic` is masked by a `recover()` further up in the function. I have added a fix (and created a PR in the upstream Water repository)—can you please test this build?

64-bit: https://1289-115685026-gh.circle-artifacts.com/0/yggdrasil-fixwindows-0.3.5-0191-windows-amd64.exe
32-bit: https://1289-115685026-gh.circle-artifacts.com/0/yggdrasil-fixwindows-0.3.5-0191-windows-i386.exe

**Comment by xaozai** [comment]
Tested Ygg while IPsec/L2TP is connected. Yes, now everything works fine for me!
Thank you, @neilalexander, @Vort!

**Comment by neilalexander** [comment]
Glad to hear it. This should now be in `yggdrasil-develop-0.3.5-0191`.
