### ISSUE TITLE
Listen on BSD is IPv4 or IPv6 only

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#47]
Affects at least OpenBSD.

On other platforms, listening on `[::]:12345` seems to bind to IPv4 and IPv6 (I would have expected this to be IPv6 only, and `:12345` to be dual-stack, but apparently the latter is IPv4 only). On OpenBSD, these bind to IPv6 and IPv4 respectively.

We either need to figure out how to listen on a dual stack socket, or open separate sockets for IPv4 and IPv6. The latter option may be difficult, as it raises the question of which socket to use to get the port for multicast announcements to find local peers.

**Comment by Arceliar** [comment]
Followup, not sure if this is true of all BSDs, but I'm told that OpenBSD intentionally doesn't support dual-stack sockets. So the fix here is to listen on two sockets, one of which is bound to IPv4, and the other to IPv6.

This is tedious but not technically difficult to do. The bigger question is how to handle it in the config. We may need to support multiple listen addresses, or else figure out that the undefined address is used (and then listen on all addresses in such cases). If we allow for multiple addresses, then we need to handle the case where someone configures multiple addresses of the same type, which quickly becomes complicated. Perhaps, in the short term, we should only use a listen port (and then listen on all addresses on both IPv4 and IPv6), until the multiple address question is answered.

**Comment by Arceliar** [comment]
It sounds like another alternative is to do nothing, and continue to only listen on all IPv6 addresses on OpenBSD. OpenBSD users who need to listen on IPv4 could set up a 4-to-6 relay, or something like that.

**Comment by neilalexander** [comment]
>

If we do nothing then the user can fix this with [relayd](https://man.openbsd.org/relayd.8) using something like this, as trn mentioned in the Matrix channel:
```
relay 6-to-4 {
  forward to 127.0.0.1 port 999
  listen on fd00::1 port 999
}
```
This isn't ideal but it does mean we aren't adding more platform-specific behaviour than is required. It'd be worth seeing if this is also true on FreeBSD and NetBSD.

**Comment by neilalexander** [comment]
Some quick research:

- FreeBSD 11 `netstat -an` shows `tcp46`/`udp46`. Accepts connections on **both** `::1` and `127.0.0.1`.
- NetBSD 7.1.1 `netstat -an` shows `tcp6`/`udp6`. Accepts connections on **both**  `::1` and `127.0.0.1`.
- OpenBSD 6.2 `netstat -an` shows `tcp6`/`udp6`. Accepts connections on `::1` but **not** `127.0.0.1`.

Seems that this issue is specific to OpenBSD.

**Comment by Arceliar** [comment]
I guess it should be enough for now to provide a workaround in the OpenBSD documentation.

**Comment by Arceliar** [comment]
#57 covers this well enough for now, I guess.
