### ISSUE TITLE
Permission Denied When running as root.

### ISSUE THREAD

**Issue by int-0x03** [yggdrasil-network/yggdrasil-go#479]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/42711898/62247988-b662e180-b3ef-11e9-9052-499ff35df4db.png">
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/42711898/62248094-f4f89c00-b3ef-11e9-803b-ab0c2fe324de.png">

How it works? No Selinux. 

`Linux n2o.ddns.net 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Config default, generated by command:

`sudo yggdrasil -genconf > /etc/yggdrasil.conf`

**Comment by neilalexander** [comment]
Is this a container or VPS of some kind? OpenVZ maybe?

**Comment by int-0x03** [comment]
Оh.... yes, it's a VPS in qemu-kvm virtualization. Inside VPS yggdrasil does'nt work?

**Comment by int-0x03** [comment]
I Just compile this example https://github.com/songgao/water, and TAP and TUN interface created are correct.

**Comment by int-0x03** [comment]
I Just compile this example on same VPS server https://github.com/songgao/water, and TAP and TUN interface created are correct.

**Comment by neilalexander** [comment]
Hmm, okay, it's possible that it's something Yggdrasil does specifically then. Some things to try:
- Try changing `IfName` to a specific interface name, e.g. `tun1`, or try leaving it as `auto`
- Try changing `IfMTU` down to 9000, 1500, etc
- Try changing between `IfTAPMode` as `true` and `false`

**Comment by int-0x03** [comment]
The problem is solved. I completely forgot that my system was forcibly disabled IPv6 subsystem. To enable it, I had to comment out the following lines in the file **/etc/sysctl.conf**:

```
#net.ipv6.conf.all.disable_ipv6 = 1
#net.ipv6.conf.default.disable_ipv6 = 1
#net.ipv6.conf.lo.disable_ipv6 = 1
```

When IPv6 is disabled, system return "Permission Denied" when you want assign IPv6 addr to any interface. I checked it with the following command:

`ip -6 addr add 200:f75d:8c06:87d3:e15c:222f:b1c7:6fdc dev tun6`

When IPv6 is disabled, it returns **Permission denied**.

**Comment by int-0x03** [comment]
May be you add some checkings or some note in documentation about it?

**Comment by neilalexander** [comment]
Thanks for the update. I'm curious to know whether disabling IPv6 was something you did or whether that was a default in your distribution?

**Comment by int-0x03** [comment]
IPv6 was turned off by me earlier.  But I forgot about it.  I turned it off, because I can’t use it to the full., But at the same time it requires separate configuration of ip6tables, which I did not want to do.  It was faster to simply turn it off so as not to create security holes.

**Comment by neilalexander** [comment]
I think in that case it's fine to close this as-is—I guess our homepage probably makes the need for IPv6 support to be fairly obvious, although if you are running a public peer or some host that acts as a router only, IPv6 would not be required if TUN/TAP is disabled.

**Comment by int-0x03** [comment]
Yes, it's true.  The most important factor that creates confusion is that the system returns “Permission Denied”, and not something like “IPv6 subsystem disabled”.  Thanks for the help. 👍🏻

**Comment by neilalexander** [comment]
Can you quickly check for me what the result is of `test -f /proc/net/if_inet6` on your system when IPv6 is enabled and disabled? That may be a good way for us to check and report if IPv6 is disabled with a better error.

**Comment by int-0x03** [comment]
Unfortunately, in both cases outputs enable.
![Снимок экрана 2019-08-08 в 16 40 02](https://user-images.githubusercontent.com/42711898/62708632-76f25180-b9fc-11e9-846b-538ef6a202d3.png)
![Снимок экрана 2019-08-08 в 16 45 57](https://user-images.githubusercontent.com/42711898/62708634-7954ab80-b9fc-11e9-83ad-37eef2f4922c.png)

**Comment by neilalexander** [comment]
Hm, okay, so `/proc/net/if_inet6` must exist when the kernel module is loaded, even if IPv6 is disabled at the interface level. I'll have a think and see if there's a way we can warn about this situation more reliably.
