### ISSUE TITLE
V0.3.6 cannot show version without “floating point hardware”

### ISSUE THREAD

**Issue by kseistrup** [yggdrasil-network/yggdrasil-go#482]
I have `yggdrasil` v0.3.6 up and running flawlessly on a virtualised ARM VPN, yet I see this hilarious and contradicting message:

```sh
$ yggdrasil -version
runtime: this CPU has no floating point hardware, so it cannot run
this GOARM=7 binary. Recompile using GOARM=5.
```

**Comment by kseistrup** [comment]
On another virtualised VPN (x86_64) `yggdrasil` simply segfaults when asked about its version:

```sh
$ yggdrasil -version
Segmentation fault
```

and kernel log shows this:

```
Aug  4 18:58:15 myvpn kernel: yggdrasil[3505] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffe5a7cd9b8 ax:ffffffffff600000 si:0 di:7ffe5a7cd9c0 
Aug  4 18:58:15 myvpn kernel: yggdrasil[3505] segfault at ffffffffff600000 ip ffffffffff600000 sp 00007ffe5a7cd9b8 error 15 
Aug  4 18:58:15 myvpn kernel: Code: Bad RIP value. 
```

Yet `yggdrasil` runs its normal job just fine.

**Comment by neilalexander** [comment]
I am really not sure why floating point would be necessary in this instance. I guess this problem goes away if you compile with `GOARM=5` as it mentions?

**Comment by kseistrup** [comment]
It probably will. However, the main yggdrasil functionality is unaffected by this, so I might as well just use the binary compiled for the architecture shown in `/proc/cpuinfo`.

I reported this issue mainly because if a simple thing like showing the version information is allegedly requiring an FPU, or that the binary segfaults with a ‘Bad RIP code’, then you might get all sorts of spurious bug reports from people who are using yggdrasil on virtualised hardware. And knowing this could potentially save everybody's precious time and energy.

**Comment by neilalexander** [comment]
Well this is the weird thing—when doing `-version`, the only functions we call are `yggdrasil.BuildName()`, `yggdrasil.BuildVersion()` and `os.Exit(0)`.

The `yggdrasil.BuildName()` and `yggdrasil.BuildVersion()` functions are *also* called even if you are running the node normally, as we output those things into the regular `stdout` log. Does that output look normal in your case? e.g.
```
2019/08/03 12:18:30 Build name: yggdrasil
2019/08/03 12:18:30 Build version: 0.3.6
2019/08/03 12:18:30 Starting up...
2019/08/03 12:18:30 Starting switch
2019/08/03 12:18:30 Starting router
```

**Comment by kseistrup** [comment]
That is exactly the output I see when I launch the binaries on my VPNs. They are started and held afloat by `systemd`, but that shouldn't make any difference. So yes, that's weird. 

(I also get the reported errors when I do just `yggdrasil -h`.)

**Comment by kseistrup** [comment]
Perhaps these errors comes from the operating system, not yggdrasil:

I have

```sh
$ sudo setcap CAP_NET_ADMIN+eip /usr/bin/yggdrasil
```

in order to have yggdrasil doing its things as an unprivileged user, and when I say `yggdrasil -version` it runs the setcap(8)'ed binary. If I instead say `./yggdrasil -version` from the build directory, the ‘plain’ binary behaves as expected and shows me the version.

It still doesn't explain why `systemd` is able to run the setcap(8)'ed binary, though.

Also: I have setcap(8)'ed binaries running on two other VPNs (with another provider, possibly under another virtualisation) where I can call `yggdrasil -version` and get an answer.

**Comment by kseistrup** [comment]
> `Aug  4 18:58:15 myvpn kernel: Code: Bad RIP value.`

Possibly related to #403

**Comment by kseistrup** [comment]
The floating point thing and the bad RIP value thing are indeed related to #403:

If I

```sh
$ sudo sysctl fs.suid_dumpable=1  # default value: 0
```

I can run `yggdrasil -version` on plain and setcapped binaries alike and get a sane answer.

**Comment by neilalexander** [comment]
I guess this is a problem in the Go runtime then and not Yggdrasil?

**Comment by kseistrup** [comment]
I guess so.

**Comment by neilalexander** [comment]
I'll close this for now then as I'm not sure we can do anything in this instance.
