### ISSUE TITLE
Rethink ReadNoCopy/WriteNoCopy API

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#490]
Currently we export `ReadNoCopy` and `WriteNoCopy` in `develop` which improves performance a lot by reducing copies on hot paths. However this API perhaps isn't very friendly and can be improved, perhaps by implementing a `yggdrasil.ShallowConn` type that implements these methods as `Read`/`Write` and then having `yggdrasil.Conn` extend those with overloaded functions.

**Comment by Arceliar** [comment]
If we use the names `Read` and `Write` for a new type, we need to be careful that we don't accidentally match the `Reader` and `Writer` interfaces, so it's not usable in those places by mistake.

**Comment by Arceliar** [comment]
The NoCopy part of the API was removed in #526. We can expose it again later (probably with better names) if there's ever a need for it, but in the mean time we use the actor-based API for our tun/tap, and expose `Read` and `Write` methods for normal Go code.
