### ISSUE TITLE
Windows: sockets are not closed during service shutdown sometimes

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#495]
When Windows service is stopped, Yggdrasil sometimes fails to close sockets properly.
Because of this, after service stop, remote node keeps thinking that connection is still alive.
And when service is started again, remote node make instant reset for new connection.

It is possible that when `os.Exit(0)` is called, some threads still performing their work:
https://github.com/yggdrasil-network/yggdrasil-go/blob/a2966291b919996d94a76792d958dae0d31be078/cmd/yggdrasil/main.go#L268-L274

Related: #452.

**Comment by Arceliar** [comment]
Hopefully fixed in #548.

**Comment by Vort** [comment]
Results are definetely better now (also startup is much faster).
It is still possible to make a problems if you stop service withing a seconds after start.
Also log is filled with `use of closed network connection` errors.
But I think it's ok to close this report.
