### ISSUE TITLE
Dial [probaby] blocked

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#496]
So here's the issue:

1. The map server queries `y.yakamo.org` (a container in `300::/8` on @neilalexander's host) every 10 minutes to get an updated list of known nodes.
2. The map server stopped updating (getting the list times out), pinging `y.yakamo.org` doesn't work, etc.
3. No session to the corresponding `200::/8` host exists.
4. Pinging the `200::/8` immediately works, and the map server starts updating again.
5. As soon as the session to the `200::/8` node times out, the `300::/8` is back to timing out.

So here's what I think is happening:

1. The query to y.yakamo.org tries to 'Dial' with a 'NodeID' and 'Mask' based on the '300::/8` address.
2. We `Dial` only once, so future attempts to dial this target `NodeID` just buffer a packet for the current `Dial` to send when it finishes.
3. The `Dial` fails for some reason, but does *not* finish timing out / clean itself up, so the `300::/8` address stays blocked.
4. Pinging the `200::/8` address starts a new search with a new target `NodeID` and `Mask`, which succeeds, creating a session and returning a working `Conn`.
5. The `Conn`/session covers the `300::/8` address's range, so packets are directed there instead of to the blocked `Dial`.
6. The `Conn` eventually times out due to lack of use, and the blocked `Dial` goes back to eating our packets.

**Comment by neilalexander** [comment]
So far this looks to be fixed—will reopen if it happens again.
