### ISSUE TITLE
Build script now fails silently

### ISSUE THREAD

**Issue by l-n-s** [yggdrasil-network/yggdrasil-go#509]
I forgot to enable Internet connection before running the build script. Script failed silently without throwing any messages. After I've commented that `set -ef ` line, it showed an error with my Internet connection, and now I can understand what's going on. 

The problem is introduced in ebdd968c246e281f73133d83b0b072464b133050

**Comment by neilalexander** [comment]
We recently fixed a problem in 27158d7 where the semantic versioning stuff was causing a problem and silently killing builds when not using a known tag.

However, if we remove the `set -ef` then it causes problems with the CircleCI build pipeline if it cannot correctly report on the exit status of a build.

I’ll close this for now.
