### ISSUE TITLE
Panic when exec yggdrasil -useconffile /config/yggdrasil.conf

### ISSUE THREAD

**Issue by Eninspace** [yggdrasil-network/yggdrasil-go#522]
Container-Optimized OS, similar problem I have on Android device

`panic: no such file or directory goroutine 1 [running]: 
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0xc00009dc50, 0xc00001a760, 0x4, 0x0, 0xc000016330, 0x27, 0xffff, 0x94741523c0af801, 0x685f3b12d98f36bb)
 /src/src/tuntap/tun_linux.go:26 +0x4c2 github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start(0xc00009dc50, 0xc000010238, 0x0) 
/src/src/tuntap/tun.go:140 +0x3f5 main.main() /src/cmd/yggdrasil/main.go:249 +0xf3d`

**Comment by Eninspace** [comment]
Yes, it trying to open /dev/net/tun, and doesn't find it. On my android tun interface exist in /dev/tun

**Comment by neilalexander** [comment]
Can you try proving the concept for now with:
```
mkdir /dev/net
ln -s /dev/tun /dev/net/tun
```
... and check that it works as expected when `/dev/net/tun` exists?

**Comment by Eninspace** [comment]
This works, the interface is created, but only without an admin socket, because it is not created.

`Admin socket failed to listen: listen unix /var/run/yggdrasil.sock: bind: no such file or directory`

**Comment by neilalexander** [comment]
OK, that’s encouraging. The admin socket can be disabled by setting `IfName` to `none` in the config if I remember right, or you can replace it with something like `tcp://localhost:9001`.

**Comment by neilalexander** [comment]
Closing this for now due to inactivity.
