### ISSUE TITLE
yggdrasil conflicts with OpenVPN under windows

### ISSUE THREAD

**Issue by xaozai** [yggdrasil-network/yggdrasil-go#523]
Windows Server 2012R2 x64
yggdrasil-0.3.8-windows-amd64
tap-windows-9.9.2_3

When the OpenVPN service is started yggdrasil displays this message at startup:
`An error occurred starting TUN/TAP: A device attached to the system is not functioning.`
If I stop the OpenVPN service and then start yggdrasil, yggdrasil works fine, but OpenVPN will no longer work when I start the service.

**Comment by Vort** [comment]
Do you have several TAP adapters installed?

**Comment by xaozai** [comment]
Probably the problem is that I only have one TAP adapter installed. I can't install the second one.
OpenVPN 2.4.7 x86_64-w64-mingw32

**Comment by xaozai** [comment]
When starting with OpenVPN stopped, the following messages are periodically displayed:
`TUN/TAP iface write error: no peer MAC known for 200:acb3:be2b:b84c:10b6:17e0:a02f:2e23  - dropping packet
TUN/TAP iface write mismatch: 0 bytes written vs 72 bytes given`

**Comment by Vort** [comment]
> Probably the problem is that I only have one TAP adapter installed. I can't install the second one.

Can you try `c:\Program Files\TAP-Windows\bin>"devcon.exe" install "C:\Program Files\TAP-Windows\driver\OemWin2k.inf" tap0901`?

**Comment by xaozai** [comment]
@Vort, It worked! Thanks!
And messages from my previous post - is this normally?

**Comment by xaozai** [comment]
The adapter was added, but it did not solve the problem. The conflict is still present.

**Comment by Vort** [comment]
> The conflict is still present.

Try to use different adapter for Yggdrasil. Give them different names, look what adapter is used by OpenVPN and set other one in Yggdrasil config `IfName:` parameter.

> And messages from my previous post - is this normally?

Looks like no, but I'm not sure what is happening there.

**Comment by xaozai** [comment]
I got it. Specified in ygg's config the name of the adapter and now works both OpenVPN and yggdrasil.
