### ISSUE TITLE
An error occured starting TUN/TAP: file exists

### ISSUE THREAD

**Issue by kravietz** [yggdrasil-network/yggdrasil-go#530]
Yggdrasil 0.3.8 fails to start on Ubuntu 19 due to a cryptic error:

```
An error occured starting TUN/TAP: file exists
```
The `tun0` interface is created but left in `DOWN` state. Yggdrasil runs but connections don't work.

**Comment by neilalexander** [comment]
Can you please check if configuration file has `IfName` set to `auto` or does it specify `tun0` specifically?

If no other process is using the leftover `tun0` then you can try:
```
ip link del tun0
```

**Comment by kravietz** [comment]
After stopping Yggdrasil and ensuring there's no leftover `tun0` I start, and the daemon starts OK (via systemd) but still displays the message and the newly created `tun0` is down.

**Comment by neilalexander** [comment]
Did you install using our `.deb` or through some other method?

What is `IfName` set to in your `yggdrasil.conf`?

**Comment by kravietz** [comment]
Sorry, forgot to mention - it's `auto`. And yes, it comes from a `deb`. I'll try to reinstall just in case.

**Comment by kravietz** [comment]
Yeah, after reinstall it's pretty much the same. Service starts but warning is there and interface is `DOWN`... Really weird...

**Comment by neilalexander** [comment]
That is weird. Has this just started happening with 0.3.8?

I am wondering if there is something else on the system trying to manage the `tun0` adapter, e.g. `systemd-networkd` or `netplan` or similar. I haven't come across this happening anywhere else yet.

**Comment by kravietz** [comment]
The problem seems to be with `netplan` apparently. The workaround is to add this to the `yggdrasil.service` file:

```
ExecStartPost=/usr/sbin/ip link set tun0 up
```
Silly, but works...
