### ISSUE TITLE
json formatted peers fails silently

### ISSUE THREAD

**Issue by jcgruenhage** [yggdrasil-network/yggdrasil-go#536]
If you use an hjson config and configure the peers section with regular json formatting, it fails silently, even though hjson should be a superset of json.

**Comment by neilalexander** [comment]
I suspect this is a problem in `hjson-go` so I’m going to drop this from the v0.3.9 milestone until I get a chance to look at it properly for a future release.

**Comment by neilalexander** [comment]
Closing as out-of-date and this is probably an upstream problem if it is still an issue.
