### ISSUE TITLE
Factor keys out

### ISSUE THREAD

**Issue by perguth** [yggdrasil-network/yggdrasil-go#538]
Keys should be factored out into their own files `.pub`, `.priv` and `authorized_keys` maybe? Like SSH?! 🐱 

The default currently features the priv keys right next to the pub key. So every time one wants to get the pub key his/her needs to also display the priv key. That's bad :-/

**Comment by neilalexander** [comment]
At the moment we keep all configuration in one place because that allows us to accept it through `stdin` (with `-useconf`) in addition to getting it from the filesystem (with `-useconffile`).

You can also get your public key using something like `sudo yggdrasilctl getSelf -v`.

**Comment by perguth** [comment]
Oh, then maybe this is a regression:
```
user@host:~$ sudo yggdrasilctl getself -v
Build name: yggdrasil
Build version: 0.3.8
IPv6 address: ...
IPv6 subnet: ...
Coords: ...
```

**Comment by Slex** [comment]
Ok, I can implement this tonight :)

**Comment by neilalexander** [comment]
That’s a bug then if the public key isn’t shown with `-v`. Does it appear in the JSON data if you pass `-json` instead of `-v`?

**Comment by perguth** [comment]
I checked: `sudo yggdrasilctl -v getself` that worked and printed out the key. The `-v` has to go before the `getself`.

**Comment by perguth** [comment]
I guess a good idea would be to order the items in the config file differently. Bring stuff like public key to the beginning and things like tunnelling and private keys to the end. That's what I do manually when I set up Ygg nodes.

**Comment by neilalexander** [comment]
v0.5 will allow setting `PrivateKeyPath` and pointing to a PEM file containing the ed25519 private key instead.
