### ISSUE TITLE
onion/i2p peers are displayed incorrectly in "yggdrasilctl getPeers" output

### ISSUE THREAD

**Issue by l-n-s** [yggdrasil-network/yggdrasil-go#539]
Proxified peers are displayed like: 
    socks://127.0.0.1:9050/127.0.0.1:9050

expected output:
    socks://127.0.0.1:9050/ruoqfb5l2n55x62gu4qsooqm6yamnkjnbqmr6xbxppkxbccgyvioc3ad.onion:5050

It was working fine at version 0.3.5, this started to happen after 0.3.6

**Comment by neilalexander** [comment]
This should be fixed in `develop` after commit ae0b267 - please test the latest `develop` build and let us know.

**Comment by l-n-s** [comment]
Great, it's correct now.
