### ISSUE TITLE
SIGTERM often ignored in v0.3.8

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#541]
Quite often I can’t stop the Yggdrasil process with `kill` (without `-9`) since v0.3.8 - not sure if the main thread is blocking on something.

**Comment by Arceliar** [comment]
FWIW I haven't seen this happen yet on linux (and I *very frequently* start ygg in multiple `netns` to run tests and then `killall` them to shut down, so I've probably had a few hundred chances to trigger it since v0.3.8). I wonder if this may be platform specific.

**Comment by neilalexander** [comment]
I've been seeing this happen on Linux quite a lot on my EdgeRouter. I've also seen it happen on macOS a number of times.

**Comment by Mikaela** [comment]
I may have been seeing this on Debian Testing / yggdrasill `0.3.8-0082`, when I `poweroff`, sometimes the screen goes dark and if I am impatient I start pressing [REISUO](https://en.wikipedia.org/wiki/Magic_SysRq_key) and see a flash on Yggdrasil pending shutdown with time limit of maybe three minutes.

Can `IfTAPMode: true` be related?

**Comment by neilalexander** [comment]
I don’t believe this to be related to TAP mode as I also see it in TUN mode.

I have started a debug build on my EdgeRouter so hopefully I’ll be able to catch something with `pprof` next time I try and kill it.

**Comment by neilalexander** [comment]
Should now be resolved with the soft-shutdown stuff in `develop`.
