### ISSUE TITLE
Yggdrasil seemingly ignores `Peers` option

### ISSUE THREAD

**Issue by MarSoft** [yggdrasil-network/yggdrasil-go#546]
I have configured `yggdrasil` adding several public nodes to `Peers` list. But when I start `yggdrasil` in a network with available internet connection and without other active Yggdrasil nodes, it does not connect to anything. Even after an hour waiting, when I issue `yggdrasilctl getpeers` command I still can see just myself.
When I issue `yggdrasilctl addpeer uri=tcp://...` command with one of my configured static peers, the requested peer gets added almost immediately and remains added. But config options is seemingly ignored.

If I run `yggdrasil -normaliseconf`, my `Peers` are included, so they should be visible to Yggdrasil. But for some reason they are never connected to unless I explicitly ask.

Yggdrasil version: `0.3.8`
Platform: Arch Linux. Yggdrasil is installed from `yggdrasil` AUR package.

Tried to run `yggdrasil` with debug logging enabled but did not see anything interesting:
```
# yggdrasil -logging info,warn,error,debug -useconffile /etc/yggdrasil.conf
2019/09/17 23:29:02 Build name: yggdrasil
2019/09/17 23:29:02 Build version: 0.3.8
2019/09/17 23:29:02 Starting up...
2019/09/17 23:29:02 Starting switch
2019/09/17 23:29:02 Starting router
2019/09/17 23:29:02 Startup complete
2019/09/17 23:29:02 Interface name: ygg
2019/09/17 23:29:02 Interface IPv6: 204:***/7
2019/09/17 23:29:02 Interface MTU: 65535
2019/09/17 23:29:02 Configuring CKR...
2019/09/17 23:29:02 CKR configured
2019/09/17 23:29:02 Your IPv6 address is 204:***
2019/09/17 23:29:02 Your IPv6 subnet is 304:***::/64
2019/09/17 23:29:02 UNIX admin socket listening on /var/run/yggdrasil.sock
```

**Comment by neilalexander** [comment]
Your `Peers` section has this format:
```
Peers: [
  tcp://a.b.c.d:port
  tcp://somehostname.org:port
  tcp://[a:b::c:d]:port
]
```
... with no other stray quotemarks or anything like that?

**Comment by MarSoft** [comment]
Yes, no quotemarks.
I have a suspection that the problem is caused by poor internet connection. Is it possible? Internet connection is over 3G, and it has often packet drops. But it looks like Yggdrasil doesn't even try to connect to any non-local peers.

**Comment by neilalexander** [comment]
It would be worth increasing the logging level with something like `-logging error,warn,info,debug,trace` and see if you receive any more feedback about what's going on?

Also would be worth trying this with the latest Yggdrasil release, which is v0.3.10 right now.

**Comment by neilalexander** [comment]
Please retest with the `develop` version `0.3.11-0022` or later, or close the issue if it's no longer relevant.

**Comment by neilalexander** [comment]
Closing due to lack of updates. Please reopen if you are still having a problem with v0.3.14.
