### ISSUE TITLE
Cant start newest release on Windows

### ISSUE THREAD

**Issue by cwchristerw** [yggdrasil-network/yggdrasil-go#553]
TAP Driver version: 9.9.2_3
These are typed in CMD as Administrator

C:\WINDOWS\system32>"C:\Program Files\Yggdrasil Network\yggdrasil-0.3.5-windows-i386.exe" -useconffile "C:\Program Files\Yggdrasil Network\config.conf"
```
2019/09/20 23:02:06 Build name: yggdrasil
2019/09/20 23:02:06 Build version: 0.3.5
2019/09/20 23:02:06 Starting up...
2019/09/20 23:02:06 Found 2 multicast interface(s)
2019/09/20 23:02:06 Starting switch
2019/09/20 23:02:06 Starting router
2019/09/20 23:02:06 Multicast discovery is enabled
2019/09/20 23:02:06 TCP admin socket listening on 127.0.0.1:9001
2019/09/20 23:02:06 netsh command: netsh interface set interface Ethernet 2 admin=DISABLED
2019/09/20 23:02:06 Listening for TCP on: [fe80::4457:9f86:12a:502c%Ethernet]:51811
2019/09/20 23:02:06 Listening for TCP on: [fe80::996e:c618:cd29:6408%Ethernet 2]:51812
2019/09/20 23:02:08 netsh command: netsh interface set interface Ethernet 2 admin=ENABLED
2019/09/20 23:02:09 Interface name: Ethernet 2
2019/09/20 23:02:09 Interface IPv6: [REDACTED]/7
2019/09/20 23:02:09 Interface MTU: 65535
2019/09/20 23:02:09 Startup complete
2019/09/20 23:02:09 Your IPv6 address is [REDACTED]
2019/09/20 23:02:09 Your IPv6 subnet is [REDACTED]/64
```
C:\WINDOWS\system32>"C:\Program Files\Yggdrasil Network\yggdrasil-0.3.8-windows-i386.exe" -useconffile "C:\Program Files\Yggdrasil Network\config.conf"
```
2019/09/20 23:07:18 Build name: yggdrasil
2019/09/20 23:07:18 Build version: 0.3.8
2019/09/20 23:07:18 Starting up...
2019/09/20 23:07:18 Starting switch
2019/09/20 23:07:18 Starting router
2019/09/20 23:07:18 Startup complete
2019/09/20 23:07:18 Listening for TCP on: [fe80::4457:9f86:12a:502c%Ethernet]:51913
2019/09/20 23:07:18 Listening for TCP on: [fe80::996e:c618:cd29:6408%Ethernet 2]:51914
2019/09/20 23:07:18 TCP admin socket listening on 127.0.0.1:9001
2019/09/20 23:07:21 Interface name: Ethernet 2
2019/09/20 23:07:21 Interface IPv6: [REDACTED]/7
2019/09/20 23:07:21 Interface MTU: 65535
2019/09/20 23:07:21 Your IPv6 address is [REDACTED]
2019/09/20 23:07:21 Your IPv6 subnet is [REDACTED]/64
panic: runtime error: index out of range

goroutine 76 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).readerPacketHandler(0x11478bcc, 0x1150a700)
        /home/circleci/project/src/tuntap/iface.go:113 +0x84c
created by github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).reader
        /home/circleci/project/src/tuntap/iface.go:253 +0x8b
```

**Comment by cwchristerw** [comment]
This computer has also NordVPN installed before but it should work correctly because older works just fine :smile:

**Comment by cwchristerw** [comment]
These are also both running default config without any modification. After adding peer older version still works as expected but newest version will still crash

**Comment by cwchristerw** [comment]
I run also newest version on my other laptop/tablet and it works perfectly fine

**Comment by Arceliar** [comment]
It looks like this is the problem:

https://github.com/yggdrasil-network/yggdrasil-go/blob/562a7d1f19f254e9d078aef44a78f7d1398bc4e5/src/tuntap/iface.go#L113

For some reason, the tuntap is returning a very short `[]byte`. We should probably check the length and reject anything too small to be an IP packet. But the real question is, why did this become a problem now and only on that machine? I wonder if maybe changes to a dependency (perhaps water) cause the short (0-length?) packets to get through...

**Comment by Vort** [comment]
These short packets can be captured using Wireshark, right?

**Comment by Arceliar** [comment]
This should be fixed as of the last release, feel free to reopen if it's not. Though I still have no idea why the short packets were getting through in the first place...
