### ISSUE TITLE
Yggdrasil 0.3.10 connection lost(?) problem

### ISSUE THREAD

**Issue by lam015** [yggdrasil-network/yggdrasil-go#575]
Hello.

There are 2 yggdrasil nodes with the following network configuration:
`<ygg1> --- <gw1> ===== <gw2> --- <ygg2>`

`ygg2` is listening for incoming connections (port is forwarded through `gw2`).
I have `ygg2` in `Peers` list of `ygg1` config (`gw2` really, but port is DNATed to `ygg2`).
Suddenly I could't ping `ygg2` from `ygg1`.
But could be able again after I pinged `ygg1` from `ygg2` (ping ipv6 address of yggdrasil's interface). This happened not once. It's about once a day when I can notice it.

When this happened I saw that yggdrasil's `Coords` changed.
Here is the log:
ygg1:
```
2019-10-16_13-47-59 Coords: [4 25 1 1]
2019-10-16_14-34-08 Coords: [2 1 1]
2019-10-16_14-34-19 Coords: [4 15 2 4 1 1]
2019-10-16_14-34-36 Coords: [4 35 2 20]
```
ygg2:
```
2019-10-16_13-15-32 Coords: [4 25 1 27]
2019-10-16_14-34-07 Coords: [2 1 27]
2019-10-16_14-34-18 Coords: [4 15 2 4 1 27]
2019-10-16_14-34-36 Coords: [2 15 1 1 27]
```

We can see that in 14:34:07 `Coords` of both nodes began to change 3 times.

There is nothing in yggdrasil's log that time (with default log level)

What can it be? Is this because of both nodes are behind NAT?
Do I need to establish some kind of keepalive connection?

Now I'm runnig both nodes with `-logging "info,warn,error,debug"` and there are messages `Admin socket JSON decode error: read unix /var/run/yggdrasil.sock->@: use of closed network connection` after each call of `yggdrasilctl getpeers` or `yggdrasilctl getself`.

**update:**
while writing this issue another connection lost situation happened.
now I can see in `ygg1` log the following (`ygg2` log is empty for the time connection lost happened):
```
окт 16 16:38:36 t1000 yggdrasil[32075]: 2019/10/16 16:38:36 conn=0xc0005605a0 DHT search started: 0xc000094f70
окт 16 16:38:52 t1000 yggdrasil[32075]: 2019/10/16 16:38:52 conn=0xc0001662a0 DHT search started: 0xc000588000
окт 16 16:39:01 t1000 yggdrasil[32075]: 2019/10/16 16:39:01 conn=0xc0001662a0 DHT search started: 0xc000588270
окт 16 16:39:06 t1000 yggdrasil[32075]: 2019/10/16 16:39:06 conn=0xc0001662a0 DHT search started: 0xc00029a270
окт 16 16:39:10 t1000 yggdrasil[32075]: 2019/10/16 16:39:10 conn=0xc0001662a0 DHT search started: 0xc000588000
окт 16 16:39:11 t1000 yggdrasil[32075]: 2019/10/16 16:39:11 conn=0xc0001662a0 DHT search started: 0xc000094dd0
окт 16 16:39:11 t1000 yggdrasil[32075]: 2019/10/16 16:39:11 conn=0xc0001662a0 DHT search started: 0xc00029a270
... <nonstop lines like the above several times a minute>...
```

`Coords` changed this time again (see time 16-38-33)):
ygg1:
```
2019-10-16_14-55-50 Coords: [4 25 1 1]
2019-10-16_16-38-33 Coords: [4 35 2 20]
2019-10-16_16-38-35 Coords: [3 35 2 20]
```

ygg2:
```
2019-10-16_16-38-34 Coords: [3 25 1 27]
```

Thank you.

**Comment by Vort** [comment]
Can you test version `0.3.10-0003`?
It contains the fix #574, which seems to be related to your problem.

**Comment by lam015** [comment]
> Can you test version `0.3.10-0003`?
> It contains the fix #574, which seems to be related to your problem.

thank you, i've started testing 0.3.10-0003

**Comment by lam015** [comment]
Today i had coords change, but connection is alive.
It seems that version 0.3.10-0003 fixes my issue.

`Coords` changes:
2019-10-17_07-08-23 Coords: [3 25 1 1]
2019-10-18_11-15-33 Coords: [2 4 41]
2019-10-18_11-16-19 Coords: [2 22 19 1]

`# journalctl -n10000 -u yggdrasil | grep -v 'Admin socket JSON decode error'`
```
-- Logs begin at Sun 2019-08-25 13:06:51 +05, end at Fri 2019-10-18 11:19:53 +05. --
окт 18 11:06:00 t1000 yggdrasil[9503]: 2019/10/18 11:06:00 conn=0xc0003fa420 DHT search started: 0xc000450270
окт 18 11:07:32 t1000 yggdrasil[9503]: 2019/10/18 11:07:32 conn=0xc0003fa420 DHT search started: 0xc000096b60
окт 18 11:09:55 t1000 yggdrasil[9503]: 2019/10/18 11:09:55 conn=0xc0003fa420 DHT search started: 0xc000450000
окт 18 11:13:20 t1000 yggdrasil[9503]: 2019/10/18 11:13:20 conn=0xc0003fa420 DHT search started: 0xc0002ae270
окт 18 11:15:03 t1000 yggdrasil[9503]: 2019/10/18 11:15:03 conn=0xc0003fa420 DHT search started: 0xc000450270
окт 18 11:15:39 t1000 yggdrasil[9503]: 2019/10/18 11:15:39 conn=0xc0003fa420 DHT search started: 0xc000450270
окт 18 11:15:42 t1000 yggdrasil[9503]: 2019/10/18 11:15:42 conn=0xc00016c5a0 DHT search started: 0xc0002b00d0
окт 18 11:16:35 t1000 yggdrasil[9503]: 2019/10/18 11:16:35 conn=0xc00016c5a0 DHT search started: 0xc0002b00d0
```

and these messages don't spam several times a minute.
thank you.

**Comment by neilalexander** [comment]
Glad this is fixed - closing this issue for now.
