### ISSUE TITLE
armel deb-package

### ISSUE THREAD

**Issue by xaozai** [yggdrasil-network/yggdrasil-go#577]
You have a build for armhf. Could you please also add an build for armel?
I would like a deb package and a repository entry.

This is my CPU:
```
# lscpu
Architecture:          armv5tel
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
CPU max MHz:           1600.0000
CPU min MHz:           533.3330

# cat /proc/cpuinfo
Processor	: Feroceon 88FR131 rev 1 (v5l)
BogoMIPS	: 1589.24
Features	: swp half thumb fastmult edsp 
CPU implementer	: 0x56
CPU architecture: 5TE
CPU variant	: 0x2
CPU part	: 0x131
CPU revision	: 1

Hardware	: Synology 6282 board
Revision	: 0000
Serial		: 0000000000000000

# dpkg --print-architecture
armel

# getconf LONG_BIT
32
```

**Comment by Arceliar** [comment]
I see no reason why we *can't* provide armel builds ([it looks like Go supports it](https://github.com/golang/go/wiki/GoArm)), so marking for v0.3.11. That doesn't necessarily mean we *will* provide armel builds, but we should at least decide whether or not we want to by then, and/or update the deb build code so users can easily build their own (if we don't want to build and host it ourselves for some reason).

**Comment by neilalexander** [comment]
Can you please try the Debian package linked below and let me know if it works? If it does I'll merge #586 and all future builds will be generated for `armel`.

https://2151-115685026-gh.circle-artifacts.com/0/yggdrasil-armel-0.3.10-0012-armel.deb

**Comment by xaozai** [comment]
@neilalexander, yes, I managed to successfully run yggdrasil on Synology NAS ds213air (with the hardware described above).
Thanks a lot!

**Comment by xaozai** [comment]
Only when the process was interrupted (сtrl+с) received an error message:
```
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1b5570]

goroutine 1 [running]:
golang.org/x/net/ipv6.(*payloadHandler).ok(...)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20190813141303-74dc4d7220e7/ipv6/payload.go:23
golang.org/x/net/ipv6.(*PacketConn).Close(0x0, 0x854e4c, 0x1dc734)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20190813141303-74dc4d7220e7/ipv6/endpoint.go:112 +0x18
github.com/yggdrasil-network/yggdrasil-go/src/multicast.(*Multicast).Stop(0x866ce4, 0xe97d8, 0x854e4c)
        /home/circleci/project/src/multicast/multicast.go:92 +0x80
main.(*node).shutdown(0x866700)
        /home/circleci/project/cmd/yggdrasil/main.go:296 +0x38
main.main()
        /home/circleci/project/cmd/yggdrasil/main.go:292 +0xe5c
```
