### ISSUE TITLE
Add include support for yggdrasil.conf

### ISSUE THREAD

**Issue by Nill-R** [yggdrasil-network/yggdrasil-go#579]
Hi! I have feature request.
Plz add include directive for conf-file
E.g for `Peers []` It would be very convenient, something like
```
Peers
[
include /etc/yggdrasil/yggdrasil_peers.list
]
```

I am testing Yggdrasil with 18 servers and I have some troubles with editing 18 conf-files, it is take many time :)

**Comment by KonoromiHimaries** [comment]
use of many at once, will be very usefull
```
include /etc/yggdrasil/yggdrasil_peers_set1.list
include /etc/yggdrasil/yggdrasil_peers_ser2.list
include /etc/yggdrasil/yggdrasil_peers_set3.list
```

**Comment by neilalexander** [comment]
I don't know how we would implement this, as our parsing of the `yggdrasil.conf` file comes from the [hjson/hjson-go](https://github.com/hjson/hjson-go) library. Includes aren't a part of the HJSON specification and I don't see that we would want to fork that library ourselves - it's just another thing to maintain.
