### ISSUE TITLE
AdminListen: none but yggdrasil opens the 9001 port

### ISSUE THREAD

**Issue by xaozai** [yggdrasil-network/yggdrasil-go#581]
yggdrasil.conf:
```
...
# Listen address for admin connections. Default is to listen for local
# connections either on TCP/9001 or a UNIX socket depending on your
# platform. Use this value for yggdrasilctl -endpoint=X. To disable
# the admin socket, use the value "none" instead.
AdminListen: none
...
```

```
# netstat -natup |grep yggdrasil
...
udp6       0      0 :::9001             :::*        4167/yggdrasil
```

**Comment by neilalexander** [comment]
UDP/9001 is the multicast port, not the admin socket. The admin socket operates on TCP/9001.

**Comment by xaozai** [comment]
Ок. Is it possible to disable it? I would not like to use multicast peer discovery.

**Comment by neilalexander** [comment]
Remove all of the entries from `MulticastInterfaces` in the configuration file and multicast will be disabled.

**Comment by xaozai** [comment]
I have nothing written there, but the port still opens.
```
MulticastInterfaces: []
```

**Comment by neilalexander** [comment]
Can you confirm the Yggdrasil version? That sounds like a bug if that's the case.

**Comment by xaozai** [comment]
```
$ yggdrasil -version
Build name: yggdrasil
Build version: 0.3.10
```

**Comment by neilalexander** [comment]
OK, so it looks like what happens is that the socket gets opened regardless, and then we ignore packets from interfaces we don't care about. 

The fix for this is simple - we just need to make sure we don't open the socket if there are no multicast interfaces configured. I should be able to fix that in `develop` later today.

**Comment by xaozai** [comment]
OK. Thanks! )

**Comment by neilalexander** [comment]
Fixed in `develop`.
