### ISSUE TITLE
can't Enable Yggdrasil on iOS

### ISSUE THREAD

**Issue by xaozai** [yggdrasil-network/yggdrasil-go#601]
Yggdrasil v. 0.1 (15)
iOS 12.4.3
iPad mini 2
The application starts, but the "Enable Yggdrasil" switch fails. The switch turns off after a couple of seconds after switching on.
Versions 0.1 (14) worked fine.

**Comment by night-hood** [comment]
Hello, I have the same problem on version 13.2 on iphone 7

**Comment by neilalexander** [comment]
There was a problem in build 0.1 (15) - I withdrew it last night, so you should be able to revert back to 0.1 (14) in the TestFlight app. I’ll try and fix the newer version in the next couple of days.

**Comment by night-hood** [comment]
Yes, good! The problem disappeared in 0.1 (15).

#-----------------------------------------

Matvey Shamatulsky
Russian Federation
Cell: +7 (966) 036 24 21
Skype: Matvey363
5 нояб. 2019 г., 13:43 +0300, Neil Alexander <notifications@github.com>, писал:

**Comment by xaozai** [comment]
v. 0.1 (16) works fine!
Thank you!
