### ISSUE TITLE
Add additional IP data to tun* interfaces upon Yggdrasil start

### ISSUE THREAD

**Issue by Revertron** [yggdrasil-network/yggdrasil-go#602]
Now if I want to add some IPs from 300::/64 network to tun* interface brought up by Yggdrasil I need to issue some commands like `ip addr add 300:111:2222:3333/64 dev tun2`, but if I restart Yggdrasil service, this interface is going down and up again, and I need to issue that command again.

Apart from that, for example on Windows, I would want to set some DNS addresses on that TUN interface. If we are to develop some GUI for Yggdrasil, it will be convenient to set them automatically upon Yggdrasil start.

I propose:
1. Add some config options to set additional IPs on interface.
2. Add some config option to set DNS IPs on interface.

What do you think?

**Comment by neilalexander** [comment]
For extra addresses from the `300::/8` range, it is better to configure those as loopback addresses on the `lo` adapter. That way the address will remain there even if Yggdrasil goes up and down, and  it shouldn't cause anomalies with source address selection for outgoing connections.

For DNS, at the moment I am not entirely sure how we want to handle this. I know that @Arceliar had some thoughts about a built-in resolver for public keys but I don't feel terribly comfortable updating environment-wide DNS options.

**Comment by neilalexander** [comment]
I'm going to close this for now as I don't think this is something we want to get into right now. We may revisit this in the future.
