### ISSUE TITLE
Add checking or fix MTU bounds for TUN/TAP interface

### ISSUE THREAD

**Issue by Revertron** [yggdrasil-network/yggdrasil-go#603]
Currently, if I set MTU to 65536, there is no error message and Yggdrasil starts as it is okay. But the traffic doesn't go through TAP any way. Done so by error on Windows 10 and was very puzzled.

**Comment by Vort** [comment]
Also default value for Windows should be lowered to 65521.
I have asked for it months ago.

**Comment by neilalexander** [comment]
@Revertron @Vort 

Please test `yggdrasil-develop-0.3.11-0032` - this should correctly handle the MTU bounds problems and reduce the TAP MTU down as needed for ethernet headers (upper limit of `65521`).

**Comment by Vort** [comment]
I don't completely understand what you made.
Yggdrasil generates config with `IfMTU: 65535` and then shows that it is out of the limits (why not make it correct right from the start?).
And are you sure that `65535` is impossible value for correctly implemented TAP driver?

So this version works, but I'm not sure that handling of MTU this way is correct.

**Comment by neilalexander** [comment]
The generated config at this stage does still refer to `65535`, but that's something we will improve in the next release. We're frozen now for changes for v0.3.12 that aren't showstoppers.

On Windows with the OpenVPN TAP driver all bets seem to be off, but I seem get more than enough reports from people that an MTU of 65535 on Windows results in some issues.

In the future, the configuration will produce a hard error at startup if the value is incorrect and the MTU will be adjusted correctly in the generated config. It's also on my radar to support WinTun instead (#394) so hopefully that will be far better than this trash OpenVPN driver.

**Comment by Vort** [comment]
So if, theoretically, WinTun will have support for `65535` MTU, you will make changes for limits again?
Or that can not happen?

**Comment by neilalexander** [comment]
The limit is still 65535 for TUN devices. It's only TAP devices for which the MTU is adjusted.

**Comment by Revertron** [comment]
> Please test `yggdrasil-develop-0.3.11-0032` - this should correctly handle the MTU bounds problems and reduce the TAP MTU down as needed for ethernet headers (upper limit of `65521`).

Works perfectly for me.

**Comment by neilalexander** [comment]
TAP devices are no longer supported so the bulk of this is no longer relevant. For TUN, we will adjust MTU accordingly based on the OS and maximum packet header size (v0.4).
