### ISSUE TITLE
AllowedEncryptionPublicKeys for outgoing connections

### ISSUE THREAD

**Issue by wizeman** [yggdrasil-network/yggdrasil-go#617]
The option `AllowedEncryptionPublicKeys` only restricts incoming connections.

It would be great to have an option for `AllowedEncryptionPublicKeys` to also apply to outgoing connections.

This would be useful in case you want to make sure that you are only connecting to a trusted node, e.g., if you're concerned that some other node can perform traffic analysis on you or if you wish to run a private network, disconnected from the Yggdrasil public network.

**Comment by neilalexander** [comment]
Not planned as v0.5 will allow per-peer/per-listener/per-multicast interface passwords instead.
