### ISSUE TITLE
Creation of yggdrasil.conf is failing when msi package is installing

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#623]
When Yggdrasil is installed with .msi package, `yggdrasil.conf` is created empty (0 bytes file).
Also appearing of black console window during installation is not a good thing. It should be possible to do things cleanly.

Version tested: `yggdrasil-develop-0.3.12-0042-x64.msi`
OS: Windows 7 SP1 x64

**Comment by Revertron** [comment]
Did it ask for Administrator privileges? It doesn't ask them on my PC, I think it is the root of issue.

**Comment by neilalexander** [comment]
So I did see this happen once when I was creating the MSI, but I was never able to reproduce it.

The task that creates the config should run as `Impersonate="no" Execute="deferred"`, so it should get deferred to a Windows Installer service running as `LOCAL SYSTEM`. In practice this is what I was seeing on Windows Server 2016.

However it may well be permissions related, and in that case I am wondering whether it might be better instead to move the `yggdrasil.conf` into `C:\ProgramData` or similar.

**Comment by Vort** [comment]
It may be that .bat file is executed before .exe is created.
Without permissions even 0 bytes file should not be created.

**Comment by neilalexander** [comment]
Please test this build 43:

https://ci.appveyor.com/project/neilalexander/yggdrasil-go/builds/29204055/artifacts

Three changes in the MSI:

1. Config is now in `%ALLUSERSPROFILE%` instead of `Program Files`
1. MSI installation scope is now specified as per-machine (should help some elevation problems)
1. The update config script is now set to impersonate elevated

**Comment by Vort** [comment]
My guess about non-existent .exe file was wrong.
The problem is that yggdrasil.exe can't generate config while it is running from system account.
Redirection works fine, there are just nothing to redirect.
Of course, I can be wrong yet again.

To reproduce problem, you can use [PsExec64.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) software:
`PsExec64.exe -w "c:\Program Files\Yggdrasil" -i -s "c:\Program Files\Yggdrasil\yggdrasil.exe" -genconf > "c:\Program Files\Yggdrasil\yggdrasil.conf"`

**Comment by Vort** [comment]
Since `yggdrasil.exe` is now executing from current user account, config generation works fine.
But question why it was failing, when was executed from system account, is open.
