### ISSUE TITLE
Line endings of config file on Windows 

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#626]
On Windows platform, `yggdrasil.exe -genconf > yggdrasil.conf` generates file with only LF (0x0A) characters, while it is traditional for Windows software to expect CR+LF (0x0D 0x0A) combination instead.
For example, it confuses default text editor of Windows 7, `notepad.exe`:
![yggnp](https://user-images.githubusercontent.com/1242858/69886779-5112f480-12ec-11ea-81aa-3e7084c86ba6.png)
It would be nice to fix this problem somehow.

**Comment by neilalexander** [comment]
I have a feeling that this is actually not Yggdrasil at all, but it's to do with the pipe redirection. From what I recall, the behaviour is different in `cmd.exe` (which is what we use in the `.msi`) to what `powershell.exe` does (which spits out CRLF with a UTF-16 byte-order marking).

Can you confirm that there's a difference using `-genconf > file.txt` in both `cmd.exe` and `powershell.exe`?

**Comment by Vort** [comment]
The behaviour is different because PowerShell converts data. Here is the topic with some explanations: [File redirection is about saving the content of a binary stream to a file, while the PS redirection is to serialize objects into files.](https://github.com/PowerShell/PowerShell/issues/2145#issuecomment-243863444)
[The second command should give System.Object[]. That is, before PowerShell ever writes the file, the stream output by git is already lost.](https://github.com/PowerShell/PowerShell/issues/2145#issuecomment-243873278)
So `.\yggdrasil.exe -genconf > yggdrasil.conf` really converts output to UTF-16LE/CR+LF.
But if you type `Start-Process -FilePath "yggdrasil.exe" -ArgumentList "-genconf" -RedirectStandardOutput "yggdrasil.conf"`, then no conversion will be applied and output will be equivalent to one from `cmd`.

**Comment by McL0v1n** [comment]
So @Vort, just to clarify:
In powershell it works but in cmd it does not?

If true, then @neilalexander maybe we just specify in the windows directions to use powershell instead of cmd?

**Comment by Vort** [comment]
@McL0v1n that is wrong approach. Yggdrasil should create correct output, not other program should fix it instead of Yggdrasil.

**Comment by McL0v1n** [comment]
Its not the other program "fixing" it, its just using the correct program for the job. In fact, powershell is installed by default on all windows machines.

-------- Original Message --------

**Comment by Vort** [comment]
> Its not the other program "fixing" it, its just using the correct program for the job

You do not need a program to use a program.
That unix-style overcomplication is unnecessary here.

**Comment by Vort** [comment]
>  just using the correct program for the job

This is called "hacks". Which is a sign of bad quality software.

> Its not the other program "fixing"

Taking wrong input and converting it to less wrong output is exactly what is meant by fixing.
It is surprising how it is possible to misunderstand this.

**Comment by neilalexander** [comment]
I have opened a PR with the upstream library to address this since this really feels like something that should be fixed by sane defaults.

If accepted then I will update our `go.mod` file to point to the new commit. If rejected then I will fix it in Yggdrasil directly.

**Comment by neilalexander** [comment]
Note to self: follow up on this.

**Comment by neilalexander** [comment]
AFAIK this is resolved and Yggdrasil can cope with the various messy formats that Windows spits out already (i.e. UTF-16, CRLF line endings).
