### ISSUE TITLE
Upgrading of msi package removes Wintun driver

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#627]
Steps to reproduce:
1. Uninstall Yggdrasil, remove config and log files.
2. Run `yggdrasil-develop-0.3.12-0043-x64.msi`.
3. Run `yggdrasil-develop-0.3.12-0046-x64.msi`.
4. Look at the log file `c:\ProgramData\Yggdrasil\yggdrasil.log`, you will see there the line:
`2019/11/30 09:00:54 An error occurred starting TUN/TAP: Error creating interface: No driver for device "Wintun" installed`

By the way, uninstallation is having some problems too.
After its successful finish, I still see `wintun.sys` file inside `C:\Windows\System32\drivers`.

OS: Windows 7 SP1 x64

**Comment by neilalexander** [comment]
I did notice the problem with upgrading—if you “Repair” the MSI after this happens, it seems to come back fine. 

I’m not sure if this is something that is broken in the Wintun `.msm` or if it’s something wrong in my `.msi` build. I’ll try and look at it more closely later.

**Comment by Vort** [comment]
There are no more such problem with upgrading from `yggdrasil-develop-0.3.12-0058-x64.msi` to `yggdrasil-develop-0.3.12-0060-x64.msi`. Thanks.
