### ISSUE TITLE
Parts rewritten in Rust, call them from Go

### ISSUE THREAD

**Issue by DaniellMesquita** [yggdrasil-network/yggdrasil-go#632]
Inspired by this article: https://ipfs.io/ipfs/QmYWefqYrMxcwu6BwZZ5hc1Qy6iT7tfMBPBPzUixF4PrBB/
A good step before creating a Rust version of Yggdrasil, like go-ipfs haves its Rust versions.

**Comment by chpio** [comment]
this repo is called yggdrasil-*go* for a reason so i think this should be closed because it's off topic also no one wants to touch rust if there's golang

**Comment by neilalexander** [comment]
At this point it is better for this repository to remain in Go and for us to not try to mix Rust in with it. A future Rust implementation is possible.
