### ISSUE TITLE
Disable ip autoconfiguration

### ISSUE THREAD

**Issue by ne-vlezay80** [yggdrasil-network/yggdrasil-go#640]
Please add disable ip autoconfiguration option with yggdrasil.

**Comment by neilalexander** [comment]
Can you please elaborate more on the request and/or the problem you are trying to solve here?

**Comment by ne-vlezay80** [comment]
Just make sure that when you start Yggdrasil the IP address is not assigned to the interface. So that you can simply register the route on the interim.

**Comment by zhoreeq** [comment]
@ne-vlezay80 Is it related to #639 ? Seems like you want yggdrasil to create tun interface, but to set IP address manually?

**Comment by neilalexander** [comment]
Not clear there's good justification for this at this time.
