### ISSUE TITLE
Reduce bandwidth usage

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#65]
General issue to monitor bandwidth usage and figure out how to reduce it.

Mobile nodes, or anything battery-powered (e.g. sensor networks) need to keep idle bandwidth usage as low as reasonably possible.

The main consumers of bandwidth for idle nodes are:
1. Keep-alive and spanning tree traffic, which happens per peer.
2. Idle DHT maintenance traffic.
3. Handling other people's DHT searches.

We should find ways of keeping all of these to a minimum. A few thoughts:

For 1, we can probably throttle back idle traffic on idle stable links, so we'd tend to only send updates when the tree updates the root timestamp. We could do this by progressively increasing the time between announcements (by 1 second per announcement, until some max, maybe 30 seconds or so). We would need to reset the time if the coords change, and/or require acknowledgements of some kind when we start relaying traffic that isn't part of the spanning tree (to make sure we're not sending data or DHT traffic into the void).

For 2, I think the DHT's correctness should be insensitive to timing, so we can probably throttle things back if the network is stable (a node would reset if its coords change, maybe?). We should wait and see what affect recent patches have had before we do anything here. Ideally, a node that isn't trying to send any traffic would participate in the bare minimum amount of DHT activity needed to keep the rest of the network running.

For 3, we need to be careful about how we change things, to make sure we don't accidentally cause blackholes. Ideally, the less active a node is, the fewer other nodes should have that node in its bucket (so it would mainly need to deal with traffic related to its keyspace neighbors), so this may interact with 2 in weird ways. It would also be good if the DHT was caching--if lots of nodes are looking up X, then X should appear on lots of DHT nodes (the ones that looked up X, and maybe the ones that were involved in looking up X). I'm not sure how well caching works in practice for DHTs, so that needs some research before deciding whether or not to try it.

All of these things have tradeoffs between reaction/convergence time and idle bandwidth usage. The current implementation mostly uses hard coded and arbitrary timeouts, so there's hopefully some room for improvement here.

**Comment by neilalexander** [comment]
#64 potentially goes some way to reducing traffic for point 2 by dropping some DHT rumour mill pings down to a minute instead of seconds, although right now it does not adjust dynamically. Once we are happy that the network can function with a higher interval, an algorithm should replace the hard-coded time.

**Comment by Arceliar** [comment]
It would also make sense to eventually switch from a recursive DHT search algorithm to an iterative one. All the machinery is in place at the protocol level (it's just repeated DHT lookups) but the search code needs to be modified to do that. Ideally, we'd optimistically try to send a recursive lookup when we start a search, and then maybe trigger an iterative lookup instead of sending another recursive lookup for the same search (or maybe start one immediately in the background, and cancel it if the recursive search succeeds). That would give us the low latency of recursive lookups, and the reliability of iterative lookups, but switching to only iterative is also an option I guess.

I started with recursive since they're more fragile--depending on the implementation, iterative searches can hide DHT blackholes in small networks, which is *exactly* the thing I'm trying to avoid--but in the long term we probably want to switch (after we're confident that the bootstrapping works and the DHT won't diverge to a state with blackhols). Iterative lookups can deal with node failure by routing around unresponsive nodes, so keeping the DHT up to date becomes less important, and may let us throttle back the passive maintenance traffic more than we could with only recursive lookups.

**Comment by Arceliar** [comment]
Thinking about this a little more...

In a perfect world, the DHT would have no idle maintenance traffic at all. Instead, we would use our bandwidth on lookups, and make sure that the lookups take care of whatever kind of maintenance is needed on their own. That's not possible in general, since nodes need to tell someone about themselves for incoming connections to work, so it runs into a bootstrap paradox. However, there's 2 parts to the maintenance routine: one pings nodes to make sure they're still alive, and the other cycles over buckets to bootstrap and plug holes.

It *may* be possible to make the keep-alive traffic throttle back completely, by marking nodes a dirty when we use them for a search, and then only pinging the least-recently-responded dirty node. I think I see how to do it safely in the current recursive search setup, but I need to think more about how it would work with iterative searches, to make sure it won't all fall apart if the recursive search packets stopped. What I'm not sure of is what kind of delay it will introduce, where searches fail but trigger a maintenance lookup, and then later searches succeed. That would add additional delay to session startup, compared to if we proactively maintain a working table with keep-alive traffic.

The bucket-cyclic bootstrap traffic is possibly doing more than it needs to. I wonder if, instead of cycling over all buckets, it may be sufficient to limit the range. I think it may still do the right thing if we start by targeting the first empty bucket, and stop with the empty bucket immediately after the last non-empty bucket. That would still plug any holes that appear (which currently relies on the periodic traffic mentioned above to flush dead nodes in create holes, so it would be sensitive to any changes there), and I think it *may* still bootstrap successfully (it's not *obviously* bad, but there may be higher order effects that I haven't thought of). That would give the (currently 1 minute) delay between re-pinging nodes a better chance to throttle things down in idle networks. I guess in that case we should probably change that delay dynamically if we know that something about the DHT state has changed (e.g. removed a node due to timeout), so we don't sit idle for up to 1 minute before even trying to fix it, assuming this approach works at all.

In either case, there could be some kind of pathelogical feedback, where congestion causes packet losses, those losses cause nodes to be pinged more (more congestion), continued lack of response causes them to drop, then trying to plug the DHT hole leads to more pings of other nodes. Feedback loops like this are why I've tried to keep things predictable with periodic proactive maintenance instead of reactive stuff, out of a fear that problems will compound exponentially under real-world churn if something reactive is used. But throttling the DHT through the rumor mill *may* be sufficient to avoid this, or at least mitigate it enough to make the badness scale less aggressively.

**Comment by Arceliar** [comment]
There's an alternative to the kad-like DHT that won't work, as far as I can tell, but is worth mentioning.

Basically, replace the current DHT with something that does a CIDR-like NodeID->coord map, where we route a lookup packet for node A to a set of coords for some node B, who is then responsible for knowing how to contact A. The problem is, a stateless mapping function doesn't balance this responsibility across the coords occupied by real nodes, so a small number of nodes necessarily get stuck being responsible for answering lookups for a large fraction of the network.

If the map is stateful, then *maybe* we can make it so this state is transitive (you care about the same information as your parent and/or neighbors), which would be a huge win compared to the current DHT. The problem is, I see no obvious stateful lookup function that both balances the lookup tree and doesn't become sensitive to *global* state, where every node join/leave disrupts the entire network (using far more resources than the current DHT).

**Comment by Arceliar** [comment]
The changes to switch message formats and the addition of DHT throttling in v0.2 should both help with this.

**Comment by Arceliar** [comment]
Moving to v0.4, since we decided to keep v0.3 backwards compatible at the protocol level, and reducing keep-alive traffic would require changing some things about how the TCP links work. We can do further work reducing idle DHT traffic after the v0.3 release, when we see how things look in the full network.

**Comment by neilalexander** [comment]
I think this has been reasonably done in v0.4. Can reopen later if needed.
