### ISSUE TITLE
Winlogon.exe not found

### ISSUE THREAD

**Issue by cwchristerw** [yggdrasil-network/yggdrasil-go#656]
An error occurred starting TUN/TAP: unable to find winlogon.exe process

Happens when running newest Windows exe file from https://yggdrasil-network.github.io/builds.html

**Comment by Vort** [comment]
Did you read that 0.3.13 uses different driver?
It is not one-click process to upgrade from 0.3.12 to 0.3.13 for Windows users.
TAP driver should be removed, TUN driver should be installed with msi package:
[yggdrasil-develop-0.3.13-x64.msi](https://ci.appveyor.com/api/buildjobs/9oj4ck2cibxl3a7i/artifacts/yggdrasil-develop-0.3.13-x64.msi)
and config file contents from 0.3.12 should be merged into 0.3.13.
_(it is good to make backups before upgrading)_

**Comment by cwchristerw** [comment]
I think it should not build exe file if it cannot be runned separately or there should be guide to use it. MSI Installer doesnt allow currently path changes #657

**Comment by Vort** [comment]
.exe file is useful for upgrading. Especially if you use non-standard installation path.

**Comment by neilalexander** [comment]
AFAIK this is not a problem with the Wintun driver.
