### ISSUE TITLE
dropping privileges or running as a regular user

### ISSUE THREAD

**Issue by i0x71** [yggdrasil-network/yggdrasil-go#659]
Are there any docs out there that explain how to drop privileges or run yggdrasil as a regular user ?

Thanks

**Comment by zhoreeq** [comment]
It can run as a regular user, but TUN interface has to be disabled and a path for admin socket must be changed. 

```
  AdminListen: unix:///tmp/yggdrasil.sock
  IfName: none
```

**Comment by neilalexander** [comment]
On Linux you can run as an unprivileged user by giving Yggdrasil the `CAP_NET_ADMIN` and `CAP_NET_RAW` privileges. See [man 7 capabilities](https://linux.die.net/man/7/capabilities) for more info.

**Comment by i0x71** [comment]
Thanks, for those interested this is the command to do it on linux
setcap cap_net_admin,cap_net_raw+iep **/opt/yg/yg**

**Comment by zhoreeq** [comment]
@neilalexander For some reason it doesn't work with systemd unit. The process crashes if run by unprivileged user, because the capabilities aren't set. Even though it sets capabilities for the openvpn unit correctly on the same box.

Tested on Raspbian and Debian 10
```
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by neilalexander** [comment]
Interesting, we do have `CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW` in the service file for the Debian packages. Would need to test it a bit further.

**Comment by zhoreeq** [comment]
All right, still no idea what happened, but after full purge and reinstall it works fine. It runs with `User=nobody` well.

**Comment by neilalexander** [comment]
Glad to hear it!
