### ISSUE TITLE
IfTAPMode seems to be ignored on 0.3.14 on OpenBSD 6.6.

### ISSUE THREAD

**Issue by slancio** [yggdrasil-network/yggdrasil-go#677]
Hi.  I'm trying to use the latest build on OpenBSD and seeing the Platform Notes and related github issue am trying to use yggdrasil with /dev/tap0. I have that IfName and IfTAPMode set to true in my config file.

On startup I get a panic saying that Interface name must be tun[0-9]* and the gocode seems to be trying to use a tun adapter.

For giggles, I tried the HJSON/JSON normalisation options and it seems that the IfTAPMode config line gets stripped from my configuration entirely, so I think the line's being ignored.

My OpenBSD system is very vanilla but patched.

**Comment by Mikaela** [comment]
I guess you are looking at outdated documentation as TAP mode has been removed in `[0.3.13] - 2020-02-21`

* https://yggdrasil-network.github.io/changelog.html#0313---2020-02-21

**Comment by McL0v1n** [comment]
It looks like it was generated in the conf in latest OpenBSD build:

https://3008-115685026-gh.circle-artifacts.com/0/yggdrasil-0.3.14-openbsd-amd64

**Comment by slancio** [comment]
Ahh okay.  I guess that marks the issue as written a non-issue, but this is still non-working for me on OpenBSD, as this doesn't seem to work with /dev/tun[0-9]* either.  I'm sure there's some piece I'm missing to get that to work.

**Comment by McL0v1n** [comment]
@neilalexander I think this has to do with the switch to wireguard, is that correct?

**Comment by neilalexander** [comment]
It's related to the switch to the [Wireguard TUN package](https://godoc.org/golang.zx2c4.com/wireguard/tun), yes.

**Comment by McL0v1n** [comment]
Then this isn't a bug anymore, its deprecated functionality

**Comment by neilalexander** [comment]
It's mostly still a bug if there is something wrong with the generated OpenBSD config, but it's been a while since I have tested Ygg with OpenBSD to verify that.

**Comment by McL0v1n** [comment]
I thought there was an issue with wireguard not available on BSD yet?

**Comment by neilalexander** [comment]
The TUN package doesn't support NetBSD, but it does have support for FreeBSD and OpenBSD: https://git.zx2c4.com/wireguard-go/tree/tun

**Comment by McL0v1n** [comment]
Understood. I must have read that wrong in the release notes then.

**Comment by z3bra** [comment]
Now the Yggdrasil switched to using the Wireguard TUN package, OpenBSD can use the TUN mode, and it works. Unfortunately the package doesn't seem to be able to change the MTU while running. See [my comment](https://github.com/yggdrasil-network/yggdrasil-go/issues/31#issuecomment-682048573) on #31 to get it to work.
