### ISSUE TITLE
yggdrasil in termux on android errors

### ISSUE THREAD

**Issue by SergeyDjam** [yggdrasil-network/yggdrasil-go#680]
1. setup termux
2. pkg update && pkg install golang
3. wget release 0.3.14 
4. tar -xf yggdrasil
5. cd yggdrasil && ./build. Its all OK
6. ./yggdrasil -genconf > yggdrasil.conf OK
7. 
```
./yggdrasil -useconffile ~/yggdrasil.conf
2020/04/21 08:36:55 Build name: yggdrasil
2020/04/21 08:36:55 Starting up...
2020/04/21 08:36:55 Starting switch
2020/04/21 08:36:55 Starting router
2020/04/21 08:36:55 Startup complete
2020/04/21 08:36:55 Starting multicast module
panic: no such file or directory

goroutine 33 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0x400008b6c0, 0x400009c778, 0x4, 0x40000d8210, 0x28, 0x40000dffff, 0x28, 0x99d16d36a03d0122)
        /data/data/com.termux/files/home/yggdrasil/yggdrasil-go-0.3.14/src/tuntap/tun_linux.go:19 +0x1d4
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start(0x400008b6c0, 0x0, 0x0)
        /data/data/com.termux/files/home/yggdrasil/yggdrasil-go-0.3.14/src/tuntap/tun.go:165 +0x320
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start.func1()
        /data/data/com.termux/files/home/yggdrasil/yggdrasil-go-0.3.14/src/tuntap/tun.go:138 +0x28
github.com/Arceliar/phony.Block.func1()
        /data/data/com.termux/files/home/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:89 +0x28
github.com/Arceliar/phony.(*Inbox).run(0x400008b828)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:104 +0x9c
created by github.com/Arceliar/phony.(*Inbox).restart
        /data/data/com.termux/files/home/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:130 +0x34
```

**Comment by neilalexander** [comment]
Android has the TUN module at `/dev/tun` rather than `/dev/net/tun`, so can you try doing something like `mkdir /dev/net; ln -s /dev/tun /dev/net/tun` and giving it another go?

**Comment by SergeyDjam** [comment]
> Android has the TUN module at `/dev/tun` rather than `/dev/net/tun`, so can you try doing something like `mkdir /dev/net; ln -s /dev/tun /dev/net/tun` and giving it another go?

```
mkdir /dev/net
mkdir: cannot create directory ‘/dev/net’: Permission denied
```
```
su
No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.
```

but wireguard/openvpn/orbot/netguard up tun interface whithout root

**Comment by SergeyDjam** [comment]
Maybe i am can turn off the multicast somehow?

**Comment by zhoreeq** [comment]
@SergeyDjam 
`IfName: none`, but this way you won't be able to use IP addresses, only relay traffic

By the way, termux su is installed with package `tsu` or `tsudo`, if you don't have it already.

**Comment by SergeyDjam** [comment]
> @SergeyDjam Try `IfName: none`, but this way you won't be able to use IP addresses, only relay traffic for other nodes.
> 
> By the way, termux su is installed with package `tsu`, if you don't have it already.

```
tsu
/data/data/com.termux/files/usr/bin/tsu: 144: exec: : Permission denied
```

**Comment by Saiv46** [comment]
Use `tsudo` command

**Comment by averyanalex** [comment]
"But wireguard/openvpn/orbot/netguard up tun interface whithout root". I think they use built in Android API to set up VPN connection. (UI appears and ask for connect VPN).

**Comment by neilalexander** [comment]
Closing as out-of-date.

**Comment by b8kings0ga** [comment]
still thinking of this now, I guess the only way we can get around it is using "Advertising a Prefix" from a "routing" device?

**Comment by envsh** [comment]
2026/07/07 06:00:37 Build version: 0.5.14
2026/07/07 06:00:37 Admin socket failed to listen: listen unix /var/run/yggdrasil/yggdrasil.sock: bind: no such file or directory

**Comment by vindicatorr** [comment]
Regarding the `bind: no such file or directory` for the socket, I can at least speak of that from experience that it just isn't created.
So find a path that exists and `$ touch /<pathTo>/<file>.sock`, and set `AdminListen: unix://<pathTo>/<file>.sock` in your config.
Then any time you use yggdrasilctl, just set the argument: `-endpoint "unix://<pathTo>/<file>.sock"`.
