### ISSUE TITLE
Extend config with modules

### ISSUE THREAD

**Issue by zhoreeq** [yggdrasil-network/yggdrasil-go#681]
Suppose someone makes a custom client for Yggdrasil with extra modules, i.e. sending RA in a local network, automatic Internet peer choice, and so on.

What would be the best approach for extending Yggdrasil's config file with new entries, but not changing any original Yggdrasil's codebase?

**Comment by neilalexander** [comment]
If you are using the `yggdrasil` package in another project then the best way would probably be to embed:
```
import "github.com/yggdrasil-network/yggdrasil-go/src/config"

type MyRAAdvertiser struct {
  config.NodeConfig

  MyRASetting bool
  MyOtherRASetting string
}
```

**Comment by zhoreeq** [comment]
Oh, I see. It can be like a proxy object, lol.
