### ISSUE TITLE
Getting through a firewall

### ISSUE THREAD

**Issue by poopingpenis** [yggdrasil-network/yggdrasil-go#694]
I'm running Yggdrasil through a Raspberry Pi and UFW.

When the firewall is on it doesn't get any local peers, however. I've allowed access to UDP port 9001 from anywhere but have had no luck. Here's my relevant config settings:

```
  # Listen addresses for incoming connections. You will need to add
  # listeners in order to accept incoming peerings from non-local nodes.
  # Multicast peer discovery will work regardless of any listeners set
  # here. Each listener should be specified in URI format as above, e.g.
  # tcp://0.0.0.0:0 or tcp://[::]:0 to listen on all interfaces.
  Listen: []

  # Listen address for admin connections. Default is to listen for local
  # connections either on TCP/9001 or a UNIX socket depending on your
  # platform. Use this value for yggdrasilctl -endpoint=X. To disable
  # the admin socket, use the value "none" instead.
  AdminListen: unix:///var/run/yggdrasil.sock
```

How can I fix this?

Edit: Oh shit it's TCP. Well it's still running through a UNIX socket instead on Yggdrasil, and I don't know how to let through multicast, how can I change that?

**Comment by neilalexander** [comment]
Multicast beacons are sent and received on the IPv6 multicast address `ff02::114` using UDP port 9001. If you want automatic peering to work then you need to allow this traffic.

In addition to that, each multicast interface that is enabled *also* gets a TCP peering socket on the interface's IPv6 link local address. The `LinkLocalTCPPort` controls this - the default setting of `0` selects any available port but you can change it to a static port number. You will then be able to add a firewall rule to allow traffic on that port.

If you want to listen on a *specific* (non-link-local) address and port (either IPv4 or IPv6) then you need to enter a `Listen` line like:
- `tcp://0.0.0.0:12345` to listen TCP on any IPv4 address on port 12345
- `tls://0.0.0.0:12345` to listen TCP+TLS on any IPv4 address on port 12345
- `tcp://[::]:12345` to listen TCP on any IPv6 address on port 12345
- `tls://[::]:12345` to listen TCP+TLS on any IPv6 address on port 12345
... or similar.

**Comment by poopingpenis** [comment]
Thanks a lot, got it fixed. :)
