### ISSUE TITLE
Admin API: public peer persists after calling removePeer

### ISSUE THREAD

**Issue by zhoreeq** [yggdrasil-network/yggdrasil-go#699]
How to reproduce:

On a system with no public peers configured, first add a peer, then remove it.

    yggdrasilctl addPeer uri=a.b.c.d:xyz
    yggdrasilctl removePeer port=1

At first `getPeers` correctly shows nothing wrong, and the network stops working. But the removed peer returns after ~20 seconds and Yggdrasil network starts to work again.

Yggdrasil v0.3.14 on Debian 10

**Comment by zhoreeq** [comment]
Looks like peer is being disconnected by the Admin API, but not removed from the config file. So the `_addPeerLoop` adds them again?

**Comment by neilalexander** [comment]
Ideally we would have `disconnectPeer` and `removePeer` as separate to solve this problem.
