### ISSUE TITLE
[future] peer never added to switchpeers

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#710]
Two of my local machines are failing to peer, both on `future`. Node A looks normal. Node B has a peer entry for node A, but no switchpeer.

No idea how to reliably reproduce or debug. My best guess is maybe the switchpeer exists, but `blocked` is set for that peer in the switch, and isn't properly resetting for whatever reason.

**Comment by Arceliar** [comment]
If it's really caused by `blocked` being set in the switch, then it's probably caused by some sort of race between when `blockPeer` is called and `unblockPeer` is called, possibly even involving a peer being removed and then a new peer being added before the switch realizes the first one was removed (so the link and switch's view of whether or not the peer is blocked becomes out of sync).

The lazy fix would be for the link to stop tracking whether or not the peer is blocked, and just *always* have the link notify the switch when we read a packet. Not 100% sure that doesn't race in other ways though (I need to review the horrible link state machine).

**Comment by neilalexander** [comment]
Closing as no longer relevant with v0.4.
