### ISSUE TITLE
Finalization Yggdrasil leads to extremely high CPU consumption - possible infinite looping

### ISSUE THREAD

**Issue by vikulin** [yggdrasil-network/yggdrasil-go#720]
Finalization Yggdrasil leads to extremely high CPU consumption - possible infinite looping.

Branch: master, fork: https://github.com/vikulin/yggdrasil-extras

The issue found while debug of Yggdrasil Android app. Also it was started after several users complained that switch off button causes high CPU consumption. As result I did profile debug and found following:
The CPU starts high load right after Yggdrasil().Stop() call which is modified as following:

```
// Stop the mobile Yggdrasil instance
func (m *Yggdrasil) Stop() {
	logger := log.New(m.log, "", 0)
	logger.EnableLevel("info")
	logger.Infof("Stop the mobile Yggdrasil instance %s", "")
	m.admin.Stop()
	m.multicast.Stop()
	m.dummy.Stop()
	m.core.Stop()
}
```

The screenshot shows different states before and after the Stop() method invocation in line 256:

**Before Stop()**
![Screenshot from 2020-07-04 09-43-12](https://user-images.githubusercontent.com/743622/86571524-3b4c6880-bf7a-11ea-8e1e-6250d3cb1fe6.png)

**After Stop()**
![Screenshot from 2020-07-04 09-43-35](https://user-images.githubusercontent.com/743622/86571536-40111c80-bf7a-11ea-8b06-1e9f1589ed18.png)

I concern that the method Stop() runs into infinite looping somewhere within child Stop() calls.

**Comment by Vort** [comment]
Maybe related: if Yggdrasil runs several days long, then stopping takes too much time:
```
2020/06/23 16:05:43 Starting up...
...
2020/07/04 10:56:01 Stopping multicast module
2020/07/04 10:56:01 Error reading TUN: file already closed
2020/07/04 10:56:11 Stopping...
...
2020/07/04 10:56:12 Stopped
```

**Comment by vikulin** [comment]
Commenting out m.admin.Stop() solved the issue, continue investigation.

```
// Stop the mobile Yggdrasil instance
func (m *Yggdrasil) Stop() {
	logger := log.New(m.log, "", 0)
	logger.EnableLevel("info")
	logger.Infof("Stop the mobile Yggdrasil instance %s", "")
	//m.admin.Stop()
	m.multicast.Stop()
	m.dummy.Stop()
	m.core.Stop()
}
```

**Comment by vikulin** [comment]
Found second Stop() method with the same issue: m.dummy.Stop(). I thing this is the end of my research.

**Comment by neilalexander** [comment]
Closing as out-of-date.
