### ISSUE TITLE
Dont accept incoming connection

### ISSUE THREAD

**Issue by averyanalex** [yggdrasil-network/yggdrasil-go#723]
Hello. I setup public node, and when enter [http://[200:9735:710e:c386:6b1a:6753:756d:506c]/](http://[200:9735:710e:c386:6b1a:6753:756d:506c]/) in computer browser, see Apache page. IP of my computer is 201:a814:62cb:212b:8eb6:d677:96a8:2539. It pings from VPS (my public node) "64 bytes from 201:a814:62cb:212b:8eb6:d677:96a8:2539: icmp_seq=148 ttl=128 time=106 ms" and from local cmd "Response from 201:a814:62cb:212b:8eb6:d677:96a8:2539: time<1ms". I setup nginx, localhost and 192.168.1.45 from Android opens "Welcome to nginx!". But [http://[201:a814:62cb:212b:8eb6:d677:96a8:2539]/](http://[201:a814:62cb:212b:8eb6:d677:96a8:2539]/) dont want to connect, from PC, and from VPS (lynx console browser) Firewall disabled

**Comment by neilalexander** [comment]
Is your nginx configured to listen on IPv6? e.g. `Listen [::]:80`

This is probably not an Yggdrasil problem if ping is working.

**Comment by averyanalex** [comment]
Than you very much! But I am writing russian connection guide "how to play minecraft with friends in different networks", but I think there is the same issue. I think you dont know, but, maybe, you know, how to configure minecraft local multiplayer to listen IPv6?

**Comment by averyanalex** [comment]
When IPv4 enabled, mc start internal server on IPv4. I will provide instruction with vanilla server (configuration, server-ip=[::])
