### ISSUE TITLE
COPR repository may need updating

### ISSUE THREAD

**Issue by yujiri8** [yggdrasil-network/yggdrasil-go#724]
Today I tried to install Yggdrasil from [the COPR repository](https://copr.fedorainfracloud.org/coprs/leisteth/yggdrasil/) on a Fedora 32 Digital Ocean droplet. I followed [the instructions](https://yggdrasil-network.github.io/installation-linux-rpm.html) and when running `dnf copr enable leisteth/yggdrasil`, got an error saying that I couldn't enable it because it had no builds. I was able to resolve it by downloading the `.repo` file manually.

Since I'm new to Fedora, I won't be surprised if it's something I did wrong. If not I suspect it's because the repo was made for Fedora 30 ([which is no longer supported](https://fedoraproject.org/wiki/Releases)) and just needs updating.

(I also noticed while writing this that there's a broken markdown link on the COPR repo's overview page under the `Installation instructions` heading.)

**Comment by neilalexander** [comment]
Closing as stale.
