### ISSUE TITLE
compile for Ubiquiti

### ISSUE THREAD

**Issue by loskiq** [yggdrasil-network/yggdrasil-go#725]
I compiled Yggdrasil for Ubiquiti and get this error:

```
UBNT-BZ.v4.3.20# /tmp/yggdrasil --help
Illegal instruction (core dumped)
UBNT-BZ.v4.3.20#
```

```
bash-5.0$ file yggdrasil
yggdrasil: ELF 32-bit MSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, Go BuildID=zrZLrOuRyamoe5_3mG6H/68QzWuVO09O_1D1UMcUm/N9y6VHQTkJw7EFh8EVxc/4cpQKGSHnWdWmCCdrmXK, stripped
bash-5.0$
```

**Comment by neilalexander** [comment]
Can you please be more specific?

Which commit/version did you build? Which Go version did you use? Which Ubiquiti hardware are you targeting?

**Comment by loskiq** [comment]
Commit: 78b5f88e4bb734d0dd6a138ff08d34ca39dcaea3
Go version: go1.14.6 linux/amd64
Ubiquiti: UAP-AC-Mesh (https://ubntwiki.com/products/unifi/unifi_mesh)

I did the following steps:

```
git clone https://github.com/yggdrasil-network/yggdrasil-go
cd yggdrasil-go/
GOARCH=mips ./build
```

Then I just copied yggdrasil and yggdrasilctl to Ubiquiti and tried to run yggdrasil

**Comment by loskiq** [comment]
@neilalexander i added `GOMIPS=softfloat` argument and now yggdrasil runs successfully. thanks for the hint, @tdemin!
