### ISSUE TITLE
Peer to Peer networking?

### ISSUE THREAD

**Issue by alpharde** [yggdrasil-network/yggdrasil-go#726]
Hi, I couldn't find this anywhere on the internet/github issues so I had to ask it here: can yggdrasil operate on a peer-to-peer nat traversal mode like zerotier?
I'm asking this because my understanding of the yggdrasil architecture is quite poor and it would always use my vps as a path to other peers.

**Comment by Vort** [comment]
I do not completely understand your configuration.
But if you can make TCP connection to one of the Yggdrasil peers, then Yggdrasil should work.

**Comment by alpharde** [comment]
Well, basically I'm asking this because yggdrasil is using my VPS as a path to reach the target peer which is not so far from where I am. While the peer is close, the VPS I'm using for tests is quite far (in the US, i'm in South America) and this means very long RTT for packets. I guess I got it wrong about how yggdrasil works.

**Comment by Vort** [comment]
Yggdrasil connects only to those peers, which are selected in `yggdrasil.conf`.
If you add more peers, then there will be more options for Yggdrasil to route packets.
If you open port with `Listen:` option, then also connections, which other users make to your node, will be used.

**Comment by alpharde** [comment]
Oh, a bit late, but I understand now. Thanks.
