### ISSUE TITLE
Auto add and update peers

### ISSUE THREAD

**Issue by GH0st3rs** [yggdrasil-network/yggdrasil-go#728]
To `yggdrasil` binary need add new features :

- Add available peers to /etc/yggdrasil.conf
- Update peers from /etc/yggdrasil.conf

For example [peer_checker.py](https://github.com/zhoreeq/peer_checker.py.git) can print available peers, you can just include a similar function into your project at the stage of creating a configuration file. You can also parse the git repository to fetch peer addresses, check them and add the available ones to the configuration file.
When the user decides to update the list of peers, for example, he will need to enter the command: `yggdrasil --update-peers` and all dead peers will be removed from the config

**Comment by GH0st3rs** [comment]
@loskiq I don't need online peers, it would be cooler if it was not necessary to monitor it manually at all, let yggdrasil find peers by itself and connect to them, monitor their updates, like a tor

**Comment by neilalexander** [comment]
It's really difficult to programmatically ensure that automatic peer selection does the right thing without creating suboptimal paths, which is why we specifically consider automatic peer management to be out-of-scope for the project.
