### ISSUE TITLE
Peers health check and automatic peer switching

### ISSUE THREAD

**Issue by zaibon** [yggdrasil-network/yggdrasil-go#729]
I've had this idea to implement something that does some health check on the peers that are configured over time and automatically switch to other peer in the event that my current peers disconnects or reject connections.

I was seeing something like having a list of possible peers in the config file and a number that represent the minimum healthy peer that Yggdrasil would try to always be connected to.

So if my list of possible peers would be:
- peer_1
- peer_2
- peer_3
- peer_4
And the number of minimum healthy peer would be 2. 
Then Yggdrasil would start and tries to connect to peer_1 and peer_2. If both accept peering, then the health checker would just sleep for a bit. Over time if one of the peer get disconnected Yggdrasil would try to connect to peer_3 and/or peer_4 and this until the minimum of 2 peers is matched.

Would it be something you could see included in the code base ?

**Comment by neilalexander** [comment]
Not planned at this time as it would make the peer management logic far more complicated.
