### ISSUE TITLE
Yggdrasil doesn't seem to route packets if the host's wall clock is too far behind (> 10 minutes or so)

### ISSUE THREAD

**Issue by wizeman** [yggdrasil-network/yggdrasil-go#740]
As the title says, if a host's wall clock is running more than 10 minutes or so behind (its peers' wall clock, I assume?), then if Yggdrasil is restarted it will connect to its peers but the peers will not receive any packets that this host sends over the Yggdrasil interface.

This is a bit of an issue for me because all my peers (except one) are synchronizing their clocks over their Yggdrasil interfaces, but they can't do that if Yggdrasil doesn't work when the clock is running behind. This is especially problematic for one of my nodes, which is a Raspberry Pi that doesn't have an RTC clock and always boots with the clock running behind...

**Comment by Arceliar** [comment]
Thanks for the report @wizeman, is this running in an isolated network, or is it connected to the rest of ygg?

If it's an isolated network, then I have some idea of what may be happening: the one place where host and peer clock *should* matter is with root announcements in the spanning tree. The root node of the tree is selected based on a hash of their key, and then sends announcements with an increasing sequence number. To make sure the sequence number does not decrease, we use the local timestamp as the sequence number -- so clocks being out-of-sync won't matter, but the root's clock rolling back is a problem. If the machine with the root key restarts, and its clock rolls back, then other nodes will see the root's timestamps as being too old (and so they ignore them). Each node will then select the best root node (highest hash of signing key) based on the announcements they see from their connected component of the network, with the old root selecting itself (and possibly partitioning the network in the process if it's the only path between other components). Things *should* fix themselves if/when the root's clock catches up to the old timestamp, but the better fix is to make sure that the root is a node with a non-decreasing clock.

If it's not running in an isolated network, then I don't think we have enough info to debug this. In that case, could you include the `yggdrasilctl getSelf` and `getPeers` results for each node?

**Comment by wizeman** [comment]
Hi @Arceliar,

It is indeed an isolated network.

I had already made sure that my home server (with a stable clock) had the highest `SigningPublicKey` (it starts with "fe..." in `yggdrasil.conf`) specifically to ensure that it becomes the root node. In contrast, the `SigningPublicKey` of the node with the unstable clock (the Raspberry Pi) starts with "67...". I also verified that when the Raspberry Pi restarts, even though the clocks are out of sync, they both get connected (I can see my home server when I run `yggdrasilctl getPeers` on the Raspberry Pi).

Isn't that how the root node gets selected? If the hex value in `yggdrasil.conf`'s `SigningPublicKey` is not the hash itself, how can I determine the hash value (to make sure that my home server always becomes the root node)?

That said, I can see that when I run `yggdrasilctl getSelf` on the Raspberry Pi, it says `Coords: []`, while the other nodes always have some number(s) between the `[ ... ]`. Does that mean my Raspberry Pi is indeed the root node?

Thanks!

**Comment by wizeman** [comment]
Ok, I can see that according to https://github.com/yggdrasil-network/yggdrasil-go/blob/d3672545a32ecd98b922efb7bb35fbf1b6d12951/src/crypto/crypto.go#L85-L88 ... and ... https://github.com/yggdrasil-network/yggdrasil-go/blob/d3672545a32ecd98b922efb7bb35fbf1b6d12951/src/yggdrasil/switch.go#L43-L56 ... the root node is selected based on the SHA-512 sum of the public signing key, rather than being the public signing key itself, so I will change my configuration accordingly.

As an FYI for future readers, if you put the hex value from `yggdrasil.conf`'s `SigningPublicKey` into the `$pubkey` env variable, you can calculate the tree id which is used to select the root node using this shell command:
```
echo -n $pubkey | sed 's/\([0-9A-F]\{2\}\)/\\\\\\x\1/gI' | xargs printf | sha512sum
```

I will fix my configuration to make sure my home server is the root node and report back to see if the issue is solved.

**Comment by Arceliar** [comment]
Hi again @wizeman,

> That said, I can see that when I run yggdrasilctl getSelf on the Raspberry Pi, it says Coords: [], while the other nodes always have some number(s) between the [ ... ]. Does that mean my Raspberry Pi is indeed the root node?

That's correct, the empty `[]` coords correspond to the root node, so the Pi apparently has the strongest key if that's the case.

Just a quick tip, since we don't document this very well, but the repo includes a utility for generating stronger keys. It's not particularly fast, so a dedicated attacker who wrote an optimized implementation would be at an advantage if they were trying to steal the root spot, but it should be good enough to avoid accidents from a random node ending up as root:

`go run cmd/genkeys/main.go -sig`

That will print out a new public key / private key / TreeID (hash of pubkey) every time it finds a new strongest ID. Running that for a few seconds should be strong enough for an isolated network of a few hundred to a few thousand nodes, if the rest of the nodes are just using the first random key they generate (the default behavior).

**Comment by wizeman** [comment]
That's great @Arceliar, thanks!

I am closing this issue as it has been solved for me, i.e. I made sure to regenerate my configs until my Raspberry Pi had the lowest SHA-512 of its `SigningPublicKey` in the entire network and my home server had the highest.

After regenerating the configs and making sure everything was working, I made sure to test whether the network was still working properly after rolling back the clock on the Raspberry Pi and indeed it was.

Feel free to reopen if you think anything else needs to be done.
Thanks!
