### ISSUE TITLE
Traceroute 

### ISSUE THREAD

**Issue by 0bsessive** [yggdrasil-network/yggdrasil-go#743]
Feature request to support 'traceroute' so its visible how traffic flows between which hops to destination

**Comment by Asherathe** [comment]
I'm not sure that's possible, since it uses node ids instead of ip addresses for routing.

**Comment by Vort** [comment]
It is better to make tracert _alternative_. Something like `yggdrasilctl tracert`.

**Comment by neilalexander** [comment]
@Arceliar — any thoughts on this?
