### ISSUE TITLE
AdminAPI method to test if a node is online by only knowing its Public key, not coords

### ISSUE THREAD

**Issue by zhoreeq** [yggdrasil-network/yggdrasil-go#747]
@Arceliar  quote from Matrix:

> we could probably add some kind of custom API call that does the DHT search and, instead of trying to open a session, just returns their key+coords if it succeeds (or an error if it fails)

> that would tell you that they're online and give you the info you'd need to e.g. send them a nodeinfo request

**Comment by neilalexander** [comment]
This is now the standard approach in v0.4, so closing.
