### ISSUE TITLE
Refactor TCP handshake for additional privacy

### ISSUE THREAD

**Issue by VictorNine** [yggdrasil-network/yggdrasil-go#753]
The current implementation makes it possible to scan the "clear net" and connect "clear net" address with Yggdrasil address/identify. This is a privacy concern that should be easy to fix.

Today the "server" node sends its metadata on connect. If this is reversed where the client sends its metadata first that would allow the server to decide if it wants to share its info or not.

This is a breaking change and is suggested for 0.4

**Comment by neilalexander** [comment]
We now have `tls://` connections and listeners which should avoid this problem by wrapping Yggdrasil peering connections in TLS, obscuring them somewhat.
