### ISSUE TITLE
[win] update wintun 

### ISSUE THREAD

**Issue by r4sas** [yggdrasil-network/yggdrasil-go#758]
Wintun continue updating, but we still use old 0.7 version.

If we will use old distribution model, when wintun driver were provided by msm package for MSI, latest version was 0.8.1.
Otherwise golang [wintun package](https://pkg.go.dev/golang.zx2c4.com/wireguard/tun/wintun) must be updated and `wintun.dll` must be provided with binary.

**Comment by neilalexander** [comment]
https://github.com/yggdrasil-network/yggdrasil-go/blob/d3672545a32ecd98b922efb7bb35fbf1b6d12951/contrib/msi/build-msi.sh#L74

**Comment by Vort** [comment]
Fixed with #766?
Look at #767 by the way.
Do not know if you know it or not, but new version uses both .dll and .sys (.dll installs .sys by itself).

**Comment by r4sas** [comment]
Closing, due to 0.3.16 release with usage of new distribution model.
