### ISSUE TITLE
how to make this software work under ipv4?

### ISSUE THREAD

**Issue by luckypoem** [yggdrasil-network/yggdrasil-go#760]
how to make this software work under ipv4?

**Comment by neilalexander** [comment]
You can make peering connections over IPv4 and you don't need IPv6 connectivity from your ISP for Yggdrasil to work.

Yggdrasil is primarily designed to carry IPv6 traffic though, so you would just need to make sure that IPv6 is not disabled on your host operating system.

**Comment by luckypoem** [comment]
@neilalexander 
then how to make peering connections over IPv4 ?can u give  a detailed instruction?

**Comment by neilalexander** [comment]
Have you read https://yggdrasil-network.github.io/configuration.html ?

**Comment by luckypoem** [comment]
@neilalexander 
i read it.but the following parameters needn't be filled in?
IPv6RemoteSubnets: {}
IPv6LocalSubnets: []
IPv4RemoteSubnets: {}
IPv4LocalSubnets: []

if the parameters need to be filled in,can u write a concrete example here?

**Comment by neilalexander** [comment]
It depends what you are trying to do here. If you just want to use Yggdrasil *on top of a regular IPv4 connection* then you don’t need to do anything special. Just add some peers. Yggdrasil can carry IPv6 traffic over either an IPv4 or an IPv6 peering.

If you want to *tunnel IPv4 traffic over Yggdrasil* (like a Wireguard tunnel) then for that you would use the local/remote subnet options as per https://yggdrasil-network.github.io/2018/11/06/crypto-key-routing.html, but this only works between two Yggdrasil nodes.

**Comment by luckypoem** [comment]
@neilalexander 

i installed yggdrasil on my linux vps and mac machine.

on my mac machine:
sudo yggdrasil -useconffile /usr/local/etc/yggdrasil.conf
Password:
2021/02/24 13:10:31 Build name: yggdrasil
2021/02/24 13:10:31 Build version: 0.3.15
2021/02/24 13:10:31 Starting up...
2021/02/24 13:10:31 Starting switch
2021/02/24 13:10:31 Starting router
2021/02/24 13:10:31 Startup complete
2021/02/24 13:10:31 Starting multicast module
2021/02/24 13:10:31 UNIX admin socket listening on /var/run/yggdrasil.sock
2021/02/24 13:10:31 Interface name: utun2
2021/02/24 13:10:31 Interface IPv6: 202:639e:9fdf:def3:54da:a0c3:b9d3:174f/7
2021/02/24 13:10:31 Interface MTU: 65535
2021/02/24 13:10:31 Added CKR remote subnet 10.8.0.1/24
2021/02/24 13:10:31 Added CKR local subnet 10.8.0.2/24
2021/02/24 13:10:31 Your IPv6 address is 202:639e:9fdf:def3:54da:a0c3:b9d3:174f
2021/02/24 13:10:31 Your IPv6 subnet is 302:639e:9fdf:def3::/64

and i opened another terminal,try to ping 10.8.0.1,but cannot ping thru:
yudeMacBook-Air:~ brite$ ping 10.8.0.1
PING 10.8.0.1 (10.8.0.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
Request timeout for icmp_seq 12
^C
--- 10.8.0.1 ping statistics ---
14 packets transmitted, 0 packets received, 100.0% packet loss
yudeMacBook-Air:~ brite$

when i visit http://geoiplookup.net/ ,it still shows my isp-assigned ip,not my vps's ip.
so,in china,i still cannot cross 'great firewall of china'.

so how to make it a usable vpn?

note: in vps and my mac,i left the 2 parameters not filled in. it doesn't matter,right?
IPv6RemoteSubnets: {}
IPv6LocalSubnets: []

**Comment by neilalexander** [comment]
Closing this as tunnel routing is no longer supported in v0.4.
