### ISSUE TITLE
Make getnodeinfo smarter

### ISSUE THREAD

**Issue by ShadowJonathan** [yggdrasil-network/yggdrasil-go#762]
It'd help a lot with investigating peers on the network if you're able to grab node info from;
- [ ] ip6 address
- [ ] coords(?)
- [ ] just public key

These would grab info from the DHT/network when needed, maybe coords is the most volatile of these (people hardcoding getting info from coords would be a disaster for some security concerns), but it'd help a lot if you can just do `yggdrasil getnodeinfo ip6=200:...`

**Comment by neilalexander** [comment]
We could do this from IPv6 address and from public keys by searching the DHT, which would give us all of the information we need.

Doing it from coords only is harder because we still need to know the public key to encrypt the request but we have no way to map coords to public key otherwise.

**Comment by neilalexander** [comment]
In v0.4 you only need to know the key for debug requests, so closing.
