### ISSUE TITLE
Build with ASLR protection on Windows

### ISSUE THREAD

**Issue by xor2003** [yggdrasil-network/yggdrasil-go#764]
See https://github.com/golang/go/issues/41421 for ASLR options

**Comment by neilalexander** [comment]
Apparently this is complicated because neither `-buildmode=pie` nor `-ldflags="-aslr"` are supported on Windows, therefore our Appveyor pipeline that builds the `.msi` installers can't produce such executables.

**Comment by neilalexander** [comment]
I did some work on this today to change the MSI builds from a Windows CI runner to a Linux one, and I *think* it's possible for us to use PIE/ASLR build modes when cross-compiling.

In any case, the latest MSIs on [the `develop` branch](https://yggdrasil-network.github.io/builds-develop.html) are built in this way, so please test and let me know if it makes a difference.

**Comment by xor2003** [comment]
Thank you. done
