### ISSUE TITLE
An error occurred starting TUN/TAP: Error registering rings: Error listing NDIS interfaces: no interfaces found

### ISSUE THREAD

**Issue by testeron211** [yggdrasil-network/yggdrasil-go#768]
Yggdrasill 0.3.15 x64
Windows 7 SP1 x64
The Yggdrasil adapter cannot be created

```
2021/03/13 12:53:47 Build name: yggdrasil
2021/03/13 12:53:47 Build version: 0.3.15
2021/03/13 12:53:47 Starting up...
2021/03/13 12:53:47 Starting switch
2021/03/13 12:53:47 Starting router
2021/03/13 12:53:47 Startup complete
2021/03/13 12:53:47 Starting multicast module
2021/03/13 12:53:47 TCP admin socket listening on 127.0.0.1:9001
2021/03/13 12:53:47 Listening for TCP on: [fe80::84c5:5679:a74:542b%Local Area Connection]:55126
2021/03/13 12:53:50 An error occurred starting TUN/TAP: Error registering rings: Error listing NDIS interfaces: no interfaces found
2021/03/13 12:53:50 Your IPv6 address is 200:4130:5585:1588:748e:299a:9587:5f86
2021/03/13 12:53:50 Your IPv6 subnet is 300:4130:5585:1588::/64
```

**Comment by neilalexander** [comment]
Please try the latest develop build instead: https://yggdrasil-network.github.io/builds-develop.html

**Comment by testeron211** [comment]
> Please try the latest develop build instead: https://yggdrasil-network.github.io/builds-develop.html

not working

**Comment by neilalexander** [comment]
Did you install using the `.msi` or did you download the `.exe` directly?

The MSI installers contain the Wintun driver which Yggdrasil needs. The standalone `.exe` does not.

**Comment by testeron211** [comment]
> Did you install using the `.msi` or did you download the `.exe` directly?
> 
> The MSI installers contain the Wintun driver which Yggdrasil needs. The standalone `.exe` does not.

The driver seems to be installed, since the driver installer does not offer

**Comment by testeron211** [comment]
now dev branch MSI returns an error "Service failed to start. Verify that you have sufficient privillages to start system services."

**Comment by testeron211** [comment]
Problem fixed after installing windows update W2K12-KB3191565-x64 (management framework 5.1)
