### ISSUE TITLE
Built-in DNS

### ISSUE THREAD

**Issue by mnqw95** [yggdrasil-network/yggdrasil-go#777]
Apologies in advance for translate.google

You have created a wonderful network. I thank you.
If you do not mind, I suggest you register on donate platforms where we can financially support you, development, Yggdrasil Network project.
For a small donation to the developer (through the donate platform), in return, you will provide users with the opportunity to create their own (eternal, editable in cases of need) domain in the .ygg .mesh .coin zones .. and other non-working in the global network.
For these purposes, create a separate chat (for feedback) in matrix or telegram.

Implementation:
Embed a local DNS resolver in the client, which will work with a local /etc /hosts  file (updated via the Internet once a day) which you will publish, for example, on your site hosts.neilalexander.dev. and github.com/yggdrasil-network/hosts or in other sources
Add separate myhosts (for manual addition)

Benefits from this:
1. Unified DNS base
2. Responsiveness, speed, no need every time they turn to external DNS servers.
3. There is no need to use mining, and others (crutches).
4. Financial support, will stimulate the developer to improve the network and user application in which there is a very shortage of practical implementations (Web.UI interface. UDP QUIC protocols .. Direct p2p connection between users, with support for nat hole punching) ... as implemented for example in the Syncthing app

**Comment by mnqw95** [comment]
Available libraries for interacting with the local hosts file on different OS :
https://github.com/txn2/txeh
https://github.com/goodhosts/hostsfile

**Comment by Bogdan107** [comment]
1) Yggdrasil and DNS resolve non-overlapping tasks.
Yggdrasil resolve problem of connectivity beetwen systems (commutation, routing).
DNS - is next-level service, which resolve other problem in network of ALREADY connected systems.

2) Grants to change hosts file from networked service - is bad security practice.
hosts file is in competention of ```System Aadministrator```. Commutation/routing - is in competention of ```Network Administrator```.
Network Admin can not change system files without System Admin - it is a basic security rule.
If yggdrasill will require grants to change hosts file - I will block them always.

3) Changes to hosts file does nod needs yggdrasil or any other network service.
hosts file can updated by third-party script in cron, without yggdrasil service.

4) Domain resolving system, based over hosts file - does nod need separate DNS-resolver in any sense.

**Comment by mnqw95** [comment]
Yes, this is understandable, I still prefer DHT and Alfis

**Comment by Bogdan107** [comment]
I prefer [A.L.F.R.E.D.](https://www.open-mesh.org/projects/alfred/wiki) to redistribute DNS info and bash script to convert-and-import those info into local standart DNS-resolver.

**Comment by Bogdan107** [comment]
DNS discussed in #661
