### ISSUE TITLE
[question] can yggdrasil leak my ip?

### ISSUE THREAD

**Issue by 73686f7461** [yggdrasil-network/yggdrasil-go#785]
if i were to host something using my home internet, could someone connecting to me on yggdrasil get my clearnet ip?

**Comment by neilalexander** [comment]
The only people who can see your real clearnet IP are your direct peers. Nobody else on the network can.

**Comment by 73686f7461** [comment]
okay c: thank you

**Comment by asakura42** [comment]
@neilalexander but who are _direct peers_? That public peers that I described in config or basically every who see things I host? Or anybody else like random peers that connect to me to maintain meshnet? (Found ygg today, still learning it, understand barely nothing but very interesting project tho)
