### ISSUE TITLE
Getting "destination unreachable" when pinging services 

### ISSUE THREAD

**Issue by lainspetcat** [yggdrasil-network/yggdrasil-go#789]
Hi, I'm new to linux and github so let me know if I need to include more.

I'm not sure what's going wrong. I'm on arch linux and installed yggdrasil with `yay -S yggdrasil-git`. After trying to set it up, When I ping a service, I get the following: 
`PING 201:4541:2f84:1188:59ab:e8dd:48a8:d40c(201:4541:2f84:1188:59ab:e8dd:48a8:d40c) 56 data bytes
From 201:509e:2312:5185:6f8c:8a50:c8c6:e11c icmp_seq=1 Destination unreachable: Port unreachable
From 201:509e:2312:5185:6f8c:8a50:c8c6:e11c icmp_seq=2 Destination unreachable: Port unreachable`

I have 5 peers added under "InterfacePeers". I'm not using the other peers section. Here's what it looks like:
`InterfacePeers: { 
    "wg-mullvad": [
      tcp://(address 1)
      tcp://(address 2)
      tcp://(address 3)
      tcp://(address 4)
      tcp://(address 5)
    ]
}`
(I'm using mullvad vpn, and my friend told me to put the mullvad part there)

Any help is appreciated

**Comment by holdneck** [comment]
I had the same issue, but disconnecting Mullvad solved the issue. I use the Mullvad app, so I tested both Openvpn and Wireguard, and they both had the same issue. However, when I setup Wireguard directly, I had no issues. I would guess the Mullvad app is messing with firewall rules in the background, but I am still a noob when it comes to a lot of networking so it could be changing something else. I hope this helps.

**Comment by cofob** [comment]
Can you try to set peers directly in `Peers`?
You can also see the current peers to which you are connected with the `sudo yggdrasilctl getPeers` command.

**Comment by holdneck** [comment]
I am away from my main pc right now, but I did directly set peers. They produced the same error, but they showed as connected when I ran getpeers.

**Comment by neilalexander** [comment]
Closing as it is a known problem that Mullvad messes with the host firewall to stop IP leaks.
