### ISSUE TITLE
Make yggdrasil run as its own user by default.

### ISSUE THREAD

**Issue by zander** [yggdrasil-network/yggdrasil-go#803]
I have started the yggdrasil client using the default packages but with plenty of changes;

1. I created a new yggdrasil user next to the already existing group.
2. created a directory `/etc/yggdrasil` which I made owned by the just created user and group.
3. auto-generate a config file and output it to `/etc/yggdrasil/server.conf`
4. alter the shipped `/usr/lib/systemd/system/yggdrasil-default-config.service` to refer to the new server.conf one (many times).
5. alter the shipped `/usr/lib/systemd/system/yggdrasil.service` to refer to the server.conf too. Additionally add under `[Service]` a line with `User=yggdrasil`
6. run (as root) `setcap cap_net_admin,cap_net_raw+eip /usr/bin/yggdrasil`
7. altered the server.conf to set the `AdminListen` to `unix:///etc/yggdrasil/yggdrasil.sock`

Various of these items will be substantially easier/unneeded when #802 is resolved. After that it is mostly a matter of writing a PACKAGERS file explaining this for those packagers packaging for the appropriate systems.

And to re-iterate, the socket creation can really use some love. It actively tries to remove the socket file on startup and then complains when it can't, instead of simply checking the permissions and using it. Its hard to make it run as non-root with the 0.4 codebase.

**Comment by tdemin** [comment]
> run (as root) `setcap cap_net_admin,cap_net_raw+eip /usr/bin/yggdrasil`

Don't. Do `AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW` in the relevant `.service` file instead.

**Comment by zander** [comment]
Thank you @tdemin  I can confirm that adding that line indeed works.

**Comment by OlegGirko** [comment]
Please don't use `/etc` subdirectory for the socket. Use `/run` instead.

The `RuntimeDirectory=yggdrasil` directive in `systemd` service file will cause `/run/yggdrasil` directory to be created automatically on service startup.

Also, `/etc/yggdrasil` should be owned by `root`, not `yggdrasil` user, and permissions of this directory and config file inside it should be set the way to allow `yggdrasil` to read but not write to them.

**Comment by zander** [comment]
Thank you so much OlegGirko, that piece of knowledge was the puzzle piece we needed to make this work with nearly no code changes.

I created a PR 816.
