### ISSUE TITLE
Signed MSI

### ISSUE THREAD

**Issue by mkg20001** [yggdrasil-network/yggdrasil-go#811]
Currently the MSI for yggdrasil is not signed

I happen to have a code-signing certificate for windows with which it could be signed, so that smartscreen doesn't trigger when trying to install it

Is the project interested in this?

**Comment by cofob** [comment]
They are paid, and not so necessary.

**Comment by neilalexander** [comment]
Whilst we very much appreciate the offer, the project isn’t really at the stage of maturity yet where we need code-signing. We still consider Yggdrasil to be alpha at the moment so I think this, despite being a papercut, is OK for now.
