### ISSUE TITLE
[Question] Difference in ping on subnets 300 and 200

### ISSUE THREAD

**Issue by cofob** [yggdrasil-network/yggdrasil-go#819]
Hi. We found a difference in ping between subnets 200 and 300. There is less ping in 300 subnet than in 200. Is it real at all? What reason?

**Comment by ShadowJonathan** [comment]
Please elaborate, what do you mean with "less ping"? Less ping delay? Also, what 300 vs 200 subnets did you try? Was it the same node?

**Comment by Vort** [comment]
My observation is slightly different:
Sometimes 300 faster, sometimes 200 faster.
When pings are active, speed do not change too much.
But if you cancel command and start it slightly later, speed may lock to different value.

I guess it is related to source routing.
300 and 200 can be locked to different routes.
And such lock is not consistent (have some amount of randomness).
