### ISSUE TITLE
json unmarshal panic on startup

### ISSUE THREAD

**Issue by deathtrip** [yggdrasil-network/yggdrasil-go#824]
I'm using the git package from the AUR with go 1.16.6, and upon starting the service i get this error:

> panic: json: cannot unmarshal string into Go struct field NodeConfig.Listen of type []string
yggdrasil[177312]: goroutine 34 [running]:
yggdrasil[177312]: main.readConfig(0xc000128060, 0x0, 0x7ca3dbe81865, 0x13, 0xc00012c000, 0x0)
yggdrasil[177312]:         /tmp/makepkg/yggdrasil-git/src/yggdrasil/cmd/yggdrasil/main.go:132 +0xdb7
yggdrasil[177312]: main.run(0x0, 0x7ca3dbe81865, 0x13, 0x0, 0x75de58, 0x6, 0x0, 0x75d7ea, 0x4, 0x7bd038, ...)
yggdrasil[177312]:         /tmp/makepkg/yggdrasil-git/src/yggdrasil/cmd/yggdrasil/main.go:268 +0x1078
yggdrasil[177312]: created by main.main
yggdrasil[177312]:         /tmp/makepkg/yggdrasil-git/src/yggdrasil/cmd/yggdrasil/main.go:395 +0x22e
systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: yggdrasil.service: Failed with result 'exit-code'.

**Comment by beryll1um** [comment]
Please provide more information about the problem. I've tried to compile project from [AUR package](https://github.com/yggdrasil-network/yggdrasil-go) then generate configuration:
```bash
./yggdrasil -genconf > yggdrasil.conf
```
and finally start the yggdrasil node:
```bash
sudo ./yggdrasil -useconffile yggdrasil.conf
```
In my case all working fine. I think you've generate configuration not in according with guide or your config has been modified after the generation.

**Comment by deathtrip** [comment]
I was using the old config file from the 0.3 version, after generating a new one, it's working again. Thanks for the hint.
