### ISSUE TITLE
panic: no such device  - arch

### ISSUE THREAD

**Issue by katelinlis** [yggdrasil-network/yggdrasil-go#831]
OS arch

1. install yggdrasil
2. yggdrasil -genconf > /etc/yggdrasil.conf
3. set peers 
4. start yggdrasil -useconffile /etc/yggdrasil.conf

2021/08/22 11:25:59 Build name: yggdrasil
2021/08/22 11:25:59 Build version: 0.4.0
2021/08/22 11:25:59 Starting up...
2021/08/22 11:25:59 Startup complete
2021/08/22 11:25:59 Starting multicast module
2021/08/22 11:25:59 UNIX admin socket listening on /var/run/yggdrasil.sock
2021/08/22 11:25:59 Listening for TLS on: [fe80::36dd:548f:5fd9:da8%enp2s0]:43677
panic: no such device

goroutine 41 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0xc0001c8150, 0xc0001b8060, 0x4, 0xc0001dc150, 0x28, 0xcf39, 0x28, 0x0)
        github.com/yggdrasil-network/yggdrasil-go/src/tuntap/tun_linux.go:19 +0x31c
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start(0xc0001c8150, 0x0, 0x0)
        github.com/yggdrasil-network/yggdrasil-go/src/tuntap/tun.go:136 +0x335
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start.func1()
        github.com/yggdrasil-network/yggdrasil-go/src/tuntap/tun.go:108 +0x35
github.com/Arceliar/phony.Block.func1()
        github.com/Arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:80 +0x31
github.com/Arceliar/phony.(*Inbox).run(0xc0001c8198)
        github.com/Arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:89 +0x3f
created by github.com/Arceliar/phony.(*Inbox).restart
        github.com/Arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:121 +0x45

**Comment by neilalexander** [comment]
Does your system have the `tun` module available and loaded? (try `modprobe tun`)

**Comment by katelinlis** [comment]
not started tun, after restart arch linux issues solved
