### ISSUE TITLE
[vulnerability] MiTM attack

### ISSUE THREAD

**Issue by cofob** [yggdrasil-network/yggdrasil-go#832]
Hello!  In the current implementation of public peers, an attacker can intercept traffic and send it to his machine by performing an invisible MiTM attack (since all peers are in the public access, he can easily distinguish https traffic from yggdrasil).  He will be able to see what resources the computer is accessing and block any requests.  To solve this problem, you can add a verification certificate parameter (like `?key=`, or verification via root machine certificates) to the `tls` transport (and an option in the config to specify the path to the certificate).

**Comment by neilalexander** [comment]
`?key=` was already added as a way to pin per keys to mitigate an attack like this.
