### ISSUE TITLE
Outdated package in FreeBSD

### ISSUE THREAD

**Issue by cofob** [yggdrasil-network/yggdrasil-go#839]
Already 0.4, but there is [still](https://www.freshports.org/net/yggdrasil/) 0.3.16. Please update.

**Comment by neilalexander** [comment]
I’ve had some problems trying to get the port updated for both v0.4.1 and v0.4.2 due to the Wireguard dependencies. I don’t know enough about FreeBSD to know what the solution is.

**Comment by Demindiro** [comment]
I submitted a [patch](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257301) for 0.4.0 a while ago and it seems to work fine so far. I don't know what the holdup is though admittedly I haven't been following it closely either.

**Comment by neilalexander** [comment]
Closing as stale.
