### ISSUE TITLE
Apple M1 chip support

### ISSUE THREAD

**Issue by abdalazizrashid** [yggdrasil-network/yggdrasil-go#844]
Will be there native support for Apple Silicon?

**Comment by neilalexander** [comment]
Can you please try this build and let me know how you get on?

https://4917-115685026-gh.circle-artifacts.com/0/yggdrasil-applesilicon-0.4.0-31-g95a6a6b-macos-arm64.pkg

**Comment by abdalazizrashid** [comment]
It worked!

**Comment by neilalexander** [comment]
Great, I've merged that into `develop` and now macOS ARM64 builds will be produced automatically for future versions.
