### ISSUE TITLE
Peers behind NAT from same IP handled as child of another peer when they don't have direct connections between them

### ISSUE THREAD

**Issue by crzsotona** [yggdrasil-network/yggdrasil-go#845]
Scenario:
Four nodes: one external node, three nodes behind NAT on same external IP.
All nodes behind NAT don't have direct connections between them (different physical subnets) and have external node in config as only peer.
External node list all connected NATed peers but only first connected peer is connected directly, second and third are handled as child peers of first peer (which has no connections to these peers) thus making them unavailable.

When Yggdrasil service is stopped on node with direct connection to external, another node establish connection to external node and became parent to rest of NATed nodes.

External node with three peers connected
![image](https://user-images.githubusercontent.com/13541485/135245970-8a00a8d8-1e03-4d17-9348-d55ebf3bd64b.png)
Peer 1
![image](https://user-images.githubusercontent.com/13541485/135243622-5a77066b-6df0-475f-b587-80ce544e76f7.png)
Peer 2
![image](https://user-images.githubusercontent.com/13541485/135243671-01b7a674-382e-434b-a4ee-39977a29ab93.png)
Peer 3
![image](https://user-images.githubusercontent.com/13541485/135243704-c257bfdc-10ff-4e87-bf86-d7722a893b04.png)

**Comment by neilalexander** [comment]
As far as I can tell, this topology looks fine. The actual spanning tree would look like this, because `97c5` (peer 1) appears to be the root node of your small network:
```
       97c5  []     <- root node
          |
       8799 [1]
       /      \
3f16 [1 2]   4c14 [1 3]
```
I don't see a problem?

**Comment by crzsotona** [comment]
Sorry, didn't checked for replies for a while.
8799 is the root node, not 97c5.
All child nodes of 8799 don't have connections between as they're in different firewalled vlans.
Actual scheme looks like this, root node supposed to treat childs as independent nodes IMO:

`      external root node 8799 []     
          ↕             ↕                ↕
3f16 [2]<≠>97c5 [1]<≠>4c14 [3]`


Basically, I'm trying to connect three NATed nodes via external root serving as relay.
I hope this is better explanation than first one.

**Comment by Arceliar** [comment]
It looks like the external node is `200:X:8799 [1]`, and one of the internal nodes (`202:X:97c5`) is the root. On the ygg side of things, everything looks like it should be OK based on the screenshots of the yggdrasilctl output.

Can you try `yggdrasilctl getsessions` after one of the internal nodes tries to ping another? If the session is created on both ends, then it's not a ygg issue (it's more likely a firewall issue on one of the nodes).

**Comment by neilalexander** [comment]
Closing as stale.
