### ISSUE TITLE
Traffic Circling vulnerability

### ISSUE THREAD

**Issue by jorektheglitch** [yggdrasil-network/yggdrasil-go#851]
Every node can specify a path for packet since Yggdrasil has Source Routing.
But it causes DDoS amplification by the creating a route loops.

In following pic  Attacker (red node) can send packet to any other node and specify a route [2 3 5 4 3 5 4 3 5 4 ... 3 5 4]. It causes packet go thorough a loop over and over again. And it can cause ~20000x traffic amplification. From 1MB/s to 20GB/s. So it maybe causes a huge RAM/CPU usage and shutdown a node.

![image](https://user-images.githubusercontent.com/57464345/135809219-ea840052-d47c-4734-93d6-a1a6430c2878.png)

**Comment by Vort** [comment]
It can be fixed simply by not allowing node to be included in list several times.
I hope that no real attack would be required for implementation of this check.

**Comment by jorektheglitch** [comment]
@Vort, each hop see a path, but this path contains only relative coirds (port numbers). Since this it's very hard to intermediate nodes to know that a path has circles.

**Comment by neilalexander** [comment]
v0.5 will no longer use source routing.
