### ISSUE TITLE
Installation failure on Raspbian

### ISSUE THREAD

**Issue by ThomasFreedman** [yggdrasil-network/yggdrasil-go#852]
There is no package "yggdrasil" for 32 bit Raspbian OS (armv7l architecture).

The build looks straightforward, but I would need to upgrade go from version 1.12.17 which is the latest version without [something] I don't recall now I didn't like, related to spyware, security or some such thing. 

A binary may get around that, but perhaps not. I need to go back and review my objection to newer go versions.

**Comment by neilalexander** [comment]
For ARMv7, I would expect that the `armhf` package from https://yggdrasil-network.github.io/builds-develop.html should work. If not, try the `armel` compatibility package.

**Comment by ThomasFreedman** [comment]
Thank you, will chk that out. I was just using the instructions here: https://yggdrasil-network.github.io/installation-linux-deb.html

**Comment by ThomasFreedman** [comment]
I downloaded both the hf & el arm binaries from that link, both run & print some cmd line help if no args provided. I will review the remainder of installation process and continue.

Thx for the link, and for all your work on this!

**Comment by ThomasFreedman** [comment]
It's all good, there is no problem, apparently I skipped over the apt-get update after adding the gpg keys & repo.

Sorry to trouble you on this.

**Comment by neilalexander** [comment]
Glad to hear it's all sorted. If the `armhf` builds work, then you'll probably get better performance with those compared to the `armel` builds.
