### ISSUE TITLE
yggdrasil -useconf -address: Behaviour change since 0.4

### ISSUE THREAD

**Issue by kittywitch** [yggdrasil-network/yggdrasil-go#856]
You used to be able to do:

```
echo '{ EncryptionPublicKey: "..." }' | yggdrasil -useconf -address
```

With yggdrasil v0.4, the equivalent would have been:

```
echo '{ SigningPublicKey: "..." }' | yggdrasil -useconf -address
```

however due to ea15eeee7ed5ebd5138773d1453615561421dac, it now automatically generates a private key and gets the public key from it despite having a provided public key, meaning that if you provide a public key but not a private key to the command you will get a random address due to a random, new generated private key.

This is a change in behaviour and makes my capacity to generate the address without providing the private key hard to do without reimplementing https://github.com/yggdrasil-network/yggdrasil-go/blob/99227b60cedfb278b1b6d6ac9ae965f47fce5ccf/src/address/address.go#L51-L94 externally.

**Comment by neilalexander** [comment]
It's certainly easy enough to build something like that:

```
package main

import (
	"encoding/hex"
	"fmt"
	"net"
	
	"github.com/yggdrasil-network/yggdrasil-go/src/address"
)

func main() {
	pk, err := hex.DecodeString("3038ccbd220f1126c33b4224b45b61e8986e81d2c0e77457b2a2758ea3d0cec2")
	if err != nil {
		panic(err)
	}

	ip := net.IP(address.AddrForKey(pk)[:])
	fmt.Println(ip)
}
```

Go Playground: https://play.golang.org/p/08wlhaHhHgI

What is your real-world use-case here?
