### ISSUE TITLE
"yggdrasilctl reconnect" command to fix delay when switching networks

### ISSUE THREAD

**Issue by mkg20001** [yggdrasil-network/yggdrasil-go#857]
Usually when networks are switched, yggdrasil is busy sending data over possibly dead TCP tunnels until eventually removing the connections and attempting reconnection (ex switching wifis)

This could be speed up by having a command "yggdrasilctl reconnect" which could be called as a hook by a hook of the network manager of the system and would force disconnection and reconnection of all peers immediatly

**Comment by jhaar** [comment]
Wouldn't it be better that yggdrasil could detect such broken TCP connections faster? Eg OpenVPN has a "ping" function  where it's continually testing the tunnel to ensure it's working and after 'n'  timeouts it tears the tunnel down and reinitializes.

**Comment by neilalexander** [comment]
Yggdrasil notices that a TCP session is dead within 6 seconds. It's just that it can take up to a minute to retry connecting a failed peering or up to 15 seconds for a multicast beacon to happen.

**Comment by mkg20001** [comment]
Another idea would be to check if the underlying network changes state (e.g. becomes up/down) and then act accordingly upon all connections that run over that network

(So if wifi is switched then LAN peerings - ex local VMs - that are completely unaffected will be left alone)

**Comment by neilalexander** [comment]
We have tried to do something similar to this in the past, but there’s no portable way to do it across platforms. Our current code for multicast already polls the network interface state on the system every couple seconds but that’s a logically separate piece of code to the router and doesn’t share any state. 

A simpler solution might just be for us to retry failed peerings more quickly (within a second or two) and back off progressively if the connection continues to fail. That way blips may be less noticeable.

**Comment by neilalexander** [comment]
Closing due to #983.
