### ISSUE TITLE
In some cases, the firewall may not see TUN Yggdrasil.

### ISSUE THREAD

**Issue by Fhiss** [yggdrasil-network/yggdrasil-go#858]
I have a Fedora 34. In some cases, the firewall may not see TUN Yggdrasil. The problem is reproduced as follows:
1. Add a WireGuard to the NetworkManager.
2. Connect to the Wi-Fi network where the UDP is blocked.
3. Turn WireGuard off.
4. **journalctl -fu yggdrasil.service**
	_Not multicasting on wlan0 due to error: listen tcp [fe80:db8::%wlan0]:0: bind: cannot assign requested address
	Connected TLS_
5. **firewall-cmd --get-active-zones**
_public
  interfaces: wlan0_

The problem is solved by patch https://github.com/yggdrasil-network/yggdrasil-go/pull/841

**Comment by neilalexander** [comment]
Should be fixed in v0.4.1/v0.4.2.
