### ISSUE TITLE
Add new transport: DNS

### ISSUE THREAD

**Issue by cofob** [yggdrasil-network/yggdrasil-go#870]
# Why?
Current Internet providers do not restrict the DNS protocol in any way after the traffic ends. (Mostly on mobile operators) This can be used to access the Internet and Yggdrasil for free. This allows to use Yggdrasil in any environment, safely, decentralized and without restrictions.

# Existing implementation approaches
1. [Iodine](https://github.com/yarrick/iodine)
2. [dnstt](https://github.com/Mygod/dnstt)

# Speed
I tested dnstt on a mobile operator when all the traffic was consumed. Stable speed - 50 kilobytes per second.

# What will the connection string look like?
```
dns://domain.tld
```

# What dependencies are needed to bring up a node with this tunnel?
Open port `53` for external connections and a clearnet domain of any level. (like `ygg.domain.tld`)

**Comment by ShadowJonathan** [comment]
(I would recommend suggesting this to the pinecone repository instead/also)

**Comment by neilalexander** [comment]
We currently require a reliable and ordered stream transport for peering connections. DNS is unordered/unreliable as it is typically over UDP.

**Comment by Saiv46** [comment]
> We currently require a reliable and ordered stream transport for peering connections. DNS is unordered/unreliable as it is typically over UDP.

So basically this is locked by #345 (which is locked by #344)

**Comment by cofob** [comment]
> > We currently require a reliable and ordered stream transport for peering connections. DNS is unordered/unreliable as it is typically over UDP.
> 
> So basically this is locked by #345 (which is locked by #344)

They are not related. The system itself sends DNS queries over UDP.

**Comment by neilalexander** [comment]
> So basically this is locked by #345 (which is locked by #344)

Yes, that’s right, because the protocol would need various changes in order to work on any unreliable/unordered datagram transport. That includes DNS.

**Comment by ShadowJonathan** [comment]
@neilalexander would the protocol itself require changes, or only the mechanism that ensures peering?

**Comment by mkg20001** [comment]
Establishing a stable connection over what would basically amount to "TCP over UDP" could be a hack to get this working before the necessary protocol changes happen

**Comment by neilalexander** [comment]
This is not planned, we have plenty of peering transports already.
