### ISSUE TITLE
Haproxy: nginx with yggdrasil on same port

### ISSUE THREAD

**Issue by cofob** [yggdrasil-network/yggdrasil-go#872]
Since yggdrasil sends `SNI` when using `TLS` transport, is it possible to use `haproxy` to proxy `yggdrasil` and `nginx` requests on the same port? Distinguishing requests by `SNI` domain.

**Comment by neilalexander** [comment]
It should be, yes, if the proxying is based on SNI alone.

**Comment by neilalexander** [comment]
Closing as `?sni=` is available on `Peer` entries.
