### ISSUE TITLE
Peers work but sites doesn't open

### ISSUE THREAD

**Issue by kt30015** [yggdrasil-network/yggdrasil-go#873]
I've tried on Ubuntu, Windows 7, Android. Everywhere the same - peers adding, pinging - but ygg sites doesn't work, just infinite load. There's my journalctl logs from Ubuntu:
```
дек 13 00:33:28 upc systemd[1]: Starting yggdrasil...
дек 13 00:33:28 upc systemd[1]: Started yggdrasil.
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Build name: yggdrasil
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Build version: 0.4.2
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Starting up...
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Startup complete
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Starting multicast module
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Listening for TLS on: [fe80::8fcc:e20a:c42b:4770%wlp4s0b1]:37397
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Interface name: tun0
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Interface IPv6: ---:----:----:---:----:----:---:----/7
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Interface MTU: 53049
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Your public key is 1d898822ea95a86ba6a3bf33dbccbdb3e0170ffa493ae4be9147000a4483b436
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Your IPv6 address is ---:----:----:---:----:----:---:----:4334
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Your IPv6 subnet is ---:----:----:---:----:----::/64
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 UNIX admin socket listening on /var/run/yggdrasil.sock
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Connected TCP: 200:5f8f:8354:1f7:85cb:ff8:3d5e:93f2@92.124.136.131, source 192.168.0.84
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Connected TCP: 223:de:d243:af64:99c1:70ea:a28a:f165@109.195.147.103, source 192.168.0.84
дек 13 00:33:28 upc yggdrasil[2870]: 2021/12/13 00:33:28 Connected TCP: 202:9e33:90f:33cf:e300:dda8:3e1b:2c54@193.33.240.97, source 192.168.0.84
дек 13 00:33:33 upc yggdrasil[2870]: 2021/12/13 00:33:33 Connected TLS: 21e:49c5:ff96:2b48:ed68:4dfd:7f8:be45@194.146.43.53, source 192.168.0.84
дек 13 00:36:48 upc yggdrasil[2870]: 2021/12/13 00:36:48 Disconnected TCP: 202:9e33:90f:33cf:e300:dda8:3e1b:2c54@193.33.240.97, source 192.168.0.84; error: EOF
дек 13 00:37:34 upc yggdrasil[2870]: 2021/12/13 00:37:34 Connected TCP: 202:9e33:90f:33cf:e300:dda8:3e1b:2c54@193.33.240.97, source 192.168.0.84
дек 13 00:38:51 upc yggdrasil[2870]: 2021/12/13 00:38:51 Disconnected TCP: 223:de:d243:af64:99c1:70ea:a28a:f165@109.195.147.103, source 192.168.0.84; error: EOF
дек 13 00:39:33 upc yggdrasil[2870]: 2021/12/13 00:39:33 Connected TCP: 223:de:d243:af64:99c1:70ea:a28a:f165@109.195.147.103, source 192.168.0.84
```
So it seems that Ygg starts normally, but when I try to open any site - it starts to disconnect.
And a string from "systemctl status yggdrasil" :
```
дек 12 23:50:34 upc yggdrasil[1963]: 2021/12/12 23:50:34 Disconnected TCP: xxxx:xxx:xxxx:xxx:xxxx:xxxx@XX.XXX.XXX.XXX, source 192.168.0.84; error: read tcp 192.168.0.84:33152->92.124.136.131:30111: i/o timeout
```

**Comment by neilalexander** [comment]
Do just the TCP peers disconnect, or do the TLS ones also disconnect? It’s possible you have a misbehaving firewall somewhere (not tracking connection state properly) or it’s possible that your ISP might be performing some kind of deep packet filtering.

**Comment by kt30015** [comment]
Thanks for answer.

> Do just the TCP peers disconnect, or do the TLS ones also disconnect?

TLS disconnecting too.

> It’s possible you have a misbehaving firewall

I'll try to configure ufw on ubuntu. It'll be helpful if there any special guides for Ygg and Ufw.

> ISP might be performing some kind of deep packet filtering

Maybe. I already discovered that my ISP sets OpenVpn connection speed to extremely low, after some size of transfered data. Is Yggdrasil packets are visible for DPI?

**Comment by kt30015** [comment]
```
00:38:51 Disconnected TCP: 223:de:d243:af64:99c1:70ea:a28a:f165@109.195.147.103, source 192.168.0.84; error: EOF
```

'source 192.168.0.84' - doesnt it strange that it tries to connect from my local ip given by router's NAT?

**Comment by Arceliar** [comment]
Disconnects with an `error: EOF` mean that the connection was closed by your peer (or a misbehaving router, firewall, or ISP).

That's almost certainly coming from your peer. Your node will send keep-alive traffic every 4 seconds, and the peer will time out the connection and close it if they don't receive traffic within 6 seconds. So if your traffic is dropped or delayed for >2 seconds, then you can start seeing timeouts.

I've seen this problem when I use public wifi in some places. Is this connection over wifi? Do you have high latency or jitter when you try to ping a node?

**Comment by Vort** [comment]
Looks like DPI. And it is worrying that TLS do not helps.
ISP may break any connection that looks suspicious to it :(

**Comment by Vort** [comment]
> peers adding, pinging

Do you mean pinging their IPv4 addresses or ygg IPv6?
Can you also try pings with larger packets?
Like `ping 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb /l 1400`

**Comment by kt30015** [comment]
> Is this connection over wifi?

Yes, but router is mine.

> Do you mean pinging their IPv4 addresses or ygg IPv6?

ipv4.

> Also try pings with larger packets?

I've tried your example, its doesnt works with "l" parameter. Without him pings normally:
```
13.12.21 17:31 u@upc:~$ ping 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb /l 1400
ping: 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb: Address family for hostname not supported
13.12.21 17:38 u@upc:~$ ping 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb -l 1400
ping: cannot set preload to value greater than 3: 1400
13.12.21 17:38 u@upc:~$ ping -c 4 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb
PING 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb(21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb) 56 data bytes
64 bytes from 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb: icmp_seq=1 ttl=64 time=547 ms
64 bytes from 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb: icmp_seq=2 ttl=64 time=120 ms
64 bytes from 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb: icmp_seq=3 ttl=64 time=121 ms
64 bytes from 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb: icmp_seq=4 ttl=64 time=121 ms

--- 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 119.677/227.214/546.635/184.418 ms
```
I also tried on my vps which is in other country, peers pinging, but sites - no. Is my command for ping site is correct?(with -6 parameter doesn't work too)
```
ping -c 4 303:60d4:3d32:a2b9::4
```

**Comment by Vort** [comment]
> I've tried your example, its doesnt works with "l" parameter.

`/l` is for Windows, try with `-s` for Linux.

**Comment by kt30015** [comment]
> try with `-s` for Linux.

0% packet loss, ~90ms on ubuntu-vps, ~130ms on ubuntu-desktop.

**Comment by Vort** [comment]
>  Is my command for ping site is correct?

Looks like so, but I don't know that site. Maybe sites you tried just offline?
Can you try ping for `21e:a51c:885b:7db0:166e:927:98cd:d186` and open it with `http://[21e:a51c:885b:7db0:166e:927:98cd:d186]` ?

**Comment by kt30015** [comment]
> `http://[21e:a51c:885b:7db0:166e:927:98cd:d186]` ?

WOOOOW, IT WORKS!!

Seems like all instructions i've found on russian are old. There are example site list from these instructions:
```
Search engine
http://[301:4541:2f84:1188:216:3eff:fe38:cefc]:8090/
MESH Forum
http://[303:60d4:3d32:a2b9::4]/
Node map
http://[21f:dd73:7cdb:773b:a924:7ec0:800b:221e]/
Hosts list
http://[300:529f:150c:eafe::1]/
Yggdrasil wiki
http://[203:e0b0:ec08:4e1f:f004:19a9:577a:90ba]/wiki/
```
