### ISSUE TITLE
please add translate to Pilish documentation and help

### ISSUE THREAD

**Issue by sp00ck** [yggdrasil-network/yggdrasil-go#876]
help files, web etc.

**Comment by ygguser** [comment]
Hi! There is a wiki on the Yggdrasil network.

http://[222:a8e4:50cd:55c:788e:b0a5:4e2f:a92c]/start
http://[222:a8e4:50cd:55c:788e:b0a5:4e2f:a92c]/yggdrasil:yggdrasil

There are already quite a lot of useful texts there. If you want, you can join to translate existing articles into your language and add your own articles.

You can contact [0n0n](https://matrix.to/#/@0n0n:matrix.org) and ask him to add languages you need. Or you can write here, I will tell him )

**Comment by neilalexander** [comment]
Not planned at this time.
