### ISSUE TITLE
Missing documentation for managing Yggdrasil (on Windows)

### ISSUE THREAD

**Issue by mlawren** [yggdrasil-network/yggdrasil-go#877]
I've read all of the documentation I can find on Yggdrasil, and appear to have successfully installed it on Windows: I can see the Yggdrasil network device is active. But how do I achieve the next logical steps? E.g:

1. What is the management interface? I.e. where are (presumably CLI) tools located?
2. If I add a Peer to $CONFIG_DIR/yggdrasil.conf how do I restart the interface?
3. What kind of example test could I run to check connectivity? I.e. ping a well-known yggrasil address?

For that matter, how do I do the above on Linux or any other OS?

Perhaps someone could point me to where this is documented (and close this issue) or else accept this issue as a documentation request.

**Comment by Vort** [comment]
Many answers are here:
https://yggdrasil-network.github.io/installation-windows.html
To test your installation you can
* `ping 21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb`
* Open [http://[21e:a51c:885b:7db0:166e:927:98cd:d186]/](http://[21e:a51c:885b:7db0:166e:927:98cd:d186]/)

**Comment by mlawren** [comment]
Ah, woops. I see now that page is linked from the general installation page. Thanks for the feedback and sorry for the noise.
