### ISSUE TITLE
Nothing Happens when I try to run yggdrasil with a custom config (MacOS)

### ISSUE THREAD

**Issue by CommandZomb** [yggdrasil-network/yggdrasil-go#878]
When I run sudo yggdrasil -useconf /private/etc/yggdrasil.conf, I would expect the startup processes to occur. Instead, terminal doesn't do anything and just kind of freezes.

**Comment by neilalexander** [comment]
You want `-useconffile`, not `-useconf`.

`-useconf` is expecting you to pipe in a config by standard input, which is why it appears to do nothing.

**Comment by CommandZomb** [comment]
Well it doesn't freeze now, and it's a different issue. 
panic: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 85,1 >>> }

**Comment by CommandZomb** [comment]
Never mind, fixed it by adding quotation marks. Now it's something about the .sock being in use.

**Comment by CommandZomb** [comment]
Anyways deleted it and now it runs smoothly. Problem now is that sudo yggdrasil -genconf doesn't show any peers

**Comment by neilalexander** [comment]
> Now it's something about the .sock being in use.

If the `.sock` is in use then you probably already have Yggdrasil running?

If you installed using the macOS `.pkg` then a launchd service was installed to run Yggdrasil in the background. You can stop it using `sudo launchctl stop yggdrasil`. 

> Problem now is that sudo yggdrasil -genconf doesn't show any peers

This is intentional. The blank config does not contain peers. You should add a small number of peers that are close to you: https://publicpeers.neilalexander.dev

**Comment by CommandZomb** [comment]
Oh I've already added a peer, so that's why I'm confused.

**Comment by neilalexander** [comment]
If you installed using the macOS package:

* A config file was already generated for you in `/etc/yggdrasil.conf`
* A launchd service unit was installed for you

To add peers, modify `/etc/yggdrasil.conf` and then stop and start it using `sudo launchctl stop yggdrasil` and then `sudo launchctl start yggdrasil`.

You should then be able to see your peers connected if you do `sudo yggdrasilctl getPeers`.

**Comment by CommandZomb** [comment]
When i use getpeers, nothing happens. the line just breaks.

**Comment by neilalexander** [comment]
That implies no peers are connected.

If you already modified `/etc/yggdrasil.conf` to add peers then the other thing you can try is `sudo killall yggdrasil`, which is a bit more extreme, but launchd should restart it.

You can check that it is running by doing `ps -ef | grep yggdrasil`.

**Comment by CommandZomb** [comment]
Got them after running killall then using the launched command. Thank you so much!
