### ISSUE TITLE
Sanity-check config

### ISSUE THREAD

**Issue by Arceliar** [yggdrasil-network/yggdrasil-go#88]
If there's an error in the config file, such as a field where the value with an incorrect type is used, this cause an error to be returned by the parser. Currently, no attempt is made to check the error and deal with it gracefully, we just `panic(err)`.

There may be some cases when we can recover (if it's an obvious mistake) or continue running with a sane default (and warn the user instead of crashing).

**Comment by neilalexander** [comment]
A lot of this is captured by `-normaliseconf` so will close this for now.
