### ISSUE TITLE
DNS in Chrome

### ISSUE THREAD

**Issue by 174n** [yggdrasil-network/yggdrasil-go#883]
Chrome doesn't resolve DNS queries to the yggdrasil addresses while firefox does. I found one solution to this problem, you might consider adding this for everyone by default

>Add a network route to ```2001:4860:4860::8888```. Doesn't have to actually be functional (could just drop requests to it). As long as Chrome can connect a UDP socket to the address, it will pass the heuristic checking IPv6-connectivity.

https://chromium.googlesource.com/chromium/src/+/refs/heads/main/net/dns/README.md

**Comment by Jan69** [comment]
works just fine with chromium for me, how can you run yggdrasil WITHOUT having a route, anyway?

**Comment by 174n** [comment]
The ipv6 addresses are being resolved correctly, but if I add an ip as AAAA DNS record it won't resolve in chrome. The DNS server was only added to the yggdrasil interface. You can try some from here, they won't work in chrome https://yggdrasil-network.github.io/services.html#dns

**Comment by zhoreeq** [comment]
In practice, Google only allows "normie" web for Chrome users. It's beyond repair.

The only working solution is to use FF rn, or you can try some fork like Brave.

**Comment by 174n** [comment]
> In practice, Google only allows "normie" web for Chrome users. It's beyond repair.
> 
> The only working solution is to use FF rn, or you can try some fork like Brave.

Can't just ```2001:4860:4860::8888``` route be added? It can just drop requests to it (ss long as chrome can connect a UDP socket to the address), but it would be enough for DNS to function? I can't imagine someone switching their browser just because of yggdrasil. And yggdrasil is so easy to install (especially on windows) so even "normies" can potentially use it. Yggdrasil is such a great technology, the community shouldn't cripple it just because their don't like some things "normies" use. Yggdrasil isn't focused on privacy anyway I think.

**Comment by ansuz** [comment]
I believe chrome/chromium/similar-browsers  can be launched with `--enable-ipv6`. This is [an old bug](https://bugs.chromium.org/p/chromium/issues/detail?id=85786) that was known in the early days of cjdns development.

Now that more networks support ipv6 natively I think fewer people are likely to affected by this (I am not).

**Comment by neilalexander** [comment]
Closing as this is an environmental issue.
