### ISSUE TITLE
`-address` and `-subnet` command line switches need descriptive error message if used without `-useconffile`

### ISSUE THREAD

**Issue by iav** [yggdrasil-network/yggdrasil-go#884]
`-address` and `-subnet` command line swiches not work

yggdrasil 0.4.2, installed as `.deb` on `aarch64` platform.

**Comment by neilalexander** [comment]
Did you also supply `-useconffile` to point it to the config to get the address/subnet from?

**Comment by iav** [comment]
No. Should I?
I want to get node address and network to get it inside bash script and pass to other tools. Without knowledge about configuration.
To be honest — I'd prefer to see it from yggdrasilctl. It looks more clear.
yggdrasilctl don't ask for any "context"... 
is it possible "just to know current ygg properties of "this" node"? 
to use it like 
```
P=$(echo 301:aaa:bbbb:ccc::/64|sed -E "s/(.*):\/([0-9]+)/\1:1\/\2/gi"); echo $P
301:aaa:bbbb:ccc::1/64
```
then in script something like
```
YNET=$(yggdrasilctl -getNetwork)
GW=$(echo $YNET|sed -E "s/(.*):\/([0-9]+)/\1:1\/\2/gi")
YPREF=$(echo $YNET|sed -E "s/:\/([0-9]+)/\1/gi")
YSTART=$(echo $YNET|sed -E "s/(.*):\/([0-9]+)/\1:100/gi")
ip addr add $GW eth0
echo "dhcp-range=tag:ygg,$YSTART[, ra-names, $YPREF, 36h" >> dnsmasq.yggdhcp.conf
```

**Comment by neilalexander** [comment]
> No. Should I?

The `-address` and `-subnet` flags are for getting the information out of a supplied config file even if Yggdrasil isn’t running yet, so you need to specify them *in combination with* `-useconffile`, but obviously that requires you to know the path to the config file.

> To be honest — I'd prefer to see it from yggdrasilctl. It looks more clear.

Sure, you can do that too — `yggdrasilctl getSelf`, or if you want it in JSON format instead, `yggdrasilctl -json getSelf` — but this requires the Yggdrasil node to be running.

**Comment by iav** [comment]
Then seems 2 separate topic:
1. `-address` and `-subnet` command line switches need descriptive error message if used without `-useconffile`
2. `yggdrasilctl getSelf` shoiuld allow to get address and subnet in good form for shell script, where json not fit.

**Comment by solanav** [comment]
Is it better that these show an error when `-useconffile` is not used or is it better that we add `/etc/yggdrasil.conf` as a default to `-useconffile`? Although the second option may be worse for multiplatform stuff.
