### ISSUE TITLE
question: DNS lookup in isolated network

### ISSUE THREAD

**Issue by fps** [yggdrasil-network/yggdrasil-go#886]
Hi,

I'm aware that yggdrasil is aimed at transport/routing and name resolution is out of scope. I just wonder how other people solve name lookup in their networks? So this is strictly aimed at local name resolution (local in the sense that only nodes under my control need to be able to lookup each other - and I also try to keep my network isolated from the main net.)

The simplest would be to maintain a hosts file on all nodes which is highly annoying :)

It would also be possible, I guess, to just have a normal DNS like bind run on a privileged node and have all other nodes use that DNS. That would make life a little bit easier on the other nodes as you would have the names managed centrally. But still a little bit of work which I'm not ready to undertake yet.

Is there a simpler solution? I tried avahi-daemon and explicitly telling it to use tun0 as well, but it doesn't seem to want to play along - it basically just ignores the tun0 interface. And I'm not sure it would work at all anyways since it required multicast.

**Comment by cofob** [comment]
You can try [Alfis](https://github.com/Revertron/Alfis) (small memory and disk footprint) or [EmerDNS](https://emercoin.com/en/emerdns) (large blockchain but simplier to add a new domain, largely supported, for example, on opennic servers).

**Comment by fps** [comment]
Hi! Thanks for the suggestions! Both of these try to solve a larger problem though.

I'm in the process of thinking up a simpler, purely local (local wrt. nodes under one's control) solution.

I'll leave this issue open for now. Maybe there is another solution.

**Comment by fps** [comment]
I played around with ygdrasil a little and came up with this: https://github.com/fps/yggdrasil-go/tree/derived-keys

In that branch of that fork if two nodes share the same private key (and have MixinHostname set to true in their config), they can lookup each other's IP address like this:

on host_a:

<pre>
sudo ./yggdrasil -useconffile conf -hostname  host_b -address
201:d90e:e8ae:9095:1774:c69a:880e:a8ec
</pre>

on host_b:

<pre>
sudo ./yggdrasil -useconffile conf -hostname  host_a -address
200:8402:6332:d1e0:e5f7:dfaa:da5a:50f0
</pre>

(actually since both use the same private key, it doesn't matter on what host the lookup is done)..

**Comment by marek22k** [comment]
You could also try Meshname (https://github.com/zhoreeq/meshname/). Namecoin is something like Emercoin, but due abuse Opennic doesn't support it anymore.

**Comment by fps** [comment]
I'm goibg with an yggdrasil fork with my hacky mdns support built in.. but thanks for the suggestions!
