### ISSUE TITLE
An error occured starting TUN/TAP: file exists [BUG][SOLUTION]

### ISSUE THREAD

**Issue by proukornew** [yggdrasil-network/yggdrasil-go#887]
#530 years have passed, but u didn't fix this bug.
Yggdrasil tries to manage unmanaged interface by itself. But there are others entities to do this job. ​e.g. Openwrt system has race condition on ygg0 static configuration. (9/10 runs An error occured starting TUN/TAP: file exists)

Please, make config's option to skip this job.
The bug  is located [here](https://github.com/yggdrasil-network/yggdrasil-go/blob/1c7deb72db461ee4c1ec96137b9242fb6acd1837/src/tuntap/tun.go#L135):

```
if err := tun.setup(tun.config.IfName, addr, mtu); err != nil {
		return err
	}
	if tun.MTU() != mtu {
		tun.log.Warnf("Warning: Interface MTU %d automatically adjusted to %d (supported range is 1280-%d)", tun.config.IfMTU, tun.MTU(), MaximumMTU())
	}
	tun.rwc.SetMTU(tun.MTU())
	tun.isOpen = true
	tun.isEnabled = true
	go tun.read()
	go tun.write()
	return nil
```
Return error and skip all useful stuff without Panic... lolwut?
try something like that:
```
if err := tun.setup(tun.config.IfName, addr, mtu); err != nil {
		if err != "file exists" {
                    return err
                }
	}
```

**Comment by neilalexander** [comment]
AFAIK this is not a problem anymore, please reopen if it is.
