### ISSUE TITLE
How to delete Yggdrasil? 

### ISSUE THREAD

**Issue by Ximeron** [yggdrasil-network/yggdrasil-go#893]
When I try to reinstall yggdrasil by deleting files from Windows 10, it's no longer possible to install it again. Error: 
Verify that yuo have suffisient privileges to start sistem services. Installation is possible only after reinstalling Windows.

**Comment by neilalexander** [comment]
You should uninstall Yggdrasil the same way you uninstall anything else MSI-based — using the Control Panel or Settings app. It's not recommended to just delete files without uninstalling properly.
