### ISSUE TITLE
question: yggdrasil as a decentralized vpn

### ISSUE THREAD

**Issue by vdloo** [yggdrasil-network/yggdrasil-go#899]
Hi, I've been messing with yggdrasil this weekend and there are some questions I've been wondering about. My use case is that I run a bunch of VMs in my homelab in different configurations where they are either in different subnets where not all VMs can reach each other, or those VMs can't talk to their Hypervisor directly because of macvtap. Anyway the constant is that at least some machine can connect to any machine and there's always a way to connect albeit indirectly.

For that purpose Yggdrasil sounds great. An IPv6 overlay network without a centralized VPN server, completely self-hosted, isolated and with no route specific configuration. I've used cjdns in the past for this but in cjdns there's is a clear distinction between cjdns the software and hyperboria the public network that you can connect to using cjdns. You can run your own nodes just fine and never connect to any public peers and you just have your own small 'private' mesh overlay network then. For Yggdrasil this looks the same as far as I can tell but from the site and documentation this appears to be a less common use-case and the focus seems to be on connecting to 'the' network. On the site it says:

> Will my machine be exposed to other users of the network?
> Typically yes, you will be routable from other nodes on the network. If you want to restrict incoming connections to your machine, you should use an IPv6 firewall. The steps for this will vary from platform to platform.

https://yggdrasil-network.github.io/faq.html

Having a firewall in place is good practice anyway, but in my context of a homelab where I'm experimenting with all kinds of services it's a huge hassle to make sure everything is locked down to the fullest extent (to the level as if each machine was directly exposed to the internet). So in my use case I would never want to connect to a public network. So I wanted to ask some questions that I hope can clarify some things for me:

- When my nodes only peer with each other there is no risk of somehow automatically being connected to a public network right? As long as I know that none of the peers do peer to a wider network (because I control all the peers).

Here in https://github.com/yggdrasil-network/yggdrasil-go/issues/853 it says:

> 'make sure you only peer to your own nodes, using AllowedPublicKeys to restrict peerings to your own nodes as appropriate

 but that isn't strictly necessary if you are in control of all nodes that you peer with and none of those peer to a wider network right? As long as Multicast is disabled that is.

- If MulticastInterfaces is empty `MulticastInterfaces": []` there won't be any autodiscovery right? In my case I want to run multiple instantiations of 'vm platforms' with their own separate yggdrasil networks on the same network. Or does it have to be set to: `"MulticastInterfaces": [{"Regex": ".*", "Beacon": false, "Listen": false, "Port": 0}]` for that?

From: src/config/config.go
> MulticastInterfaces []string `comment:"Regular expressions for which interfaces multicast peer discovery\nshould be enabled on. If none specified, multicast peer discovery is\ndisabled. The default value is .* which uses all interfaces."`

Or does it have to be `"MulticastInterfaces": null` in json?

In https://github.com/yggdrasil-network/yggdrasil-go/issues/875 mutual authentication with a common key is mentioned, that sounds like a great idea to lock things down a bit more for people with a use case similar to mine and rule out the risk of accidentally peering to a wider network because of a misconfiguration.

**Comment by perguth** [comment]
I had a similar problem:

- I often start local services and open ports for development purposes
- I want to use Yggdrasil to connect those machines
- But I also want to connect to the wider network
- But I do not want to expose those open ports

In the end I solved it by locking down incoming traffic with UFW and then having a script do the whitelisting and `AllowedPublicKeys` syncing for me: https://github.com/perguth/yggdrasil-protected-group

**Comment by neilalexander** [comment]
Closing as v0.5 will have optional mutual peer authentication and I'm not sure this needs engineering further.
