### ISSUE TITLE
OCI containers?

### ISSUE THREAD

**Issue by shdwchn10** [yggdrasil-network/yggdrasil-go#903]
I build [OCI containers for yggdrasil](https://gitlab.com/oci-containers/yggdrasil-go) with GitLab CI. These OCI images give [automatic rollbacks](https://www.redhat.com/sysadmin/podman-auto-updates-rollbacks) for failed automatic updates with podman. They don't offer any benefit for Docker because AFAIK Docker doesn't support automatic rollback.

Are developers interested in having [my buildah script](https://gitlab.com/oci-containers/yggdrasil-go/-/blob/main/build.sh) included in the upstream CI/CD process? I'd like to integrate it, but I understand if it's not needed for upstream.

**Comment by zhoreeq** [comment]
This info could be added to the [website repository](https://github.com/yggdrasil-network/yggdrasil-network.github.io)

Can somebody create a documentation page about Docker and other containerized solutions?

**Comment by neilalexander** [comment]
It might be worth trying to get something like this into GitHub Actions so we can build OCI containers using CI.
