### ISSUE TITLE
(Solved) Error loading wintun.dll DLL: Unable to load library: The parameter is incorrect.

### ISSUE THREAD

**Issue by HappinessIsImportant** [yggdrasil-network/yggdrasil-go#906]
Hi all. Please fix for Windows 7. 

I have KB2921916 for 64-bit

 C:/Users/appveyor/ not exist on this PC.

**With admin account:**

C:\Program Files\Yggdrasil>yggdrasil -useconffile yggdrasil.conf
2022/03/23 15:14:29 Build name: yggdrasil
2022/03/23 15:14:29 Build version: 0.4.3
2022/03/23 15:14:29 Starting up...
2022/03/23 15:14:29 Startup complete
2022/03/23 15:14:29 Starting multicast module
**panic: Error loading wintun.dll DLL: Unable to load library: The parameter is incorrect.**

goroutine 16 [running]:
golang.zx2c4.com/wireguard/tun/wintun.(*lazyProc).Addr(...)
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-202110170
52713-f87e87af0d9a/tun/wintun/dll_windows.go:58
golang.zx2c4.com/wireguard/tun/wintun.CreateAdapter({0xc0000a6f10, 0xc0001215b8}
, {0x6d939d, 0x9}, 0xc000121628)
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-202110170
52713-f87e87af0d9a/tun/wintun/wintun_windows.go:86 +0x1a5
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID({0xc0000a6f10, 0xa7d0e
9c41f06ebb2}, 0x6e664c, 0xcf39)
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-202110170
52713-f87e87af0d9a/tun/tun_windows.go:71 +0x46
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup.func1()

        C:/projects/yggdrasil-go/src/tuntap/tun_windows.go:34 +0xb1
golang.zx2c4.com/wireguard/windows/elevate.DoAsSystem(0xc000121ac8)
        C:/Users/appveyor/go/pkg/mod/golang.zx2c4.com/wireguard/windows@v0.4.12/
elevate/doas.go:114 +0x622
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0x6d850
0, {0xc0000a6f10, 0xc000059ca0}, {0xc00000b5f0, 0x2}, 0xc000059c28)
        C:/projects/yggdrasil-go/src/tuntap/tun_windows.go:27 +0x176
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start(0xc000
078000)
        C:/projects/yggdrasil-go/src/tuntap/tun.go:135 +0x2b4
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start.func1()

        C:/projects/yggdrasil-go/src/tuntap/tun.go:108 +0x26
github.com/Arceliar/phony.Block.func1()
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-202102092
35338-dde1a8dca979/actor.go:80 +0x26
github.com/Arceliar/phony.(*Inbox).run(0xc000078048)
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-202102092
35338-dde1a8dca979/actor.go:89 +0x34
created by github.com/Arceliar/phony.(*Inbox).restart
        C:/Users/appveyor/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-202102092
35338-dde1a8dca979/actor.go:121 +0x5b

**Attempt without admin account:**

C:\Program Files\Yggdrasil>yggdrasil -useconffile yggdrasil.conf
2022/03/23 15:17:14 Build name: yggdrasil
2022/03/23 15:17:14 Build version: 0.4.3
2022/03/23 15:17:14 Starting up...
2022/03/23 15:17:14 Startup complete
2022/03/23 15:17:14 Starting multicast module
2022/03/23 15:17:14 **An error occurred starting TUN/TAP: Access is denied.**
2022/03/23 15:17:14 Your public key is ( ....... ok )
2022/03/23 15:17:14 Your IPv6 address is ( ....... ok )
2022/03/23 15:17:14 Your IPv6 subnet is ( ....... ok )
2022/03/23 15:17:14 TCP admin socket listening on 127.0.0.1:9001

For linux works perfectly after
`modprobe -v --first-time ipv6`

**Comment by Vort** [comment]
Do not know if it will help someone:
Yggdrasil works on my PC with Windows 7 SP1 x64.
However, I have unusual configuration:
yggdrasil.exe 0.4.0-30-gf92d812 (8439d0b24fac091db44e32cc53166349)
wintun.dll 0.11 (6e3c2ff630fbe36cece3c709352113f5)
wintun.sys 0.14 (43d91124fe8112d0027842824dad7326)

**Comment by HappinessIsImportant** [comment]
Problem solved. I can enter this website http://[319:3cf0:dd1d:47b9:20c:29ff:fe2c:39be] ( and other, which are online ) in Windows 7 64 ( also works in: Linux PC, Smartphone (with help of apk, version 0.1 and network 0.4.0) )
 
**I disclaim all responsibility: if someone breaks their computer or any other damage occurs, including loss of data,  because of my instructions. I won't be responsible for that.**   I suggest, to read all of this text before you follow this instructions

Need to intall:

Windows6.1-KB3063858-x64 + reboot
windows6.1-KB4474419-v3-x64  + reboot

Open regedit.exe and find 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
if "DisabledComponents" exists, delete it ( if changes have been made, a PC restart is most likely required )


I downloaded the latest version of the wintun.dll file from the https://wintun.net  and put the x64 version in many folders:
1) Folder with this project
2) C:\Windows\system32\drivers\
3) C:\Windows\system32\ 
4) C:\Windows\

I also installed the WireGuard VPN client and I got wintun.sys


,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

( You can skip this step )

Also, successfully compiled development version from github
To do this you need to download the compiler, add go.exe to the environment path.

Download https://git-scm.com/download/win . My choice PortableGit 64-bit.7z.exe
Open git-bash.exe
cd D:\folder_with_yggdrasil_source_code
./build
Copy new files yggdrasil.exe and yggdrasilctl.exe to the folder with project 

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

Also, I copied cmd.exe into the folder with the project for ease of use. I wrote a *.bat script 
yggdrasil.exe -useconffile D:\path\to\yggdrasil.conf
Next, right click on cmd.exe: Run from an admin account
write the first part of the script file name and then press TAB (to autocomplete the command)


Here are some of the errors I encountered, and if you follow the recommendations that are written above, then yggdrasil-0.4.3-2-g6c4778b-windows-amd64.exe + correct config file should work.

( for search )

Build name: yggdrasil
Build version: 0.4.3-2-g6c4778b
Starting up...
Startup complete
Starting multicast module
TCP admin socket listening on 127.0.0.1:9001
Installing driver 0.14
Extracting driver
Installing driver
Creating adapter 
Connected TLS: 200:(secret)@15(secret), source 192.168.(secret)
Failed to setup adapter (problem code: 0x34):   
(Code 0x0000048C)
An error occurred starting TUN/TAP: Error creating interface:
The indicated device requires reinitialization due to hardware errors

another error:

.... text......
Using existing driver 0.14
Creating adapter
Failed to set up TUN address: Element not found.
An error occurred starting TUN/TAP: Element not found.
