### ISSUE TITLE
Logging settings inside yggdrasil.conf

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [yggdrasil-network/yggdrasil-go#908]
At the moment, this is set by a key `-logto` in the service https://github.com/yggdrasil-network/yggdrasil-go/blob/620b901473dd864b7c0c461b001cc38c36776de8/contrib/msi/build-msi.sh#L163
It's not very convenient. Please move the logging settings inside yggdrasil.conf

**Comment by beryll1um** [comment]
I can implement it. Contributors, can approve a feature?

**Comment by zhoreeq** [comment]
> It's not very convenient. Please move the logging settings inside yggdrasil.conf

Why?

**Comment by 0x4E69676874466F78** [comment]
@zhoreeq because if I want to turn off logging (or change path) I have to get into the registry where to change the service.
I expect to see logging settings in the config.
Settings must be set in one place and the service configuration is not the right place (counter question: why not store the yggdrasil settings in the registry then? I'm not suggesting this just for thought).


@beryll1um thanks.

**Comment by zhoreeq** [comment]
@0x4E69676874466F78 It works perfectly fine for Linux, no reason to change it. 

Windows users should not manually edit config files, but use a GUI application wrapper for convenience. There are a few at github already.

**Comment by beryll1um** [comment]
> @0x4E69676874466F78 It works perfectly fine for Linux, no reason to change it. 
> 
> Windows users should not manually edit config files, but use a GUI application wrapper for convenience. There are a few at github already.

Are we making life harder for windows users with this change?  Another reason to do it =)

Seriously, I don't think it's a big problem.
Unless we can do what I was talking about initially. Leaving the option to configure it from arguments, which doesn't seem like a very good solution to me.

**Comment by andrius4669** [comment]
aaaaaa please don't

**Comment by neilalexander** [comment]
For now we'll leave this as-is so we can control the log level whilst using `-autoconf`.
