### ISSUE TITLE
"Server indicated a failure" when making a request to the key

### ISSUE THREAD

**Issue by stemy2** [yggdrasil-network/yggdrasil-go#912]
Hello,

The command "gpg --fetch-keys https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt" is not working, and i get the message "Server indicated a failure". Strangely, i can download the file with my browser.

**Comment by neilalexander** [comment]
This is hosted on a regular S3 bucket and not something we control at the infrastructure level so not really sure what we can do here. Please reopen if still a problem.
