### ISSUE TITLE
Ubuntu, unable to start no matter what. 

### ISSUE THREAD

**Issue by Dry-Leaf** [yggdrasil-network/yggdrasil-go#917]
I first installed yggdrasil from the repository as described here 
https://yggdrasil-network.github.io/installation-linux-deb.html

I got this error message 
>yggdrasil.service: Scheduled restart job, restart counter is at 5.
>Stopped yggdrasil.
>yggdrasil.service: Start request repeated too quickly.
>yggdrasil.service: Failed with result 'exit-code'.
>Failed to start yggdrasil.

So then I tried building from source, as described here 
https://yggdrasil-network.github.io/installation-linux-other.html
and I got the same error message.

**Comment by mkb2091** [comment]
Do you have the config/have it in the right place, that can cause it to be unable to start
