### ISSUE TITLE
Manual routing data entry

### ISSUE THREAD

**Issue by nerd36** [yggdrasil-network/yggdrasil-go#919]
To yggdrasil work on international internet cut-off in my country, users should be able to enter real IP address of peer, too, because the routing table DHT bootstrapping server wouldn't be accessible.

**Comment by nerd36** [comment]
But I don't know if users really do that or not (exchanging they IP)

**Comment by neilalexander** [comment]
There is no “bootstrap server” or DHT-based peer discovery, you just configure static peers and Yggdrasil will use them. You can do this either by IP address or DNS name.
