### ISSUE TITLE
Linux: ufw blocks broadcast of local peers

### ISSUE THREAD

**Issue by derpindialer** [yggdrasil-network/yggdrasil-go#921]
I run ygg on linux, and use ufw. It seems that ufw blocks the broadcast of the local peers, so if I leave the peers blank in my config, it won't connect to any of my other local peers. Is there a specific port/rule I should add to ufw to allow local peering?

**Comment by neilalexander** [comment]
There's two things to allow: the multicast beacons and the incoming connection port.

The multicast beacons are always sent to `ff02::114` UDP port `9001`.

The incoming connection port depends on what you've configured in the `Port` setting in `MulticastInterfaces` section of your config. It's probably set to `0` by default which means it will select a random port, so you'll probably set a static port number of your choosing and then allow incoming connections to that port, e.g. TCP/12345:
```
  MulticastInterfaces:
  [
    {
      Regex: en.*
      Beacon: true
      Listen: true
      Port: 12345
    }
  ]
```

**Comment by derpindialer** [comment]
Thank you, that worked!
