### ISSUE TITLE
go mod vendor failed (0.4.3 version)

### ISSUE THREAD

**Issue by Pro-pra** [yggdrasil-network/yggdrasil-go#922]
Hi,
i run 'go mod vendor' command, and its fail
`golang.zx2c4.com/wireguard/rwcancel
internal error: failed to find embedded files of golang.zx2c4.com/wireguard/rwcancel: //go:build comment without // +build comment
`
may need another source wireguard?

**Comment by Pro-pra** [comment]
$ go version
go version go1.16.7 linux/amd64

**Comment by neilalexander** [comment]
Can you please try Go 1.17? This seems to be a problem in a dependency.

**Comment by Pro-pra** [comment]
Thank you, update golang help me.
