### ISSUE TITLE
core: add an api to block until the node is "stabilized"

### ISSUE THREAD

**Issue by Jorropo** [yggdrasil-network/yggdrasil-go#923]
I have tests for my libp2p transport here: [github.com/Jorropo/go-pin-argente/blob/main/pin_argenté_test.go](https://github.com/Jorropo/go-pin-argente/blob/main/pin_argent%C3%A9_test.go).

They works because they just spin up two nodes in the same process and then peer over localhost.

If I try with a non localhost peering node that both connect to, the tests fails because calls to `Dial` / `WriteTo` are lost since they happen before the yggdrasil nodes are in the network.

I have to add a `time.Sleep(time.Second * 5)` between the node creations and the actual test.

I would like a `(*core.Core).Ready(context.Context)` method which blocks until the node has been registered in the root node's DHT.

**Comment by Jorropo** [comment]
A `(*core.Core).Ready() <-chan struct{}` might be better for API that want to block on more than one thing (*`select`*).

**Comment by neilalexander** [comment]
Closing as there's no good definition for what "stabilised" really means.
