### ISSUE TITLE
Prefer connecting to a local multicasted node over connecting the remote but same one

### ISSUE THREAD

**Issue by ZeroAurora** [yggdrasil-network/yggdrasil-go#928]
I use yggdrasil for connecting back home. To achieve that, I configured a NAT tunneling (for a lack of a server) on my RPi and configured my nodes to peer with the address exposed to the internet.
It's great, except that when two nodes are in a local network, my devices sometimes connect with RPi directly, but it's more often for the devices to connect to the remote address which is a tunnel to my RPi. This causes much unnecessary lantency.
I wonder if there is a way to give local connections a high priority, or if there is a way to fix this if it's a weird thing.

**Comment by neilalexander** [comment]
Closing as `?priority=` in `Listen`/`Peer` is designed for this purpose.
