### ISSUE TITLE
How to use yggdrasil with vpn in same time?

### ISSUE THREAD

**Issue by connected201** [yggdrasil-network/yggdrasil-go#931]
hi, i have problem, when my VPN is enabled (mullvad vpn) yggdrasil not working, to access yggdrasil address, i need to turn off my VPN.

**Comment by neilalexander** [comment]
It is a known issue that the Mullvad app interferes with Yggdrasil and other VPNs as it adds system firewall rules to prevent traffic leaking (I think they call it “kill switch”). See if you can adjust the settings of your Mullvad client or consider using the regular Wireguard or OpenVPN clients to connect to Mullvad instead.

**Comment by Mikaela** [comment]
You can also run the command with `mullvad-exclude` to have it bypass VPN and be compatible with Yggdrasil.

E.g. `mullvad-exclude curl ...`
