### ISSUE TITLE
The network is not able to recover after I shutdown the root

### ISSUE THREAD

**Issue by Jorropo** [yggdrasil-network/yggdrasil-go#934]
When I shutdown the root, instead of a new root being found, it seems like nodes are chasing false very long coordinates paths:
```
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 9
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 35 6
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 7
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 23 12
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 6
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 108 11
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 28 6 63
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 42 2
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 251 12 170
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 3
1 2 4 387 7 286 62 612 623 9 213 6 18 177 598 98
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 129
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 126
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 219 34
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 35 2
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 12
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 98 9
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 173 7 111
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 95 5
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 4
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 147 16
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 251 11
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 8 16 19
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 251 12 227
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 10
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 60 1
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 8 4 13
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 274 30 7
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 82 1
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 111 20
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 162 2
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 60 26
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 1050 53 24
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 162 5
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 2
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 162 1
1 2 4 387 7 286 62 612 623 9 213 6 18 180 26 98 80 270 251 12
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 173 7 123
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 35 6
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 35 3
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 60 29
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 35 4

1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 98 33
1 2 6 145 28 48 300 1432 58 39 4 90 2 94 41 61 13
```
```
1 2 4 387 7 286 62 612 623 9 213 6 18 177 598 98 74 98 16 1110 58 34 52
1 2 4 387 7 286 62 612 623 9 213 6 18 177 598 98 74 98 16 1110 58 34 167
```
Thoses are examples coordinates I found with `getpeers`.
If I make a `watch "yggdrasilctl getpeers | sort"` the coordinates often flash in sync and regularly update to new (generaly longer routes).

While this is happening I cannot make any `> 1` hop connection.

This state has been happening for > 1h30 at this point. (I restarted the node shortly to see if it would fix it, and it did, but it went bad again after I stopped it, me running a node forever isn't a very good solution).

**Comment by jorektheglitch** [comment]
Hm, I remember same problem was in Yggdrasil 0.3.x
In russian community it was called "storms", and the main explanation was the circulating waves of root update messages that makes node's coords update over and over again. And in case of coords updates no new route can be established, even route to your peer (theese cases was reported by some users).

Theoretically, source routing in Ygg 0.4 had to make already established routes resistant to storms...

**Comment by Jorropo** [comment]
> the main explanation was the circulating waves of root update messages that makes node's coords update over and over again

Looks a lot like what I was seeing.

> Theoretically, source routing in Ygg 0.4 had to make already established routes resistant to storms...

I have not tested this, what I tested is with new unestablished routes.

**Comment by neilalexander** [comment]
May be improved/fixed in [1de587a](https://github.com/yggdrasil-network/yggdrasil-go/commit/1de587a971ee2f93d7e7d8b6fd894f32458590cd) but needs testing.

**Comment by Jorropo** [comment]
@neilalexander do you want me to update and shutdown the root again ?
See what happen after an hour ?

Or does this need many nodes in the network to update first ?

**Comment by Jorropo** [comment]
cc @Arceliar same question

**Comment by neilalexander** [comment]
Closing as this logic will be completely different in v0.5.
