### ISSUE TITLE
yggdrasil.conf, Listen: [] when containing port ":0" then only first line is used

### ISSUE THREAD

**Issue by slrslr** [yggdrasil-network/yggdrasil-go#948]
Debian package, 0.4.3-2~bpo11+1

yggdrasil.conf
```
Listen: [
  tls://[::]:123456
  tcp://[::]:123457
]
```

When i have used ":0" port for both lines , it caused only one be used and automatic port was assigned:

> Listening for TLS on: [::]:40859

but when manually defined ports for both (:123456, :123457), then:

> Listening for TLS on: [::]:123456
> Listening for TCP on: [::]:123457

I have confirmed opened port/s using netstat.

I think that yggdrasil should have opened not 1 but two ports, in case port ":0" is defined for tcp and tls:
```
Listen: [
  tls://[::]:0
  tcp://[::]:0
]
```
when i change order of that lines in yggdrasil.conf so first is tcp listen one and then tcp one, then the TCP is opened and TLS not.

**Comment by neilalexander** [comment]
I think this is already fixed on `develop` by the link refactoring — can you please try [this build](https://nightly.link/yggdrasil-network/yggdrasil-go/actions/runs/3118138164)?

**Comment by slrslr** [comment]
I do not know right commands to do it, so ran:
apt remove yggdrasil
apt install ./yggdrasil-develop-0.4.4-22-gb67c313-amd64.deb
```
Generating initial configuration file /etc/yggdrasil.conf
Please familiarise yourself with this file before starting Yggdrasil
N: Download is performed unsandboxed as root as file '/root/yggdrasil-develop-0.4.4-22-gb67c313-amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```
 systemctl restart yggdrasil*
```
Failed to restart yggdrasil-develop-0.4.4-22-gb67c313-amd64.deb.service: Unit yggdrasil-develop-0.4.4-22-gb67c313-amd64.deb.service not found.
Failed to restart yggdrasil.conf.service: Unit yggdrasil.conf.service not found.
```
ls /etc/init.d|grep y
```
chrony
one-context-reconfigure-delayed
rsync
rsyslog
```

Already copied modified yggdrasil.conf in place.
Which commands to run now to start service?

**Comment by neilalexander** [comment]
Do `sudo dpkg -i yggdrasil-develop-0.4.4-22-gb67c313-amd64.deb` instead?

**Comment by slrslr** [comment]
You are right, this issue is fixed and can be closed. Thank you

Btw. yggdrasil installed yours mentioned way exits with error:

> Admin socket failed to listen: listen unix /var/run/yggdrasil/yggdrasil.sock: bind: no such file or directory
> yggdrasil.service: Main process exited, code=exited, status=1/FAILURE
> tun1: Failed to query device driver: No such device
> tun1: Failed to get link config: No such device
> Starting OpenNebula delayed reconfiguration...

indeed /var/run/yggdrasil/ does not exist, which reminds me this open issue https://github.com/yggdrasil-network/yggdrasil-go/issues/946#issuecomment-1255617018
