### ISSUE TITLE
addpeer, removepeer missing from admin socket

### ISSUE THREAD

**Issue by ehmry** [yggdrasil-network/yggdrasil-go#950]
I'd like to add and remove peers from a running yggdrasil instance. I remember this being a feature but it seems to have been removed?

Basically I want my init system to start a minimally configured yggdrasil and then delegate the further configuration. I can think of a few ways this would be useful:
- I want an address to bind to *as soon as possible* during boot.
- Find peers using DNS service discovery where multicast discovery isn't possible (Freifunk) - without adding the DNS SD logic to yggdrasil-go.
- Peer ~~auto-discovery~~ optimization, I'd like to have the option to dynamically add and remove peers by estimating the physical distance of known public peers. I don't know how I would do that but I can't experiment without being able to externalise that logic.

More configuration options exposed through the control socket is better. It may seem like a feature that people aren't using, but regardless I think it's the state-of-the-art way to do configuration.

**Comment by ehmry** [comment]
Looking at the source I see that it didn't survive a refactor but it will return at some point.

**Comment by vikulin** [comment]
This is also useful for UI building which allows to add and remove peers in runtime.
