### ISSUE TITLE
Fallback to other addresses of hostname in Peers URLs

### ISSUE THREAD

**Issue by lukaslihotzki** [yggdrasil-network/yggdrasil-go#956]
`tcp://` and `tls://` peer URLs can use hostnames instead of IP literals. However, such names are resolved by `net.ResolveTCPAddr` in [tcp](https://github.com/yggdrasil-network/yggdrasil-go/blob/develop/src/core/link_tcp.go#L38) and [tls](https://github.com/yggdrasil-network/yggdrasil-go/blob/develop/src/core/link_tls.go#L54). [ResolveTCPAddr](https://pkg.go.dev/net#ResolveTCPAddr) is not recommended for resolving names, "because it will return at most one of the host name's IP addresses."

Yggdrasil should resolve all addresses for a name and fall back to the next one if connection establishment is rejected or times out. This is especially useful for outgoing connections to hosts reachable by both IPv4 and IPv6, when only either IPv4 or IPv6 is available.

**Comment by lukaslihotzki** [comment]
The dialer already does the correct thing when passing the name as argument instead of resolving it manually before. However, the resolved IP is needed as input for dialerFor, so the correct local address can be chosen from the source interface. I'd suggest to instead try all possible 4 dialers that can occur (v4/v6 and global/link-local) if a source interface is set.

**Comment by neilalexander** [comment]
Closing as fixed.
