### ISSUE TITLE
Something strange with Listeners

### ISSUE THREAD

**Issue by ygguser** [yggdrasil-network/yggdrasil-go#960]
In the configuration file I have `AdminListen: none`

And in the Listen section I have:
```
[
      tcp://192.168.1.15:22854
      unix:///var/run/yggdrasil.sock
]
```

In the Peers section i have:
```
Peers:
     [
       tcp://188.225.9.167:18226
    ]
```

`sudo netstat -natup | grep yggdrasil`
```
...
tcp6       0      0 fe80::8c63:de15:b:40555 :::*                    LISTEN      621/yggdrasil       
tcp6       0      0 fe80::8c63:de15:b:40555 fe80::ab08:a3c0:1:37427 ESTABLISHED 621/yggdrasil       
udp6       0      0 :::9001                 :::*                                621/yggdrasil
...
```
Why is this connection (fe80::8c63:de15:b) being established?

And also, why does Yggdrasil open upd port 9001?

Yggdrasil version 0.4.5

**Comment by neilalexander** [comment]
>  Why is this connection (fe80::8c63:de15:b) being established?

Yes, that's multicast discovered.

> But connecting to yourself at a link-local address is still a bit wrong, I think.

Are both of those link-local addresses `fe80::8c63:de15:b` and `fe80::ab08:a3c0:1` really the same machine?

**Comment by ygguser** [comment]
I'm sorry, please! I'm confused with these addresses, these are addresses on different machines. And I also did not expect the connection via Multicast Peer Discovery to be via link-local IPv6 ...
I close this question...
