### ISSUE TITLE
Multiple incoming connections with the same Public Key.

### ISSUE THREAD

**Issue by DrewCyber** [yggdrasil-network/yggdrasil-go#961]
I see that my node has multiple incoming connections with same Public Key from the same ip address.
Just wondering, if this should be handled by app and how could it impact for routing.

```
root@OpenWrt:~# yggdrasilctl getpeers
Port	                           Public Key                           	              IP Address              	 Uptime 	 RX  	 TX  	                URI
5   	558019f8a0aaf01d1d77eae681e2e72b319ac6d7cb6fbcf4dbdde05d28f6e29a	201:a9ff:981d:7d54:3f8b:8a20:5465:f874	33m45s  	 3kb 	 3kb 	tls://85.174.194.106:5679
8   	558019f8a0aaf01d1d77eae681e2e72b319ac6d7cb6fbcf4dbdde05d28f6e29a	201:a9ff:981d:7d54:3f8b:8a20:5465:f874	33m45s  	 3kb 	 2kb 	tls://85.174.194.106:5701

14  	c427b9bde7800f7a059a7d08fbeb4d35cebb322c4702a24138e9a492246753ee	200:77b0:8c84:30ff:e10b:f4cb:5ee:829  	30m4s   	 2kb 	 2kb 	tls://178.216.222.194:47490
15  	c427b9bde7800f7a059a7d08fbeb4d35cebb322c4702a24138e9a492246753ee	200:77b0:8c84:30ff:e10b:f4cb:5ee:829  	30m4s   	 2kb 	 2kb 	tls://178.216.222.194:62804
```

Probably we should deny second connection in this case.

**Comment by neilalexander** [comment]
It's possible to receive connections from the same node over more than one network interface and this is in some cases desirable (i.e. if you are getting multicast beacons over both Wi-Fi and wired ethernet, or your server is multihomed). It doesn't impact routing, Yggdrasil will generally select one of them (the one that has the lower latency path to the root) and ignore the other until it is needed.
