### ISSUE TITLE
After update 0.4.5 for windows the Yggdrasil Service no longer starts automatically and crash

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [yggdrasil-network/yggdrasil-go#963]
This can be seen immediately after installing the update it did not immediately start itself.
Also after update the service began to crash:
In eventlog:
`Служба "Yggdrasil Service" неожиданно прервана. Это произошло (раз): 1.`
```XML
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2022-10-19T08:43:03.6777750Z" /> 
  <EventRecordID>91393</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="956" ThreadID="6212" /> 
  <Channel>System</Channel> 
  <Computer>name</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">Yggdrasil Service</Data> 
  <Data Name="param2">1</Data> 
  <Binary>590067006700640072006100730069006C000000</Binary> 
  </EventData>
  </Event>
```
`Служба "Yggdrasil Service" неожиданно прервана. Это произошло (раз): 2.`
```XML
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2022-10-19T17:31:21.9244655Z" /> 
  <EventRecordID>91446</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="956" ThreadID="3044" /> 
  <Channel>System</Channel> 
  <Computer>name</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">Yggdrasil Service</Data> 
  <Data Name="param2">2</Data> 
  <Binary>590067006700640072006100730069006C000000</Binary> 
  </EventData>
  </Event>
```

**Comment by 0x4E69676874466F78** [comment]
@neilalexander 
> Which version of Windows?

10, 21H1
> Can you please get the log 

Check your email.

**Comment by 0x4E69676874466F78** [comment]
To be properly understood:
1. After the update, the service itself could not start. I was able to run it manually.
2. The service crashed a couple of times on its own (after some time).
I can also add that the problem with autostart is not only mine (friend reported and there were mentions of the problem in the chat room).

**Comment by 0x4E69676874466F78** [comment]
Bump. v0.4.6 completely stopped working for me.
Send email with logs and config.

**Comment by vikulin** [comment]
I confirm the error on Windows 11 after OS start. It showing me the service is down with following error code: 7034. Exactly the same as reported here.

Reference from MS:
https://social.technet.microsoft.com/wiki/contents/articles/13764.event-id-7034-service-terminated.aspx#Possible_Causes

**Comment by 0x4E69676874466F78** [comment]
@neilalexander maybe do a workaround via recovery service settings?
e.g. `sc failure yggdrasil reset=3 actions=restart/1000/restart/5000/restart/10000`

**Comment by neilalexander** [comment]
Closing as stale.
