### ISSUE TITLE
Multicast discovery breaks LAN

### ISSUE THREAD

**Issue by Saiv46** [yggdrasil-network/yggdrasil-go#967]
**Expected behaviour**: Peers find themselves over LAN by multicast.

**Observed behaviour**: Same as expected, but after some time router begins to drop packets on LAN.
Rebooting it helps for some time, but problem can be solved permanently only by disabling multicast discovery.

**Yggdrasil version**: from 0.3.1 up to 0.4.5

**Devices**:
- Windows 10
- Samsung A50 (Android 10)
- Ubuntu-based Linux
- Router NETIS N1

**Possible solution**: Make peers beacon after startup or network change (interface is up), then slow down to beaconing every 10s (instead of every 1s).

**Comment by neilalexander** [comment]
Multicast beacons already back off to a periodic interval but this sounds more like a network issue than an Yggdrasil issue. I have never heard of this being reproduced anywhere else.
