### ISSUE TITLE
GetPeersJSON returns Remote with missing URL schema at app start

### ISSUE THREAD

**Issue by vikulin** [yggdrasil-network/yggdrasil-go#973]
GetPeersJSON returns Remote with missing URL schema:

```
[
{"IP":"fc00:eede:5c1e:73ad:3f98:4840:63d:5ba7",
"RXBytes":1340,
"TXBytes":1954,
"Coords":[1,15],
"Key":"iJDR8MYpYDPb3/zhUixufEDzRFDorL7AJih6gmxLxTo\\u003d",
"Port":1,
"Priority":0,
"Remote": "[fe80::15f:5dab:293c:a6%wlan0]:47569",
"Root":"Jx0jL93yapdgxkCB5hsEUy2l2g8RdPMWWb2GLqxC2wM\\u003d",
"Uptime":2.48031411E9}"
]
```

I noticed that comes from https://github.com/yggdrasil-network/yggdrasil-go/blob/develop/src/core/api.go#L80 and can skip full connection name in following condition:
https://github.com/yggdrasil-network/yggdrasil-go/blob/develop/src/core/api.go#L81
```
		if name := names[p.Conn]; name != "" {
			info.Remote = name
		}
```

I did not have much time to investigate why names[p.Conn] is empty but should be fixed since it beaks URL parsing: [fe80::15f:5dab:293c:a6%wlan0]:47569 is invalid URL missing schema and results Crispa mobile app error.

**Comment by neilalexander** [comment]
Closing as out-of-date.
