### ISSUE TITLE
Problems with public peers

### ISSUE THREAD

**Issue by ygguser** [yggdrasil-network/yggdrasil-go#987]
Unfortunately, not all public peers work stably. Some appear and disappear after a short time. This is one of the reasons for the unstable connectivity of the network. We have to constantly manually check and change the peers in the configuration file. We need automation! Please make automatic addition of the best (ping time) peer and removal of "dead" peers and peers with high ping time.

**Comment by neilalexander** [comment]
Adding and removing peers automatically is *deliberately* out of scope for the project at the moment. Our goal is to make routing work with the links we are given, so to change those links automatically changes the game significantly. It also would create far more topology changes which the rest of the network has to adapt to.

It's also incredibly difficult to get automatic peer selection right. The only way to do it is to use centralised data sources to advertise peers. In addition to that, latency is not necessarily the best metric as the path might still not have good throughput. It's also possible that the peer selection algorithm fails and causes specific public peers to become overloaded.

The public peers are really just intended to help people bootstrap themselves into the network and to play around. They are not intended to be a permanent network backbone. If you have specific reliability requirements or topologies, you would need to run additional nodes yourself.

**Comment by ygguser** [comment]
I just wish the "global" Yggdrasil network would work more stably.

For lack of a better one and due to the complexity of implementing the selection of the "best" peers, it would be good to at least select nodes by ping from the list of peers on github and automatically add/remove them...

**Comment by ygguser** [comment]
https://github.com/ygguser/peers_updater
