### ISSUE TITLE
cisco anyconnect also uses 200::/7

### ISSUE THREAD

**Issue by jhaar** [yggdrasil-network/yggdrasil-go#988]
Hi there

I'm running Yggdrasil under Windows connecting successfully back to a Linux server. However, we use ipv6 over Cisco Anyconnect in the office and when I have that up-and-running (under Windows), Yggdrasil stops working: eg ping in either direction stops working.

Looking at the Windows routing table, I can see the Anyconnect interface also has a route to 200::/7 with a METRIC of 32 - which is much higher priority than Yggdrasil which has a METRIC of 256. Bring down the Anyconnect interface and Yggdrasil starts working again.

Is there a way to change the Yggdrasil metric - so that these two VPNs can co-exist?  Annoyingly we don't even use Anyconnect for that 200::/7 network (we have other IPv6 networks) - must be some built-in network similar to Yggdrasil.

Thanks

Jason

**Comment by neilalexander** [comment]
We use the 200::/7 range because it is marked as deprecated but we can't predict when collisions will occur with other projects/products that have the same idea. I am not convinced we should fix this specifically.
