### ISSUE TITLE
Problem with the removepeer API method

### ISSUE THREAD

**Issue by xaozai** [yggdrasil-network/yggdrasil-go#994]
First I do `yggdrasilctl getPeers` to get the connected peers.
Next, I select one peer from the output list and do `yggdrasilctl removepeer uri=tcp://peeruri`.
Then I do `yggdrasilctl getPeers` again and see all the same peers as the first time.
I do `yggdrasilctl getPeers` again after some time - the peer does not disappear from the list.
But if I do `yggdrasilctl removepeer uri=tcp://peeruri` again, I will see in the output "Admin socket returned an error: peer not configured".
Please explain how it works.

**Comment by vikulin** [comment]
@neilalexander I see following issues:
Peer is getting removed from c.config._peers but:
* c.links._links are still not updated
* retry = func(attempt int) is reconnecting when the peer connection is closed - this needs to check whether the close event invoked by peer removing method and skip retry function
* func (c *Core) _addPeerLoop() need to change and add following condition:

```
			info, err := c.CallPeer(u, intf)
			if err != nil {
				c.log.Errorln("Failed to add peer:", err)
			} else {
				phony.Block(c, func() {
					c.config._peers[Peer{u.String(), intf}] = &info
				})
			}
```
This code has an impact for ```func (c *Core) RemovePeer(uri string, sourceInterface string) error``` method when linkInfo is nil
```
		linkInfo, ok := c.config._peers[peer]
		if !ok {
			err = fmt.Errorf("peer not configured")
			return
		}
		if ok && linkInfo != nil {
```
As result second peer removal fails with ```fmt.Errorf("peer not configured")``` error.

**Comment by neilalexander** [comment]
Closing as this was refactored in v0.5.

**Comment by vikulin** [comment]
I have no idea why this was closed since that method was marked as "not implemented":
https://github.com/yggdrasil-network/yggdrasil-go/commit/e110dd46fd82e8ae9e85c7eaf50c3adf8190b575#diff-eee080a6af13035a5ddd2c7d0f2b2c991758d624b3a363e64e8e428c1a8afc1eR196

**Comment by neilalexander** [comment]
You're right, I had that work sat on a branch and had forgot to cherry-pick it in. Have done so now.
